export type AINewsItem = { id: string; title: string; summary: string; source: string; url: string; published: string; category: string; image: string };

// Stable random-looking imagery with a unique seed per story. No two stories reuse an image URL.
const imageFor = (id: string) => `https://picsum.photos/seed/streamearn-news-${encodeURIComponent(id)}/1200/700`;

export const aiNews: AINewsItem[] = [
  { id: 'runable-agents-growth', title: 'AI agents are moving from building software to running growth workflows', summary: 'Runable raised new funding around agents that can move beyond creating websites and apps into ongoing growth and operational work.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/26/runable-hits-21m-to-bet-ai-agents-can-go-from-building-businesses-to-growing-them/', published: 'Aug 26, 2026', category: 'AI Agents', image: imageFor('runable-agents-growth') },
  { id: 'keenable-agent-search', title: 'Web search infrastructure is being redesigned for AI agents', summary: 'Keenable emerged from stealth with an agent-focused web index, reflecting a shift from human search pages toward machine-readable retrieval.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/25/accel-backed-keenable-is-indexing-the-web-for-ai-agents/', published: 'Aug 25, 2026', category: 'AI Search', image: imageFor('keenable-agent-search') },
  { id: 'cowork-memory', title: 'AI workspaces are adding persistent memory to reduce repeated instructions', summary: 'Claude Cowork received a memory-focused update designed to preserve useful context between conversations and longer-running work.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/25/claude-cowork-finally-remembers-what-you-told-the-app-in-chat/', published: 'Aug 25, 2026', category: 'AI Workflows', image: imageFor('cowork-memory') },
  { id: 'agent-security-containment', title: 'AI agent containment is becoming a major security challenge', summary: 'Recent reporting and research highlight the difficulty of controlling increasingly capable agents once they can access tools, systems and sensitive data.', source: 'Reuters', url: 'https://www.reuters.com/technology/artificial-intelligence/ai-firms-cant-yet-contain-what-theyve-built-study-finds-2026-08-19/', published: 'Aug 19, 2026', category: 'AI Security', image: imageFor('agent-security-containment') },
  { id: 'instinct-agent-risk', title: 'Powerful personal AI assistants raise new privacy and permission questions', summary: 'Early reactions to agentic assistants are putting broad access, permissions and data-handling practices under renewed scrutiny.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/24/instincts-powerful-ai-assistant-is-raising-privacy-and-security-concerns/', published: 'Aug 24, 2026', category: 'AI Security', image: imageFor('instinct-agent-risk') },
  { id: 'meta-ai-transformation', title: 'Meta experience shows the difficulty of forcing rapid AI-led organisational change', summary: 'Reuters reports that Meta adjusted its aggressive AI-driven workforce transformation plans after productivity and operational concerns surfaced.', source: 'Reuters', url: 'https://www.reuters.com/investigations/mark-zuckerberg-had-bold-plan-replace-meta-staff-with-ai-heres-how-it-imploded-2026-08-26/', published: 'Aug 26, 2026', category: 'AI Business', image: imageFor('meta-ai-transformation') },
  { id: 'inherent-research-agent', title: 'Research agents are being built to reproduce scientific findings', summary: 'Inherent says its research-focused agent can independently reproduce published scientific results, showing how agent evaluation is expanding beyond coding.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/22/inherent-founded-by-deepmind-alumni-says-its-ai-teammate-just-outperformed-anthropic-and-openai-at-replicating-research/', published: 'Aug 22, 2026', category: 'AI Research', image: imageFor('inherent-research-agent') },
  { id: 'nvidia-agent-harness', title: 'The agent harness is becoming as important as raw model capability', summary: 'Nvidia research is adding to a broader industry focus on the software harness around AI systems: tools, controls, context, evaluation and execution loops.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/21/nvidia-just-showed-that-the-harness-not-the-ai-model-is-now-the-real-hero/', published: 'Aug 21, 2026', category: 'AI Engineering', image: imageFor('nvidia-agent-harness') },
  { id: 'ai-coding-adoption', title: 'AI coding agents continue shifting software development toward multi-step workflows', summary: 'Developer research points to continued adoption of agentic coding workflows rather than AI being limited to autocomplete and single-line suggestions.', source: 'JetBrains Research', url: 'https://blog.jetbrains.com/research/2026/08/ai-coding-agent-adoption-2026/', published: 'Aug 2026', category: 'Developer Tools', image: imageFor('ai-coding-adoption') },
  { id: 'ai-infrastructure-spend', title: 'AI infrastructure spending keeps expanding across compute and data centers', summary: 'Companies continue investing heavily in the physical infrastructure needed to support growing AI workloads and agent usage.', source: 'Reuters', url: 'https://www.reuters.com/technology/nvidia-invests-data-center-developer-cloverleaf-infrastructure-2026-08-21/', published: 'Aug 21, 2026', category: 'AI Infrastructure', image: imageFor('ai-infrastructure-spend') },
  { id: 'ai-debt-fatigue', title: 'AI infrastructure financing is creating a new investment risk conversation', summary: 'Reuters reports that the surge in corporate borrowing for AI infrastructure is testing investor appetite as spending accelerates.', source: 'Reuters', url: 'https://www.reuters.com/legal/transactional/us-corporate-ai-debt-surge-tests-investor-limits-2026-08-21/', published: 'Aug 21, 2026', category: 'AI Business', image: imageFor('ai-debt-fatigue') },
  { id: 'browser-agent-security', title: 'Browser agents are becoming a major new security surface', summary: 'As agents gain the ability to navigate websites and interact with software, permission boundaries, isolation and monitoring are becoming central engineering concerns.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/24/instincts-powerful-ai-assistant-is-raising-privacy-and-security-concerns/', published: 'Aug 24, 2026', category: 'Browser Agents', image: imageFor('browser-agent-security') },
];
