export type AINewsItem = { id: string; title: string; summary: string; source: string; url: string; published: string; category: string; image: string };

// Primary feed: meaningful AI/technology developments from the latest verified window.
// Every story has a unique visual seed so cards do not repeat imagery.
const imageFor = (id: string) => `https://picsum.photos/seed/streamearn-news-${encodeURIComponent(id)}/1200/700`;

export const aiNews: AINewsItem[] = [
  { id: 'anthropic-model-hardware-standard', title: 'Anthropic previews a standard for AI agents to control physical devices', summary: 'Anthropic introduced a research preview of the Model Hardware Standard, a framework intended to let AI agents operate programmable lab and industrial devices such as microscopes and robotic arms while the design undergoes safety evaluation.', source: 'Reuters', url: 'https://www.reuters.com/technology/anthropic-unveils-new-framework-allowing-ai-agents-operate-physical-devices-2026-08-27/', published: 'Aug 27, 2026', category: 'AI Agents & Robotics', image: imageFor('anthropic-model-hardware-standard') },
  { id: 'rogue-ai-defense-letter', title: 'More than 100 technology companies call for stronger defenses against rogue AI', summary: 'OpenAI, Anthropic, Google, Microsoft and major cybersecurity companies joined a public call for coordinated defenses against AI-enabled cyberattacks as agent capabilities become more autonomous.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/27/openai-anthropic-google-and-100-other-companies-call-for-action-to-defend-against-rogue-ai/', published: 'Aug 27, 2026', category: 'AI Security', image: imageFor('rogue-ai-defense-letter') },
  { id: 'cursor-ai-cyberattacks', title: 'AI coding agents become a new target as attackers abuse Cursor workflows', summary: 'Reuters reports that a ransomware group used Cursor-powered workflows in attacks against several organizations, reinforcing the need for strong permissions, review and isolation around AI coding agents.', source: 'Reuters', url: 'https://www.reuters.com/world/russian-speaking-cybercriminals-used-spacexs-cursor-ai-tool-hack-seven-companies-2026-08-27/', published: 'Aug 27, 2026', category: 'AI Security & Coding', image: imageFor('cursor-ai-cyberattacks') },
  { id: 'anthropic-matx-chip-talks', title: 'Anthropic explores custom AI-chip strategy as compute demand rises', summary: 'Reuters reports Anthropic explored a potential acquisition of AI-chip startup MatX before discussions shifted toward a possible partnership, highlighting the growing push toward specialized AI hardware.', source: 'Reuters', url: 'https://www.reuters.com/business/finance/anthropic-planned-then-abandoned-7-billion-purchase-matx-sources-say-2026-08-27/', published: 'Aug 27, 2026', category: 'AI Infrastructure', image: imageFor('anthropic-matx-chip-talks') },
  { id: 'nvidia-agi-comments', title: 'NVIDIA CEO reignites the AGI debate while emphasizing useful AI outcomes', summary: 'During NVIDIA earnings commentary, Jensen Huang said the company had achieved AGI while also questioning the usefulness of the label, underscoring the lack of a common industry definition for AGI.', source: 'The Verge', url: 'https://www.theverge.com/ai-artificial-intelligence/985597/jensen-huang-says-nvidia-achieved-senseless-agi', published: 'Aug 27, 2026', category: 'AI Industry', image: imageFor('nvidia-agi-comments') },
  { id: 'cisco-myagent-enterprise', title: 'Cisco gives employees personalized AI agents for internal work', summary: 'Cisco is deploying personalized MyAgent assistants to its global workforce, with enterprise connectors, approval controls and policy infrastructure designed to keep agent actions within governed boundaries.', source: 'The Wall Street Journal', url: 'https://www.wsj.com/cio-journal/cisco-gave-all-90-000-employees-their-own-ai-agent-1a4ad8bc', published: 'Aug 27, 2026', category: 'Enterprise AI', image: imageFor('cisco-myagent-enterprise') },
];
