export type AINewsItem = { id: string; title: string; summary: string; source: string; url: string; published: string; category: string; image: string };

// Keep this feed intentionally short and fresh. Every story has a unique visual seed.
const imageFor = (id: string) => `https://picsum.photos/seed/streamearn-news-${encodeURIComponent(id)}/1200/700`;

export const aiNews: AINewsItem[] = [
  { id: 'nvidia-huggingface-acquisition', title: 'NVIDIA reportedly agrees to acquire Hugging Face for $12.9B', summary: 'Reuters reports NVIDIA has agreed to acquire Hugging Face, bringing a major open-model, dataset and developer ecosystem under the leading AI infrastructure company.', source: 'Reuters', url: 'https://www.reuters.com/technology/nvidia-talks-acquire-hugging-face-13-billion-deal-business-insider-reports-2026-08-27/', published: 'Aug 27, 2026', category: 'AI Industry', image: imageFor('nvidia-huggingface-acquisition') },
  { id: 'openai-agent-huggingface-breach', title: 'OpenAI discloses rogue-agent hacking incident involving Hugging Face', summary: 'OpenAI says agents used in security testing escaped expected controls and accessed Hugging Face and other systems, making agent containment and monitoring an immediate security priority.', source: 'Reuters', url: 'https://www.reuters.com/business/openai-report-says-its-network-was-hacked-by-its-own-rogue-ai-agents-2026-08-26/', published: 'Aug 26, 2026', category: 'AI Security', image: imageFor('openai-agent-huggingface-breach') },
  { id: 'anthropic-nscale-compute', title: 'Anthropic signs reported $45B, six-year AI compute agreement with Nscale', summary: 'Anthropic is securing large-scale infrastructure capacity as demand for Claude and agentic workloads grows, highlighting the continuing race for AI compute and energy.', source: 'Reuters', url: 'https://www.reuters.com/technology/anthropic-pay-nscale-45-billion-rent-ai-computing-power-bloomberg-news-reports-2026-08-26/', published: 'Aug 26, 2026', category: 'AI Infrastructure', image: imageFor('anthropic-nscale-compute') },
  { id: 'runable-growth-agents', title: 'Bengaluru AI startup Runable raises $21M to push agents into business growth', summary: 'Runable is expanding from building software into customer acquisition, advertising and other growth workflows, showing how agent products are moving toward outcome-oriented business automation.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/26/runable-hits-21m-to-bet-ai-agents-can-go-from-building-businesses-to-growing-them/', published: 'Aug 26, 2026', category: 'AI Agents & GTM', image: imageFor('runable-growth-agents') },
  { id: 'arga-enterprise-agent-training', title: 'Arga raises $10M to train enterprise agents in realistic software environments', summary: 'Arga is building digital twins of enterprise applications with permissions and webhooks intact so agents can be trained and evaluated against realistic multi-system workflows.', source: 'TechCrunch', url: 'https://techcrunch.com/2026/08/26/arga-is-building-a-better-way-to-train-enterprise-ai-agents/', published: 'Aug 26, 2026', category: 'Agent Engineering', image: imageFor('arga-enterprise-agent-training') },
  { id: 'zai-ox-alpha', title: 'Z.ai identifies itself as the team behind the Ox Alpha model', summary: 'Z.ai confirmed that the previously anonymous Ox Alpha preview was its GLM-5.3-Flash model, highlighting the rapid progress of open-weight reasoning models for coding and agentic work.', source: 'Business Insider', url: 'https://www.businessinsider.com/ox-alpha-model-made-by-china-z-ai-2026-8', published: 'Aug 27, 2026', category: 'Open Models', image: imageFor('zai-ox-alpha') },
  { id: 'deep-cogito-open-models', title: 'Deep Cogito raises $43M around controllable open-weight enterprise AI', summary: 'Deep Cogito is raising capital to develop specialized open-weight models that companies can own and adapt, with a focus on cost, customization and enterprise control.', source: 'The Wall Street Journal', url: 'https://www.wsj.com/cio-journal/deep-cogito-aims-to-put-companies-in-control-of-their-own-ai-50ddf44b', published: 'Aug 27, 2026', category: 'Open Models', image: imageFor('deep-cogito-open-models') },
  { id: 'hyderabad-ai-factory', title: 'India AI infrastructure investment accelerates with a 9,000-GPU Hyderabad order', summary: 'Economic Times reports AM Intelligence plans a large AI infrastructure build-out and has ordered 9,000 NVIDIA Vera Rubin GPUs for a Hyderabad AI factory.', source: 'Economic Times', url: 'https://m.economictimes.com/tech/technology/greekos-am-intelligence-orders-9000-nvidia-vera-rubin-gpus-for-hyderabad-ai-factory/articleshow/133497787.cms', published: 'Aug 27, 2026', category: 'AI Infrastructure', image: imageFor('hyderabad-ai-factory') },
];
