export type AiTool = {
  name: string;
  logoKey: string;
  link: string;
  description?: string;
  tags?: string[];
};

export type AiToolCategory = {
  name: string;
  description: string;
  tools: AiTool[];
};

const t = (name: string, link: string, description: string, tags: string[] = []): AiTool => ({ name, logoKey: 'futureAbstract', link, description, tags });

export const aiToolsPyramid: AiToolCategory[] = [
  { name: 'AI Assistants & Workspaces', description: 'General-purpose assistants for research, writing, analysis, files and everyday work.', tools: [t('ChatGPT','https://chatgpt.com/','General-purpose AI workspace for research, writing, files and automation.'),t('Claude','https://claude.ai/','Long-form writing, document work, analysis and collaborative tasks.'),t('Gemini','https://gemini.google.com/','Assistant integrated with Google services, search and multimodal workflows.'),t('Grok','https://grok.com/','Conversational assistant with real-time information workflows.'),t('Perplexity','https://www.perplexity.ai/','Answer engine focused on web research and cited sources.'),t('Poe','https://poe.com/','Multi-provider assistant hub with bots and custom workflows.')] },
  { name: 'AI Coding Agents & Developer Tools', description: 'AI-native development environments, terminal agents, code review and software delivery tools.', tools: [t('Cursor','https://cursor.com/','AI-native coding environment for large codebases and agentic development.'),t('Windsurf','https://windsurf.com/','Agentic coding environment with context-aware development workflows.'),t('GitHub Copilot','https://github.com/features/copilot','Coding assistance across editors, GitHub and software workflows.'),t('Claude Code','https://www.anthropic.com/claude-code','Terminal-first coding agent for repository-level engineering tasks.'),t('Replit','https://replit.com/','Build, test and deploy applications from a browser-based workspace.'),t('Cline','https://cline.bot/','Open coding agent for editor-based autonomous development workflows.'),t('Aider','https://aider.chat/','Terminal pair-programming workflow for repositories.'),t('OpenCode','https://opencode.ai/','Open-source terminal coding agent and development workflow.'),t('JetBrains AI','https://www.jetbrains.com/ai/','AI-assisted development inside JetBrains IDE workflows.')] },
  { name: 'AI App Builders & Vibe Coding', description: 'Generate interfaces, prototypes and production-oriented applications from natural language.', tools: [t('Lovable','https://lovable.dev/','Natural-language application builder for rapid full-stack prototypes.'),t('Bolt.new','https://bolt.new/','Browser-based app builder for generating and running web projects.'),t('v0','https://v0.dev/','Prompt-driven interface and application generation.'),t('Base44','https://base44.com/','AI application builder for turning ideas into working products.'),t('Magic Patterns','https://www.magicpatterns.com/','Rapid product UI generation and prototyping.'),t('Tempo','https://tempo.new/','AI-assisted product and interface development.')] },
  { name: 'AI Agents & Task Automation', description: 'Delegate multi-step work across apps, tools and business processes.', tools: [t('Zapier','https://zapier.com/','Automation platform connecting AI workflows with thousands of apps.'),t('Make','https://www.make.com/','Visual automation and multi-step workflow orchestration.'),t('n8n','https://n8n.io/','Self-hostable workflow automation with AI and tool integrations.'),t('Lindy','https://www.lindy.ai/','Build personal and business agents for repetitive workflows.'),t('Relevance AI','https://relevanceai.com/','Build and deploy AI agents for operational workflows.'),t('Gumloop','https://www.gumloop.com/','Visual AI automation for data and repetitive business tasks.'),t('Relay.app','https://www.relay.app/','Human-in-the-loop AI workflow automation.'),t('Dify','https://dify.ai/','Build AI applications, workflows and agentic experiences.')] },
  { name: 'Browser & Computer Agents', description: 'Tools that let agents navigate websites, operate browsers and complete computer tasks.', tools: [t('Browser Use','https://browser-use.com/','Open framework for browser automation by AI agents.'),t('Browserbase','https://www.browserbase.com/','Infrastructure for production browser agents and automation.'),t('Stagehand','https://www.stagehand.dev/','Developer framework for reliable AI browser automation.'),t('BrowserGym','https://github.com/ServiceNow/BrowserGym','Environment and tooling for browser-agent research and evaluation.'),t('Opera Neon','https://www.opera.com/neon','Agentic browser experience with direct browser task execution.'),t('Steel','https://steel.dev/','Browser infrastructure for AI agents and automated workflows.')] },
  { name: 'MCP, Agent Interoperability & Tool Connectivity', description: 'Standards and platforms for connecting agents to tools, data and other agents.', tools: [t('Model Context Protocol','https://modelcontextprotocol.io/','Open protocol for connecting AI applications to tools and data.'),t('MCP.so','https://mcp.so/','Directory for discovering MCP servers and integrations.'),t('Smithery','https://smithery.ai/','Registry and infrastructure for MCP integrations.'),t('Composio','https://composio.dev/','Agent tool integrations, authentication and action infrastructure.'),t('Pipedream','https://pipedream.com/','APIs and workflow infrastructure for agent tool access.'),t('AGNTCY','https://www.agntcy.org/','Open ecosystem for interoperable agent infrastructure.')] },
  { name: 'RAG, Search & Knowledge Systems', description: 'Search, retrieval, document intelligence and knowledge layers for AI applications.', tools: [t('LlamaIndex','https://www.llamaindex.ai/','Framework for connecting AI applications to private data and knowledge.'),t('LangChain','https://www.langchain.com/','Application framework for retrieval, agents and tool workflows.'),t('Pinecone','https://www.pinecone.io/','Managed vector database and retrieval infrastructure.'),t('Weaviate','https://weaviate.io/','Open-source vector database for semantic search and AI applications.'),t('Qdrant','https://qdrant.tech/','Vector search engine for retrieval and semantic applications.'),t('Chroma','https://www.trychroma.com/','Developer-friendly retrieval and vector database layer.'),t('NotebookLM','https://notebooklm.google.com/','Source-grounded research and document knowledge workspace.'),t('Elicit','https://elicit.com/','Research assistant for literature discovery and synthesis.')] },
  { name: 'AI Evaluation, Testing & Observability', description: 'Measure quality, reliability, traces, cost and safety of AI applications and agents.', tools: [t('LangSmith','https://smith.langchain.com/','Tracing, evaluation and observability for AI applications.'),t('Arize Phoenix','https://phoenix.arize.com/','Open-source observability and evaluation for AI systems.'),t('Weights & Biases Weave','https://wandb.ai/site/weave/','Evaluation and observability for AI application workflows.'),t('Braintrust','https://www.braintrust.dev/','AI evaluation, tracing and production quality workflows.'),t('Langfuse','https://langfuse.com/','Open-source AI application observability and evaluation.'),t('DeepEval','https://deepeval.com/','Testing framework for evaluating AI application quality.'),t('Promptfoo','https://www.promptfoo.dev/','Open-source testing for prompts, agents and AI applications.')] },
  { name: 'AI Search, Research & Intelligence', description: 'Deep research, web intelligence, academic discovery and source-based analysis.', tools: [t('Perplexity','https://www.perplexity.ai/','Fast web research with source-backed answers.'),t('You.com','https://you.com/','AI search and research workspace.'),t('Consensus','https://consensus.app/','Evidence-focused academic research search.'),t('Scite','https://scite.ai/','Research discovery with citation context and evidence.'),t('Exa','https://exa.ai/','Search infrastructure designed for AI applications and agents.'),t('Tavily','https://tavily.com/','Search API designed for AI agents and research workflows.'),t('Firecrawl','https://www.firecrawl.dev/','Web crawling and extraction infrastructure for AI applications.')] },
  { name: 'Image Generation & Creative Design', description: 'Generate, edit, upscale and transform images for products, marketing and creative work.', tools: [t('Midjourney','https://www.midjourney.com/','Creative image generation and visual ideation.'),t('Adobe Firefly','https://firefly.adobe.com/','Generative creation and editing inside Adobe workflows.'),t('Ideogram','https://ideogram.ai/','Image generation with strong typography and design workflows.'),t('Recraft','https://www.recraft.ai/','Design-focused generation for graphics, vectors and brand assets.'),t('Krea','https://www.krea.ai/','Real-time creative generation, enhancement and visual exploration.'),t('Leonardo AI','https://leonardo.ai/','Creative image generation, editing and asset production.'),t('Freepik AI','https://www.freepik.com/ai','Integrated AI image and design creation tools.'),t('Canva AI','https://www.canva.com/ai/','AI-assisted design, layout, copy and creative production.')] },
  { name: 'AI Video & Visual Production', description: 'Video generation, editing, avatars, motion graphics and production workflows.', tools: [t('Runway','https://runwayml.com/','AI video generation and creative production platform.'),t('Kling AI','https://klingai.com/','Generative video and visual storytelling.'),t('Luma','https://lumalabs.ai/','AI video and creative visual generation.'),t('Higgsfield','https://higgsfield.ai/','AI video creation focused on cinematic and social content.'),t('HeyGen','https://www.heygen.com/','AI avatars, localization and business video production.'),t('Synthesia','https://www.synthesia.io/','Business video creation with AI presenters and localization.'),t('Descript','https://www.descript.com/','Text-based video and audio editing workflow.'),t('CapCut','https://www.capcut.com/','AI-assisted short-form video editing and creation.')] },
  { name: 'Voice, Audio & Music', description: 'Voice agents, speech, dubbing, audio editing and music creation.', tools: [t('ElevenLabs','https://elevenlabs.io/','Voice generation, dubbing and conversational audio tools.'),t('PlayAI','https://play.ai/','Voice agents and conversational audio infrastructure.'),t('Cartesia','https://cartesia.ai/','Real-time voice infrastructure for conversational applications.'),t('Resemble AI','https://www.resemble.ai/','Synthetic voice and audio production tools.'),t('Suno','https://suno.com/','Music creation and song production from prompts.'),t('Udio','https://www.udio.com/','Generative music creation and editing.'),t('Adobe Podcast','https://podcast.adobe.com/','AI-assisted voice cleanup and podcast production.'),t('Auphonic','https://auphonic.com/','Automated audio leveling, cleanup and production.')] },
  { name: 'Writing, Content & Marketing', description: 'Writing, editing, SEO, campaign content and marketing production.', tools: [t('Jasper','https://www.jasper.ai/','Marketing content and brand workflow platform.'),t('Copy.ai','https://www.copy.ai/','GTM and content workflow automation.'),t('Grammarly','https://www.grammarly.com/','Writing improvement and communication assistance.'),t('Writer','https://writer.com/','Enterprise writing and content workflow platform.'),t('Surfer','https://surferseo.com/','SEO content planning and optimization.'),t('Writesonic','https://writesonic.com/','AI content, search and marketing workflows.'),t('Frase','https://www.frase.io/','SEO research and content optimization.'),t('Typefully','https://typefully.com/','Social content creation and publishing workflow.')] },
  { name: 'Productivity, Notes & Meetings', description: 'Meeting intelligence, knowledge capture, planning and personal productivity.', tools: [t('Notion AI','https://www.notion.com/product/ai','Workspace search, writing, knowledge and task assistance.'),t('Microsoft Copilot','https://www.microsoft.com/microsoft-365/copilot','AI assistance across Microsoft productivity workflows.'),t('Granola','https://www.granola.ai/','AI meeting notes and conversation capture.'),t('Otter','https://otter.ai/','Meeting transcription, notes and conversation intelligence.'),t('Fireflies.ai','https://fireflies.ai/','Meeting capture, summaries and searchable conversation knowledge.'),t('Fathom','https://fathom.video/','Meeting recording, summaries and follow-up workflows.'),t('Rewind','https://www.rewind.ai/','Personal knowledge capture and retrieval.'),t('Motion','https://www.usemotion.com/','AI-assisted scheduling, planning and task management.')] },
  { name: 'Sales, GTM & Lead Intelligence', description: 'Prospecting, enrichment, outreach, CRM intelligence and revenue workflows.', tools: [t('Clay','https://www.clay.com/','Data enrichment and GTM workflow automation.'),t('Apollo','https://www.apollo.io/','B2B prospecting, enrichment and sales engagement.'),t('Instantly','https://instantly.ai/','Outbound email and sales engagement automation.'),t('HubSpot','https://www.hubspot.com/','CRM, marketing, sales and AI-assisted customer workflows.'),t('Common Room','https://www.commonroom.io/','Signal-based GTM and customer intelligence.'),t('Gong','https://www.gong.io/','Revenue intelligence from customer conversations.'),t('Lavender','https://www.lavender.ai/','Sales email coaching and personalization.'),t('Hunter','https://hunter.io/','Email discovery and verification for prospecting.')] },
  { name: 'Customer Support & Service Agents', description: 'AI-assisted support, customer operations, knowledge and service automation.', tools: [t('Intercom','https://www.intercom.com/','AI-powered customer support and service operations.'),t('Zendesk','https://www.zendesk.com/','Customer service platform with AI-assisted support workflows.'),t('Fin','https://www.intercom.com/fin','Customer service agent for support automation.'),t('Gorgias','https://www.gorgias.com/','AI-assisted ecommerce customer support.'),t('Ada','https://www.ada.cx/','Automated customer service experiences.'),t('Decagon','https://decagon.ai/','Customer service automation and support agents.')] },
  { name: 'Data, Analytics & BI', description: 'Analyze data, build dashboards, query datasets and automate business intelligence.', tools: [t('Julius AI','https://julius.ai/','Natural-language data analysis and visualization.'),t('Rows','https://rows.com/','Spreadsheet and business analysis with AI workflows.'),t('Hex','https://hex.tech/','Collaborative data analysis and AI-assisted notebooks.'),t('Power BI','https://powerbi.microsoft.com/','Business intelligence and interactive analytics.'),t('Tableau','https://www.tableau.com/','Visual analytics and business intelligence.'),t('Metabase','https://www.metabase.com/','Open analytics and self-service BI.')] },
  { name: 'Cybersecurity & AI Security', description: 'Security operations, code security, threat analysis, governance and AI security.', tools: [t('GitHub Advanced Security','https://github.com/security/advanced-security','Application security and code vulnerability workflows.'),t('Snyk','https://snyk.io/','Developer security for code, dependencies and cloud workloads.'),t('Wiz','https://www.wiz.io/','Cloud security and risk visibility.'),t('CrowdStrike','https://www.crowdstrike.com/','Security operations and threat detection platform.'),t('Microsoft Security Copilot','https://www.microsoft.com/security/business/ai-machine-learning/microsoft-security-copilot','AI-assisted security investigation and response workflows.'),t('Lakera','https://www.lakera.ai/','Security controls for AI applications and agents.'),t('Protect AI','https://protectai.com/','Security and governance for AI systems.'),t('HiddenLayer','https://hiddenlayer.com/','AI security and threat protection.')] },
  { name: 'Education & Learning', description: 'Tutoring, learning support, practice, research and educational content.', tools: [t('Khanmigo','https://www.khanacademy.org/khan-labs','AI-powered tutoring and learning support.'),t('NotebookLM','https://notebooklm.google.com/','Source-grounded study and research workspace.'),t('Quizlet','https://quizlet.com/','AI-assisted study and practice tools.'),t('Duolingo','https://www.duolingo.com/','AI-assisted language learning.'),t('Photomath','https://photomath.com/','Step-by-step math learning assistance.'),t('Wolfram Alpha','https://www.wolframalpha.com/','Computational knowledge and problem solving.')] },
  { name: 'Presentations & Visual Communication', description: 'Generate decks, documents, diagrams and polished visual communication.', tools: [t('Gamma','https://gamma.app/','AI-assisted presentations, documents and web pages.'),t('Beautiful.ai','https://www.beautiful.ai/','Presentation design and layout automation.'),t('Tome','https://tome.app/','AI-assisted visual storytelling and presentations.'),t('Canva','https://www.canva.com/','Visual communication and design workspace.'),t('Napkin AI','https://www.napkin.ai/','Turn ideas and text into visual diagrams.'),t('Whimsical','https://whimsical.com/','AI-assisted diagrams, flowcharts and visual planning.')] },
  { name: 'Local, Open-Source & AI Infrastructure', description: 'Run, serve, manage and build AI applications with flexible infrastructure.', tools: [t('Ollama','https://ollama.com/','Run AI workloads locally with a simple developer interface.'),t('LM Studio','https://lmstudio.ai/','Desktop environment for local AI experimentation.'),t('Hugging Face','https://huggingface.co/','Open AI ecosystem for applications, datasets and tooling.'),t('Together AI','https://www.together.ai/','AI infrastructure and developer APIs.'),t('Groq','https://groq.com/','Fast AI inference infrastructure and developer APIs.'),t('Replicate','https://replicate.com/','Run and integrate AI applications through APIs.'),t('Modal','https://modal.com/','Cloud infrastructure for compute-heavy AI workloads.'),t('RunPod','https://www.runpod.io/','GPU cloud infrastructure for AI development and inference.')] },
  { name: 'Enterprise AI & Business Platforms', description: 'AI embedded into enterprise applications, governance, workflows and business operations.', tools: [t('Salesforce','https://www.salesforce.com/','CRM and agentic customer workflows.'),t('ServiceNow','https://www.servicenow.com/','Enterprise workflow automation and AI operations.'),t('Microsoft 365 Copilot','https://www.microsoft.com/microsoft-365/copilot','AI assistance across enterprise productivity workflows.'),t('Google Workspace','https://workspace.google.com/','AI-assisted productivity and collaboration tools.'),t('Atlassian Intelligence','https://www.atlassian.com/software/artificial-intelligence','AI-assisted software and team workflows.'),t('Notion','https://www.notion.com/','Knowledge, projects and AI-assisted workspace.')] },
  { name: 'Translation & Localization', description: 'Translation, dubbing, localization and multilingual content production.', tools: [t('DeepL','https://www.deepl.com/','High-quality machine translation and writing assistance.'),t('HeyGen','https://www.heygen.com/','Video translation and multilingual localization.'),t('ElevenLabs','https://elevenlabs.io/','Voice dubbing and multilingual audio production.'),t('Smartcat','https://www.smartcat.com/','AI-assisted translation and localization operations.'),t('Phrase','https://phrase.com/','Localization management and multilingual content workflows.')] },
];

export const toolSubLabels: Record<string, string> = Object.fromEntries(aiToolsPyramid.flatMap(category => category.tools.map(tool => [tool.name, category.name])));
