export type BusinessDirectoryResource = {
  id: string;
  title: string;
  url: string;
  description: string;
  tags: string[];
  contactEmail?: string;
  contactPhone?: string;
  sourceType: 'Government' | 'Industry body' | 'Established platform';
  isFavorite: boolean;
  visitCount: number;
};

type Seed = Omit<BusinessDirectoryResource, 'isFavorite' | 'visitCount'>;

const seed: Seed[] = [
  // BUSINESS
  { id:'biz-01', title:'Udyam Registration', url:'https://udyamregistration.gov.in/', description:'Official MSME registration portal; free, paperless registration and permanent Udyam identity.', tags:['Business','India','Government','MSME'], contactEmail:'champions@gov.in', contactPhone:'+91 8308809334', sourceType:'Government' },
  { id:'biz-02', title:'Startup India', url:'https://www.startupindia.gov.in/', description:'DPIIT startup ecosystem portal for recognition, schemes, funding, mentorship, procurement and networking.', tags:['Business','India','Government','Startups'], contactPhone:'1800 115 565', sourceType:'Government' },
  { id:'biz-03', title:'National Single Window System', url:'https://www.nsws.gov.in/', description:'Government gateway to identify and apply for central and state business approvals.', tags:['Business','India','Government','Business Setup'], contactEmail:'contactus-nsws@investindia.org.in', contactPhone:'1800 102 5841', sourceType:'Government' },
  { id:'biz-04', title:'Ministry of Corporate Affairs', url:'https://www.mca.gov.in/', description:'Official corporate registry and company/LLP compliance services in India.', tags:['Business','India','Government','Company Registration'], sourceType:'Government' },
  { id:'biz-05', title:'GST Portal', url:'https://www.gst.gov.in/', description:'Official GST registration, returns, payments and taxpayer services.', tags:['Business','India','Government','Tax'], sourceType:'Government' },
  { id:'biz-06', title:'Government e-Marketplace', url:'https://gem.gov.in/', description:'Government procurement marketplace for sellers, buyers and service providers.', tags:['Business','India','Government','Procurement'], contactEmail:'helpdesk-gem@gov.in', sourceType:'Government' },
  { id:'biz-07', title:'SIDBI', url:'https://www.sidbi.in/en/', description:'Government-backed development finance institution focused on MSME credit, growth and ecosystem support.', tags:['Business','India','Government','Finance','MSME'], contactPhone:'180-022-6753', sourceType:'Government' },
  { id:'biz-08', title:'Ministry of MSME', url:'https://www.msme.gov.in/', description:'Official MSME schemes, programmes, market access, finance and entrepreneurship support.', tags:['Business','India','Government','MSME','Schemes'], sourceType:'Government' },
  { id:'biz-09', title:'MyMSME / Udyami Bharat', url:'https://ubp.msme.gov.in/', description:'Government hub for central and state MSME schemes, business planning tools and support.', tags:['Business','India','Government','MSME','Schemes'], sourceType:'Government' },
  { id:'biz-10', title:'Invest India', url:'https://www.investindia.gov.in/', description:'National investment promotion and facilitation agency for investors and businesses entering or expanding in India.', tags:['Business','India','Investment','Government'], sourceType:'Government' },
  { id:'biz-11', title:'Confederation of Indian Industry', url:'https://www.cii.in/', description:'Major industry body providing business networking, policy, research, market intelligence and industry opportunities.', tags:['Business','India','Industry Body','Networking'], contactEmail:'info@cii.in', contactPhone:'1800 103 1244', sourceType:'Industry body' },
  { id:'biz-12', title:'FICCI', url:'https://www.ficci.in/', description:'National industry chamber connecting businesses with policy, trade, research and sector networks.', tags:['Business','India','Industry Body','Networking'], sourceType:'Industry body' },
  { id:'biz-13', title:'TiE Global', url:'https://tie.org/', description:'Global entrepreneurship network connecting founders, mentors, investors and business communities.', tags:['Business','Global','Networking','Startups'], sourceType:'Industry body' },
  { id:'biz-14', title:'Bharat SME Forum', url:'https://bharatsmeforum.org/', description:'MSME-focused business network and knowledge ecosystem for Indian entrepreneurs.', tags:['Business','India','MSME','Networking'], sourceType:'Industry body' },

  // REAL ESTATE
  { id:'re-01', title:'MahaRERA', url:'https://maharera.mahaonline.gov.in/', description:'Official Maharashtra RERA portal for projects, promoters, agents, complaints and verification.', tags:['Real Estate','India','Government','RERA'], contactEmail:'helpdesk@maharera.mahaonline.gov.in', contactPhone:'022-26561620', sourceType:'Government' },
  { id:'re-02', title:'UP RERA', url:'https://www.up-rera.in/', description:'Official Uttar Pradesh RERA portal to verify registered projects, promoters and agents and access complaints and orders.', tags:['Real Estate','India','Government','RERA'], contactPhone:'0522-2781440', sourceType:'Government' },
  { id:'re-03', title:'Telangana RERA', url:'https://rera.telangana.gov.in/', description:'Official Telangana real estate regulator with registered project, agent, complaint and progress information.', tags:['Real Estate','India','Government','RERA'], contactEmail:'rera-maud@telangana.gov.in', contactPhone:'040-29394973', sourceType:'Government' },
  { id:'re-04', title:'Rajasthan RERA', url:'https://rera.rajasthan.gov.in/', description:'Official Rajasthan RERA portal for project, promoter, agent and complaint searches.', tags:['Real Estate','India','Government','RERA'], sourceType:'Government' },
  { id:'re-05', title:'99acres', url:'https://www.99acres.com/', description:'Large Indian property marketplace for residential and commercial buying, selling and renting.', tags:['Real Estate','India','Property','Marketplace'], sourceType:'Established platform' },
  { id:'re-06', title:'Housing.com', url:'https://housing.com/', description:'Indian property discovery platform covering homes, rentals, commercial property and projects.', tags:['Real Estate','India','Property','Marketplace'], sourceType:'Established platform' },
  { id:'re-07', title:'MagicBricks', url:'https://www.magicbricks.com/', description:'Established Indian real estate marketplace for sale, rent, projects and property research.', tags:['Real Estate','India','Property','Marketplace'], sourceType:'Established platform' },
  { id:'re-08', title:'NoBroker', url:'https://www.nobroker.in/', description:'Owner-focused Indian property platform for buying, renting and property services.', tags:['Real Estate','India','Property','Marketplace'], sourceType:'Established platform' },
  { id:'re-09', title:'Square Yards', url:'https://www.squareyards.com/', description:'Property discovery, advisory and real estate services across India and international markets.', tags:['Real Estate','India','Property','Investment'], sourceType:'Established platform' },
  { id:'re-10', title:'PropTiger', url:'https://www.proptiger.com/', description:'Residential property discovery and advisory platform for buyers and investors.', tags:['Real Estate','India','Property','Investment'], sourceType:'Established platform' },
  { id:'re-11', title:'CREDAI', url:'https://www.credai.org/', description:'Apex association of private real estate developers in India with industry policy, research and member networks.', tags:['Real Estate','India','Industry Body','Developers'], contactEmail:'info@credai.org', contactPhone:'+91 11 43126262', sourceType:'Industry body' },
  { id:'re-12', title:'JLL India', url:'https://www.jll.com/en-in/', description:'Commercial real estate services, property, investment, leasing and market research.', tags:['Real Estate','India','Commercial','Research'], contactPhone:'+91 124 460 5000', sourceType:'Established platform' },
  { id:'re-13', title:'CBRE India', url:'https://www.cbre.co.in/', description:'Commercial real estate advisory, property services, investment and market intelligence.', tags:['Real Estate','India','Commercial','Research'], sourceType:'Established platform' },
  { id:'re-14', title:'Knight Frank India', url:'https://www.knightfrank.co.in/', description:'Residential and commercial property services with research, investment and occupier advisory.', tags:['Real Estate','India','Commercial','Research'], sourceType:'Established platform' },
  { id:'re-15', title:'Colliers India', url:'https://www.colliers.com/en-in', description:'Commercial real estate, investment, valuation and research platform with India market intelligence.', tags:['Real Estate','India','Commercial','Research'], sourceType:'Established platform' },
  { id:'re-16', title:'ANAROCK', url:'https://www.anarock.com/', description:'Indian real estate services, advisory, research and property solutions.', tags:['Real Estate','India','Commercial','Research'], sourceType:'Established platform' },

  // FRANCHISE
  { id:'fr-01', title:'Franchise India', url:'https://www.franchiseindia.com/', description:'Major Indian franchise and business opportunity marketplace covering brands, investment ranges and expansion.', tags:['Franchise','India','Business','Marketplace'], contactPhone:'+91 9717683838', contactEmail:'feedback@franchiseindia.in', sourceType:'Established platform' },
  { id:'fr-02', title:'FranchiseBazar', url:'https://www.franchisebazar.com/', description:'Large Indian franchise and business opportunity directory covering franchises, dealerships and distributorships.', tags:['Franchise','India','Business','Marketplace'], contactPhone:'+91 9844443200', sourceType:'Established platform' },
  { id:'fr-03', title:'Franchise Mart', url:'https://www.franchisemart.in/', description:'Indian franchise opportunity platform for franchisors, franchisees and business buyers.', tags:['Franchise','India','Business','Marketplace'], contactPhone:'+91 9909960054', sourceType:'Established platform' },
  { id:'fr-04', title:'Franchise Gateway', url:'https://www.franchisegateway.iid.org.in/', description:'Franchise platform connecting brands and investors with structured opportunity and advisory information.', tags:['Franchise','India','Business','Marketplace'], sourceType:'Established platform' },
  { id:'fr-05', title:'International Franchise Association', url:'https://www.franchise.org/', description:'Major global franchise association with franchise education, research, resources and industry networking.', tags:['Franchise','Global','Industry Body','Research'], sourceType:'Industry body' },
  { id:'fr-06', title:'Quality Franchise Association India', url:'https://india.franchise-association.org/', description:'Franchise association focused on ethical franchising, member directory, guidance and education.', tags:['Franchise','India','Industry Body','Standards'], contactPhone:'+44 1323 315 048', sourceType:'Industry body' },
  { id:'fr-07', title:'Franchise Direct', url:'https://www.franchisedirect.com/', description:'International franchise opportunity and information marketplace operating across multiple regions.', tags:['Franchise','Global','Marketplace'], sourceType:'Established platform' },
  { id:'fr-08', title:'Franchise Gator', url:'https://www.franchisegator.com/', description:'Franchise discovery marketplace with investment and category-based opportunity search.', tags:['Franchise','Global','Marketplace'], sourceType:'Established platform' },
  { id:'fr-09', title:'Entrepreneur Franchise', url:'https://www.entrepreneur.com/franchises', description:'Franchise directory and business education from Entrepreneur.', tags:['Franchise','Global','Business','Research'], sourceType:'Established platform' },

  // JOBS
  { id:'job-01', title:'National Career Service', url:'https://www.ncs.gov.in/', description:'Government of India employment platform for jobseekers, employers, internships, counselling and career services.', tags:['Jobs','India','Government','Internships'], contactPhone:'1514', sourceType:'Government' },
  { id:'job-02', title:'Apprenticeship India', url:'https://www.apprenticeshipindia.gov.in/', description:'Government apprenticeship ecosystem connecting candidates and establishments for apprenticeship opportunities.', tags:['Jobs','India','Government','Internships'], sourceType:'Government' },
  { id:'job-03', title:'LinkedIn Jobs', url:'https://www.linkedin.com/jobs/', description:'Professional job and internship marketplace with employer, skill, location and remote filters.', tags:['Jobs','Global','Internships','Remote'], sourceType:'Established platform' },
  { id:'job-04', title:'Indeed India', url:'https://in.indeed.com/', description:'Large job search platform covering India and international roles.', tags:['Jobs','India','Global','Remote'], sourceType:'Established platform' },
  { id:'job-05', title:'Wellfound Jobs', url:'https://wellfound.com/jobs', description:'Startup hiring marketplace with remote and local startup roles.', tags:['Jobs','Global','Startups','Remote'], sourceType:'Established platform' },
  { id:'job-06', title:'Naukri', url:'https://www.naukri.com/', description:'Major Indian recruitment and job search platform for freshers and experienced professionals.', tags:['Jobs','India','Recruitment'], sourceType:'Established platform' },
  { id:'job-07', title:'Foundit', url:'https://www.foundit.in/', description:'India-focused career and recruitment platform for jobs and talent discovery.', tags:['Jobs','India','Recruitment'], sourceType:'Established platform' },
  { id:'job-08', title:'Internshala', url:'https://internshala.com/', description:'India-focused internship and fresher opportunity platform.', tags:['Jobs','India','Internships','Freshers'], sourceType:'Established platform' },
  { id:'job-09', title:'Cutshort', url:'https://cutshort.io/', description:'Technology and startup hiring platform for professional roles.', tags:['Jobs','India','Technology','Startups'], sourceType:'Established platform' },
  { id:'job-10', title:'Instahyre', url:'https://www.instahyre.com/', description:'Recruitment marketplace focused on technology and professional hiring.', tags:['Jobs','India','Technology','Recruitment'], sourceType:'Established platform' },
  { id:'job-11', title:'Hirist', url:'https://www.hirist.tech/', description:'Technology jobs and hiring platform for software and digital roles.', tags:['Jobs','India','Technology'], sourceType:'Established platform' },
  { id:'job-12', title:'Freshersworld', url:'https://www.freshersworld.com/', description:'India-focused fresher jobs, entry-level opportunities and recruitment resources.', tags:['Jobs','India','Freshers','Entry Level'], sourceType:'Established platform' },

  // IMPORT / EXPORT
  { id:'trade-01', title:'DGFT', url:'https://www.dgft.gov.in/', description:'Official Directorate General of Foreign Trade portal for IEC, trade policy, authorisations and exporter services.', tags:['Import/Export','India','Government','Export','Import'], sourceType:'Government' },
  { id:'trade-02', title:'ICEGATE', url:'https://www.icegate.gov.in/', description:'Indian Customs national trade portal for customs filing, registration, refunds and trade services.', tags:['Import/Export','India','Government','Customs'], contactPhone:'1800-3010-1000', sourceType:'Government' },
  { id:'trade-03', title:'Indian Trade Portal', url:'https://indiantradeportal.in/', description:'Trade information hub with HS codes, tariffs, export-import policy conditions, statistics, alerts and buyer opportunities.', tags:['Import/Export','India','Trade Data','Export'], sourceType:'Industry body' },
  { id:'trade-04', title:'FIEO', url:'https://fieo.org/en/', description:'Apex body of government-recognised export promotion councils and commodity boards supporting Indian exporters.', tags:['Import/Export','India','Industry Body','Export'], contactPhone:'1800-121-9000', sourceType:'Industry body' },
  { id:'trade-05', title:'APEDA', url:'https://apeda.gov.in/', description:'Official export promotion authority for agricultural and processed food products, including exporter registration and directories.', tags:['Import/Export','India','Government','Export'], sourceType:'Government' },
  { id:'trade-06', title:'MPEDA', url:'https://mpeda.gov.in/', description:'Statutory authority for marine product exports with exporter registration, directory and market services.', tags:['Import/Export','India','Government','Export'], contactEmail:'ho@mpeda.gov.in', contactPhone:'+91 484 2311901', sourceType:'Government' },
  { id:'trade-07', title:'EEPC India', url:'https://www.eepcindia.org/', description:'Government-recognised export promotion council supporting engineering exporters, market access and trade promotion.', tags:['Import/Export','India','Industry Body','Engineering'], sourceType:'Industry body' },
  { id:'trade-08', title:'PHARMEXCIL', url:'https://pharmexcil.com/', description:'Export promotion council for Indian pharmaceuticals with trade enquiries, regulatory resources and export support.', tags:['Import/Export','India','Industry Body','Pharma'], contactEmail:'info@pharmexcil.com', sourceType:'Industry body' },
  { id:'trade-09', title:'CHEMEXCIL', url:'https://www.chemexcil.in/', description:'Ministry of Commerce-supported export promotion council for chemicals, cosmetics, dyes and related products.', tags:['Import/Export','India','Industry Body','Chemicals'], contactEmail:'info@chemexcil.in', contactPhone:'+91 22 69821200', sourceType:'Industry body' },
  { id:'trade-10', title:'EPCH', url:'https://epch.in/', description:'Export Promotion Council for Handicrafts with exporter support, trade fairs and international market information.', tags:['Import/Export','India','Industry Body','Handicrafts'], sourceType:'Industry body' },
  { id:'trade-11', title:'TEXPROCIL', url:'https://www.texprocil.org/', description:'Export promotion council for cotton textiles with buyer-seller meets, market intelligence and exporter support.', tags:['Import/Export','India','Industry Body','Textiles'], contactEmail:'info@texprocil.org', contactPhone:'+91 22 49444000', sourceType:'Industry body' },
  { id:'trade-12', title:'GJEPC', url:'https://www.gjepc.org/', description:'Gem and Jewellery Export Promotion Council supporting exporters, trade events, market information and industry access.', tags:['Import/Export','India','Industry Body','Jewellery'], sourceType:'Industry body' },
  { id:'trade-13', title:'Trade Connect ePlatform', url:'https://www.trade.gov.in/', description:'DGFT trade platform connecting exporters with trade information, opportunities and international market resources.', tags:['Import/Export','India','Government','Trade Data'], sourceType:'Government' },
  { id:'trade-14', title:'Indian Business Portal', url:'https://www.indianbusinessportal.in/', description:'B2B outreach platform connected with the Indian trade ecosystem for exporters and buyers.', tags:['Import/Export','India','B2B','Export'], sourceType:'Industry body' },
  { id:'trade-15', title:'Export Promotion Councils Directory', url:'https://www.commerce.gov.in/', description:'Department of Commerce gateway for India trade policy, export promotion ecosystem and government trade information.', tags:['Import/Export','India','Government','Export'], sourceType:'Government' },
];

export const businessDirectoryResources: BusinessDirectoryResource[] = seed.map((item) => ({ ...item, isFavorite: false, visitCount: 0 }));
