import type { CurrentAICategory } from './current-ai-directory';

export const currentAIAdditions: CurrentAICategory[] = [
  {
    id: 'frontier-aug-2026',
    name: 'Frontier Models & New Releases',
    description: 'Current frontier models and major AI releases verified against official August 2026 announcements.',
    tools: [
      { name: 'GPT-5.6 Sol', url: 'https://openai.com/index/gpt-5-6/', summary: 'OpenAI flagship model for complex reasoning, coding, knowledge work, cybersecurity, science and computer use.', tags: ['frontier', 'openai', 'reasoning', 'coding'], featured: true },
      { name: 'GPT-5.6 Terra', url: 'https://developers.openai.com/api/docs/models', summary: 'Balanced GPT-5.6 option for strong capability with a lower cost profile.', tags: ['frontier', 'openai', 'balanced'] },
      { name: 'GPT-5.6 Luna', url: 'https://developers.openai.com/api/docs/models', summary: 'Fast, cost-efficient GPT-5.6 option for high-volume workloads.', tags: ['frontier', 'openai', 'fast'] },
      { name: 'GPT-5.6 Ultrafast', url: 'https://openai.com/index/previewing-ultrafast/', summary: 'High-speed GPT-5.6 Sol service tier preview for latency-sensitive API workloads.', tags: ['frontier', 'openai', 'speed', 'api'], featured: true },
      { name: 'GPT-Live-1', url: 'https://openai.com/index/introducing-gpt-live/', summary: 'OpenAI voice-native model family powering more natural, full-duplex ChatGPT voice interactions.', tags: ['voice', 'openai', 'realtime'], featured: true },
      { name: 'Claude Opus 5', url: 'https://www.anthropic.com/news/claude-opus-5', summary: 'Anthropic frontier model for demanding coding, knowledge work and long-running agentic tasks.', tags: ['frontier', 'anthropic', 'coding'], featured: true },
      { name: 'Claude Sonnet 5', url: 'https://www.anthropic.com/news/claude-sonnet-5', summary: 'Anthropic’s highly agentic Sonnet model for coding, tool use, knowledge work and everyday production tasks.', tags: ['frontier', 'anthropic', 'agents', 'coding'], featured: true },
      { name: 'Gemini 3.7 Flash', url: 'https://blog.google/innovation-and-ai/models-and-research/gemini-models/introducing-gemini-3-7-flash/', summary: 'Google’s latest workhorse Gemini model focused on coding, agents and fast production workflows.', tags: ['frontier', 'google', 'agents', 'coding'], featured: true },
      { name: 'Grok 4.6', url: 'https://x.ai/news/grok-4-6', summary: 'xAI flagship focused on long-running agents, interactive work, visual tasks and complex coding.', tags: ['frontier', 'xai', 'agents'], featured: true },
      { name: 'Grok Bot', url: 'https://x.ai/news/grok-bot-more-plans', summary: 'Always-on AI teammates that can operate tools and apps and complete delegated jobs end to end.', tags: ['agents', 'automation', 'xai'], featured: true },
      { name: 'Grok Build', url: 'https://x.ai/news/grok-build-for-everyone', summary: 'Prompt-to-app builder for creating and publishing working apps, games, websites and dashboards.', tags: ['app-builder', 'xai', 'agents'], featured: true },
      { name: 'Grok Imagine Video 1.5', url: 'https://x.ai/news', summary: 'Current xAI video generation release supporting text, image and voice references.', tags: ['video', 'creative', 'xai'] },
    ],
  },
  {
    id: 'current-assistants-research',
    name: 'Current Assistants & Research',
    description: 'Current assistants and research products for knowledge work, discovery, documents and advanced technical tasks.',
    tools: [
      { name: 'Claude', url: 'https://claude.ai/', summary: 'General-purpose assistant for writing, analysis, coding and long-form knowledge work.', tags: ['assistant', 'research', 'coding'], featured: true },
      { name: 'Perplexity', url: 'https://www.perplexity.ai/', summary: 'Research-focused answer engine for web discovery, source-backed synthesis and current information.', tags: ['research', 'search', 'sources'], featured: true },
      { name: 'Kimi', url: 'https://www.kimi.com/', summary: 'General AI assistant for research, documents, presentations, spreadsheets and complex tasks.', tags: ['assistant', 'research', 'documents'] },
      { name: 'Google AI Studio', url: 'https://aistudio.google.com/', summary: 'Interactive environment for prototyping and testing AI applications.', tags: ['developer', 'prototyping', 'ai-apps'], featured: true },
      { name: 'NotebookLM', url: 'https://notebooklm.google.com/', summary: 'Source-grounded research and study workspace for working with supplied documents.', tags: ['research', 'documents', 'study'] },
    ],
  },
  {
    id: 'agent-engineering',
    name: 'Agent Engineering & Production',
    description: 'Production-oriented agent frameworks, coding agents, evaluation and infrastructure.',
    tools: [
      { name: 'GitHub Copilot Coding Agent', url: 'https://github.com/features/copilot', summary: 'Delegated coding agent for issues, code changes, tests, reviews and pull requests.', tags: ['coding', 'agent', 'github'], featured: true },
      { name: 'GitHub Copilot CLI', url: 'https://github.com/features/copilot/cli', summary: 'Terminal-native coding agent for planning, editing, testing and reviewing repositories.', tags: ['coding', 'cli', 'agent'], featured: true },
      { name: 'NVIDIA NIM', url: 'https://www.nvidia.com/en-in/ai-data-science/products/nim-microservices/', summary: 'Optimized inference microservices for deploying AI models on accelerated infrastructure.', tags: ['infrastructure', 'inference', 'self-hosted'], featured: true },
      { name: 'NVIDIA NIM Operator', url: 'https://docs.nvidia.com/nim-operator/latest/', summary: 'Kubernetes operator for managing NVIDIA NIM inference microservices and lifecycle operations.', tags: ['infrastructure', 'kubernetes', 'inference'] },
      { name: 'Arize Phoenix', url: 'https://phoenix.arize.com/', summary: 'Open observability and evaluation platform for LLM and agent applications.', tags: ['evals', 'observability', 'agents'] },
      { name: 'Langfuse', url: 'https://langfuse.com/', summary: 'Open tracing, evaluation and prompt observability for production AI systems.', tags: ['evals', 'observability', 'production'] },
    ],
  },
  {
    id: 'gtm-automation',
    name: 'GTM, Sales & Lead Automation',
    description: 'Current GTM platforms for prospect research, enrichment, sequencing and agentic revenue workflows.',
    tools: [
      { name: 'Apollo', url: 'https://www.apollo.io/', summary: 'AI-native GTM platform for prospecting, enrichment, engagement, sequencing and agentic sales workflows.', tags: ['gtm', 'sales', 'lead-generation', 'automation'], featured: true },
      { name: 'Clay', url: 'https://www.clay.com/', summary: 'GTM data and workflow platform for enrichment, signals, research and automated outbound operations.', tags: ['gtm', 'enrichment', 'automation'], featured: true },
      { name: 'Clay Account Agents', url: 'https://www.clay.com/blog/account-agents-workflows', summary: 'Account agents for research and context inside automated GTM workflows.', tags: ['gtm', 'agents', 'account-research', 'automation'], featured: true },
      { name: 'HubSpot Breeze', url: 'https://www.hubspot.com/products/artificial-intelligence', summary: 'AI agents and workflow assistance across marketing, sales, service and CRM operations.', tags: ['gtm', 'crm', 'agents'] },
      { name: 'Common Room RoomieAI', url: 'https://www.commonroom.io/product/ai/', summary: 'GTM agents for signal discovery, pipeline plays and personalized outbound.', tags: ['gtm', 'signals', 'sales', 'agents'], featured: true },
      { name: 'Common Room MCP', url: 'https://www.commonroom.io/product/mcp-server/', summary: 'MCP access to buyer intelligence for research, prospect lists and outreach workflows.', tags: ['gtm', 'mcp', 'buyer-intelligence'] },
      { name: 'Runable', url: 'https://runable.ai/', summary: 'AI agent platform focused on automated workflows and growth execution.', tags: ['agents', 'gtm', 'growth', 'automation'], featured: true },
    ],
  },
  {
    id: 'creative-current',
    name: 'Creative, Design & Media',
    description: 'Current creative platforms for image, video, design, presentation and media workflows.',
    tools: [
      { name: 'Canva', url: 'https://www.canva.com/ai/', summary: 'AI-assisted design and content creation for presentations, graphics, documents and social media.', tags: ['creative', 'design', 'presentations'] },
      { name: 'Adobe Firefly', url: 'https://www.adobe.com/products/firefly.html', summary: 'Generative creative tools integrated with Adobe workflows for images, video and design.', tags: ['creative', 'image', 'video'], featured: true },
      { name: 'Runway', url: 'https://runwayml.com/', summary: 'Generative video and creative production platform for visual storytelling and editing.', tags: ['creative', 'video', 'media'] },
      { name: 'Figma AI', url: 'https://www.figma.com/ai/', summary: 'AI-assisted design and prototyping workflows inside Figma.', tags: ['creative', 'design', 'prototyping'] },
      { name: 'ElevenLabs', url: 'https://elevenlabs.io/', summary: 'Voice, speech, dubbing and audio production platform for expressive media workflows.', tags: ['creative', 'voice', 'audio'] },
    ],
  },
  {
    id: 'agent-security',
    name: 'AI Security & Agent Safety',
    description: 'Security guidance, evaluation and infrastructure controls for AI and agentic systems.',
    tools: [
      { name: 'OWASP GenAI Security Project', url: 'https://genai.owasp.org/', summary: 'Security guidance, risks and community resources for generative AI and agentic applications.', tags: ['security', 'owasp', 'agents'], featured: true },
      { name: 'Microsoft Security Copilot', url: 'https://www.microsoft.com/en-us/security/business/ai-machine-learning/microsoft-security-copilot', summary: 'Security-focused AI assistance for investigation, threat analysis and defensive operations.', tags: ['security', 'soc', 'defensive-ai'] },
      { name: 'Arize Phoenix', url: 'https://phoenix.arize.com/', summary: 'Trace, evaluate and inspect AI and agent behavior for quality and safety signals.', tags: ['security', 'evals', 'observability'] },
      { name: 'Langfuse', url: 'https://langfuse.com/', summary: 'Open observability and evaluation for production AI applications.', tags: ['security', 'evals', 'observability'] },
    ],
  },
  {
    id: 'infrastructure-current',
    name: 'AI Infrastructure & Serving',
    description: 'Current infrastructure platforms for model serving, inference, cloud deployment and scalable AI workloads.',
    tools: [
      { name: 'NVIDIA NIM', url: 'https://www.nvidia.com/en-in/ai-data-science/products/nim-microservices/', summary: 'Production inference microservices for accelerated AI serving.', tags: ['inference', 'gpu', 'production'] },
      { name: 'AWS Bedrock', url: 'https://aws.amazon.com/bedrock/', summary: 'Managed foundation-model platform for building and operating production generative AI applications.', tags: ['cloud', 'infrastructure', 'enterprise'] },
      { name: 'Google Vertex AI', url: 'https://cloud.google.com/vertex-ai', summary: 'Google Cloud platform for building, evaluating, deploying and governing AI applications.', tags: ['cloud', 'infrastructure', 'enterprise'] },
      { name: 'Microsoft Foundry', url: 'https://ai.azure.com/', summary: 'Microsoft environment for building, evaluating and governing enterprise AI applications and agents.', tags: ['cloud', 'agents', 'enterprise'] },
    ],
  },
];
