import type { LucideIcon } from 'lucide-react';
import {
  Type,
  MousePointerClick,
  Headphones,
  Mic,
  BookOpen,
  UserCheck,
  FlaskConical,
  MessageSquare,
  FileText,
  ClipboardList,
  GraduationCap,
  BriefcaseBusiness,
  Languages,
  School,
  Home,
  Palette,
  Bug,
  Users,
  Share2,
  Youtube,
  Instagram,
  BrainCircuit,
  Paintbrush,
  Book,
  Bot,
  CircleDollarSign,
  TrendingUp,
  Landmark,
  Shield,
  Printer,
  Package,
  Laptop,
  Camera,
  Store,
  Wifi,
  Tag,
  PenTool,
  Wallet,
  Clock,
} from 'lucide-react';

export type Opportunity = {
  title: string;
  description: string;
  link: string;
  image: string;
  aiHint: string;
};

export type EarningCategory = {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  opportunities: Opportunity[];
};

const placeholderOpportunities = (count: number, hint: string) => Array.from({ length: count }, (_, i) => ({
  title: `${hint.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')} Site ${i + 1}`,
  description: `Explore opportunities on platform #${i + 1}`,
  link: '#',
  image: `https://picsum.photos/600/40${i}`,
  aiHint: hint,
}));

export const earningOpportunities: EarningCategory[] = [
    {
        id: 'recently-watched',
        name: 'Recently Watched',
        icon: Clock,
        description: "Opportunities you've recently viewed.",
        opportunities: placeholderOpportunities(3, 'history clock'),
    },
    {
        id: 'captcha-entry',
        name: 'Captcha Entry',
        icon: MousePointerClick,
        description: "Earn by solving captchas.",
        opportunities: placeholderOpportunities(3, 'captcha security'),
    },
    {
        id: 'data-entry',
        name: 'Data Entry',
        icon: Type,
        description: "Jobs involving entering data into systems.",
        opportunities: placeholderOpportunities(3, 'data spreadsheet'),
    },
    {
        id: 'transcription',
        name: 'Transcription',
        icon: Headphones,
        description: "Convert audio to text.",
        opportunities: placeholderOpportunities(3, 'audio transcription'),
    },
    {
        id: 'microtasks',
        name: 'Copy Pasting / Microtasks',
        icon: ClipboardList,
        description: "Complete small, simple online tasks.",
        opportunities: placeholderOpportunities(2, 'task list'),
    },
    {
        id: 'virtual-assistant',
        name: 'Virtual Assistant',
        icon: UserCheck,
        description: "Provide remote administrative support.",
        opportunities: placeholderOpportunities(2, 'virtual assistant'),
    },
    {
        id: 'online-surveys',
        name: 'Online Surveys',
        icon: MessageSquare,
        description: "Share your opinion for rewards.",
        opportunities: placeholderOpportunities(3, 'survey form'),
    },
    {
        id: 'product-testing',
        name: 'Product Testing',
        icon: FlaskConical,
        description: "Test new products and give feedback.",
        opportunities: placeholderOpportunities(2, 'product testing'),
    },
    {
        id: 'writing-reviews',
        name: 'Writing Product Reviews',
        icon: PenTool,
        description: "Get paid to write reviews.",
        opportunities: placeholderOpportunities(2, 'writing review'),
    },
    {
        id: 'app-testing',
        name: 'App Testing',
        icon: Laptop,
        description: "Test mobile and web apps.",
        opportunities: placeholderOpportunities(2, 'app testing'),
    },
    {
        id: 'usability-testing',
        name: 'Feedback & Usability Testing',
        icon: Users,
        description: "Test websites and apps for user-friendliness.",
        opportunities: placeholderOpportunities(2, 'user feedback'),
    },
    {
        id: 'content-writing',
        name: 'Content Writing',
        icon: FileText,
        description: "Write articles, blog posts, and more.",
        opportunities: placeholderOpportunities(2, 'content writing'),
    },
    {
        id: 'copywriting',
        name: 'Copywriting',
        icon: BookOpen,
        description: "Write compelling marketing copy.",
        opportunities: placeholderOpportunities(2, 'copywriting book'),
    },
    {
        id: 'proofreading-editing',
        name: 'Proofreading & Editing',
        icon: GraduationCap,
        description: "Correct grammar and style in texts.",
        opportunities: placeholderOpportunities(2, 'editing document'),
    },
    {
        id: 'resume-writing',
        name: 'Resume Writing',
        icon: BriefcaseBusiness,
        description: "Help people create professional resumes.",
        opportunities: placeholderOpportunities(2, 'resume document'),
    },
    {
        id: 'translation',
        name: 'Translation',
        icon: Languages,
        description: "Translate documents and audio.",
        opportunities: placeholderOpportunities(2, 'language translation'),
    },
    {
        id: 'online-tutoring',
        name: 'Online Tutoring',
        icon: School,
        description: "Tutor students in various subjects.",
        opportunities: placeholderOpportunities(2, 'online tutoring'),
    },
    {
        id: 'homework-help',
        name: 'Homework Help',
        icon: Home,
        description: "Assist students with their homework.",
        opportunities: placeholderOpportunities(2, 'student homework'),
    },
    {
        id: 'ui-ux-design',
        name: 'UI/UX Design',
        icon: Palette,
        description: "Design user interfaces and experiences.",
        opportunities: placeholderOpportunities(2, 'design prototype'),
    },
    {
        id: 'bug-bounty',
        name: 'Bug Bounty Hunting',
        icon: Bug,
        description: "Find and report software bugs.",
        opportunities: placeholderOpportunities(2, 'hacker code'),
    },
    {
        id: 'social-media',
        name: 'Social Media Management',
        icon: Share2,
        description: "Manage social media accounts for businesses.",
        opportunities: placeholderOpportunities(2, 'social media'),
    },
    {
        id: 'affiliate-marketing',
        name: 'Affiliate Marketing',
        icon: Tag,
        description: "Promote products and earn commissions.",
        opportunities: placeholderOpportunities(2, 'affiliate chart'),
    },
    {
        id: 'youtube',
        name: 'YouTube Content Creation',
        icon: Youtube,
        description: "Create and monetize YouTube videos.",
        opportunities: placeholderOpportunities(2, 'youtube creator'),
    },
    {
        id: 'instagram-marketing',
        name: 'Instagram Marketing',
        icon: Instagram,
        description: "Market products and services on Instagram.",
        opportunities: placeholderOpportunities(2, 'instagram phone'),
    },
    {
        id: 'ai-prompts',
        name: 'Creating & Selling AI Prompts',
        icon: BrainCircuit,
        description: "Craft and sell prompts for AI models.",
        opportunities: placeholderOpportunities(2, 'ai brain'),
    },
    {
        id: 'ai-art',
        name: 'Selling AI-Generated Art',
        icon: Paintbrush,
        description: "Create and sell art made with AI.",
        opportunities: placeholderOpportunities(2, 'ai art'),
    },
    {
        id: 'ai-voiceover',
        name: 'AI Voiceover Work',
        icon: Mic,
        description: "Use AI for voiceover projects.",
        opportunities: placeholderOpportunities(2, 'voiceover microphone'),
    },
    {
        id: 'ai-ebooks',
        name: 'Selling AI-Generated Ebooks',
        icon: Book,
        description: "Write and sell ebooks with AI assistance.",
        opportunities: placeholderOpportunities(2, 'ebook library'),
    },
    {
        id: 'ai-chat-dev',
        name: 'AI Based Chat Development',
        icon: Bot,
        description: "Develop chatbots using AI.",
        opportunities: placeholderOpportunities(2, 'chatbot robot'),
    },
    {
        id: 'crypto-staking',
        name: 'Cryptocurrency Staking',
        icon: CircleDollarSign,
        description: "Earn rewards by staking crypto.",
        opportunities: placeholderOpportunities(2, 'crypto coin'),
    },
    {
        id: 'stock-trading',
        name: 'Stock Market Trading',
        icon: TrendingUp,
        description: "Trade stocks on the financial markets.",
        opportunities: placeholderOpportunities(2, 'stock chart'),
    },
    {
        id: 'nft-trading',
        name: 'NFT Trading',
        icon: Landmark,
        description: "Buy and sell Non-Fungible Tokens.",
        opportunities: placeholderOpportunities(2, 'nft art'),
    },
    {
        id: 'forex-trading',
        name: 'Forex Trading',
        icon: Wallet,
        description: "Trade currencies on the foreign exchange market.",
        opportunities: placeholderOpportunities(2, 'forex graph'),
    },
    {
        id: 'airdrops',
        name: 'Participating in Airdrops',
        icon: Shield,
        description: "Receive free tokens from new crypto projects.",
        opportunities: placeholderOpportunities(2, 'crypto airdrop'),
    },
    {
        id: 'print-on-demand',
        name: 'Print-on-Demand Stores',
        icon: Printer,
        description: "Sell custom designs on products.",
        opportunities: placeholderOpportunities(2, 'tshirt design'),
    },
    {
        id: 'dropshipping',
        name: 'Dropshipping',
        icon: Package,
        description: "Sell products without holding inventory.",
        opportunities: placeholderOpportunities(2, 'shipping box'),
    },
    {
        id: 'digital-products',
        name: 'Selling Digital Products',
        icon: Laptop,
        description: "Sell your own digital creations.",
        opportunities: placeholderOpportunities(2, 'digital download'),
    },
    {
        id: 'sell-photos',
        name: 'Selling Photos & Videos',
        icon: Camera,
        description: "Monetize your photography and videography.",
        opportunities: placeholderOpportunities(2, 'camera lens'),
    },
    {
        id: 'mystery-shopping',
        name: 'Online Mystery Shopping',
        icon: Store,
        description: "Evaluate online businesses anonymously.",
        opportunities: placeholderOpportunities(2, 'online shopping'),
    },
    {
        id: 'rent-digital-space',
        name: 'Renting Out Digital Space',
        icon: Wifi,
        description: "Share your internet bandwidth for cash.",
        opportunities: placeholderOpportunities(2, 'internet router'),
    },
    {
        id: 'data-annotation',
        name: 'Data Annotation',
        icon: Tag,
        description: "Label data to train AI models.",
        opportunities: placeholderOpportunities(2, 'data label'),
    },
];
