import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';
import { cookies } from 'next/headers';
import { AUTH_COOKIE, verifySession } from '@/lib/auth';
export type ProjectStatus='idea'|'planning'|'in-progress'|'blocked'|'testing'|'completed'|'archived'; export type ProjectPriority='P0'|'P1'|'P2'|'P3';
export type Project={id:string;name:string;description:string;people:string[];organization:string;role:string;priority:ProjectPriority;status:ProjectStatus;progress:number;startDate?:string;targetDate?:string;phase:string;techStack:string[];repository?:string;liveUrl?:string;nextAction:string;blockers:string[];notes:string[];createdAt:string;updatedAt:string;archivedAt?:string};
const file=path.join(process.cwd(),'src/data/projects/projects.json'); const configured=()=>Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY));
async function legacy():Promise<Project[]>{const parsed=JSON.parse(await fs.readFile(file,'utf8'));if(!Array.isArray(parsed))throw new Error('Project store is invalid');return parsed}
async function owner(){const token=(await cookies()).get(AUTH_COOKIE)?.value;if(!verifySession(token))throw new Error('Unauthorized');const username=process.env.AUTH_USERNAME||'';if(!username)throw new Error('Auth is not configured');const h=crypto.createHash('sha256').update(`streamearn-owner:${username}`).digest('hex').slice(0,32).split('');h[12]='5';h[16]=((parseInt(h[16],16)&3)|8).toString(16);return `${h.slice(0,8).join('')}-${h.slice(8,12).join('')}-${h.slice(12,16).join('')}-${h.slice(16,20).join('')}-${h.slice(20,32).join('')}`}
function fromRow(r:any):Project{return {id:r.id,name:r.name,description:r.description||'',people:Array.isArray(r.people)?r.people:[],organization:r.organization||'',role:r.role||'',priority:r.priority,status:r.status,progress:r.progress,startDate:r.start_date||undefined,targetDate:r.target_date||undefined,phase:r.phase||'',techStack:Array.isArray(r.tech_stack)?r.tech_stack:[],repository:r.repository||undefined,liveUrl:r.live_url||undefined,nextAction:r.next_action||'',blockers:Array.isArray(r.blockers)?r.blockers:[],notes:Array.isArray(r.notes)?r.notes:[],createdAt:r.created_at,updatedAt:r.updated_at,archivedAt:r.archived_at||undefined}}
function row(p:Project,id:string){return {id:p.id,owner_id:id,name:p.name,description:p.description,organization:p.organization,role:p.role,priority:p.priority,status:p.status,progress:p.progress,start_date:p.startDate||null,target_date:p.targetDate||null,phase:p.phase,tech_stack:p.techStack,repository:p.repository||'',live_url:p.liveUrl||'',next_action:p.nextAction,blockers:p.blockers,notes:p.notes,created_at:p.createdAt,updated_at:p.updatedAt,archived_at:p.archivedAt||null}}
export async function listProjects(){if(!configured())return legacy();const sb=createSupabaseAdminClient();const {data,error}=await sb.from('projects').select('*').eq('owner_id',await owner()).order('updated_at',{ascending:false});if(error)throw error;return(data||[]).map(fromRow)}
export async function addProject(p:Project){if(!configured()){const old=await legacy();if(old.some(x=>x.id===p.id))throw new Error('Project already exists');const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,`${JSON.stringify([...old,p],null,2)}\n`);await fs.rename(tmp,file);return p}const sb=createSupabaseAdminClient();const {data,error}=await sb.from('projects').insert(row(p,await owner())).select('*').single();if(error)throw error;return fromRow(data)}
export async function archiveProject(id:string){if(!configured()){const old=await legacy();const now=new Date().toISOString();const next=old.map(p=>p.id===id?{...p,status:'archived' as const,archivedAt:now,updatedAt:now}:p);if(next.every((p,i)=>p===old[i]))throw new Error('Project not found');const tmp=`${file}.${process.pid}.tmp`;await fs.writeFile(tmp,`${JSON.stringify(next,null,2)}\n`);await fs.rename(tmp,file);return}const sb=createSupabaseAdminClient();const {error}=await sb.from('projects').update({status:'archived'}).eq('id',id).eq('owner_id',await owner());if(error)throw error}
