export type ResourceLink = { id: string; title: string; url: string; description?: string; tags: string[]; isFavorite: boolean; visitCount: number };

const sourceLinks: Omit<ResourceLink, 'isFavorite' | 'visitCount'>[] = [
  { id: '1', title: 'Google AI Essentials', url: 'https://grow.google/intl/en_in/ai-essentials/', description: 'Core AI concepts from Google.', tags: ['Monday', 'AI', 'Core Concepts', 'Google'] },
  { id: '2', title: 'IBM AI Foundations for Everyone', url: 'https://www.coursera.org/specializations/ai-foundations-for-everyone', description: 'A specialization covering AI foundations.', tags: ['Monday', 'AI', 'Core Concepts', 'IBM', 'Coursera'] },
  { id: '3', title: 'Coursera AI For Everyone', url: 'https://www.coursera.org/learn/ai-for-everyone', description: 'A foundational AI course.', tags: ['Monday', 'AI', 'Core Concepts', 'Coursera'] },
  { id: '4', title: 'Microsoft AI For Beginners', url: 'https://microsoft.github.io/AI-For-Beginners/', description: 'A structured curriculum for AI foundations.', tags: ['Monday', 'AI', 'Core Concepts', 'Microsoft'] },
  { id: '5', title: 'Microsoft AI Learning Hub', url: 'https://learn.microsoft.com/en-us/ai/?tabs=developer', description: 'AI learning resources and documentation.', tags: ['Monday', 'AI', 'Core Concepts', 'Microsoft'] },
  { id: '6', title: 'Google AI Education', url: 'https://ai.google/education/', description: 'AI learning resources from Google.', tags: ['Monday', 'AI', 'Core Concepts', 'Google'] },
  { id: '7', title: 'Class Central AI Courses', url: 'https://www.classcentral.com/subject/ai', description: 'AI courses from multiple providers.', tags: ['Monday', 'AI', 'Learning'] },
  { id: '8', title: 'Microsoft Generative AI Training', url: 'https://learn.microsoft.com/en-us/training/modules/fundamentals-generative-ai/', description: 'Training on generative AI fundamentals.', tags: ['Monday', 'AI', 'Generative AI', 'Microsoft'] },
  { id: '9', title: 'DeepLearning.AI Short Courses', url: 'https://www.deeplearning.ai/courses/', description: 'Short practical courses for modern AI development.', tags: ['Monday', 'AI', 'Learning'] },
  { id: '10', title: 'Hugging Face Learn', url: 'https://huggingface.co/learn', description: 'Practical learning for open AI tooling and applications.', tags: ['Monday', 'AI', 'Developer'] },
  { id: '11', title: 'Fast.ai', url: 'https://course.fast.ai/', description: 'Practical deep learning education.', tags: ['Monday', 'AI', 'Developer'] },
  { id: '12', title: 'Full Stack Deep Learning', url: 'https://fullstackdeeplearning.com/', description: 'End-to-end AI application development education.', tags: ['Monday', 'AI', 'Developer'] },
  { id: '13', title: 'Microsoft Learn', url: 'https://learn.microsoft.com/', description: 'Technical learning and documentation across cloud and developer technologies.', tags: ['Tuesday', 'Developer', 'Cloud'] },
  { id: '14', title: 'freeCodeCamp', url: 'https://www.freecodecamp.org/', description: 'Free programming and developer education.', tags: ['Tuesday', 'Developer', 'Coding'] },
  { id: '15', title: 'The Odin Project', url: 'https://www.theodinproject.com/', description: 'Open web-development curriculum.', tags: ['Tuesday', 'Developer', 'Coding'] },
  { id: '16', title: 'roadmap.sh', url: 'https://roadmap.sh/', description: 'Developer roadmaps for software and infrastructure skills.', tags: ['Tuesday', 'Developer', 'Roadmaps'] },
  { id: '17', title: 'MDN Web Docs', url: 'https://developer.mozilla.org/', description: 'Authoritative web development documentation.', tags: ['Tuesday', 'Developer', 'Web'] },
  { id: '18', title: 'GitHub Skills', url: 'https://skills.github.com/', description: 'Hands-on GitHub and software-development learning.', tags: ['Tuesday', 'Developer', 'GitHub'] },
  { id: '19', title: 'OWASP', url: 'https://owasp.org/', description: 'Open security standards, projects and learning resources.', tags: ['Cybersecurity', 'Security', 'OWASP'] },
  { id: '20', title: 'PortSwigger Web Security Academy', url: 'https://portswigger.net/web-security', description: 'Hands-on web application security training.', tags: ['Cybersecurity', 'Web Security', 'Practice'] },
  { id: '21', title: 'TryHackMe', url: 'https://tryhackme.com/', description: 'Guided cybersecurity labs and learning paths.', tags: ['Cybersecurity', 'Practice', 'Labs'] },
  { id: '22', title: 'Hack The Box Academy', url: 'https://academy.hackthebox.com/', description: 'Structured cybersecurity training and labs.', tags: ['Cybersecurity', 'Practice', 'Labs'] },
  { id: '23', title: 'picoCTF', url: 'https://picoctf.org/', description: 'Capture-the-flag security challenges and practice.', tags: ['Cybersecurity', 'CTF', 'Practice'] },
  { id: '24', title: 'OverTheWire', url: 'https://overthewire.org/wargames/', description: 'Security learning through command-line games.', tags: ['Cybersecurity', 'Linux', 'Practice'] },
  { id: '25', title: 'SANS Reading Room', url: 'https://www.sans.org/white-papers/', description: 'Security research and technical papers.', tags: ['Cybersecurity', 'Research'] },
  { id: '26', title: 'NIST Cybersecurity Resources', url: 'https://www.nist.gov/cybersecurity', description: 'Cybersecurity frameworks, guidance and standards.', tags: ['Cybersecurity', 'Standards'] },
  { id: '27', title: 'CISA Cybersecurity Resources', url: 'https://www.cisa.gov/topics/cybersecurity-best-practices', description: 'Public cybersecurity guidance and best practices.', tags: ['Cybersecurity', 'Security'] },
  { id: '28', title: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', description: 'Practical data science and AI learning.', tags: ['Data', 'AI', 'Learning'] },
  { id: '29', title: 'Google Cloud Skills Boost', url: 'https://www.cloudskillsboost.google/', description: 'Hands-on cloud and data learning.', tags: ['Cloud', 'Learning'] },
  { id: '30', title: 'AWS Skill Builder', url: 'https://skillbuilder.aws/', description: 'AWS learning and hands-on cloud training.', tags: ['Cloud', 'Learning'] },
  { id: '31', title: 'Microsoft Azure Learning', url: 'https://learn.microsoft.com/en-us/training/azure/', description: 'Azure training and cloud skill paths.', tags: ['Cloud', 'Learning'] },
  { id: '32', title: 'LinkedIn Learning', url: 'https://www.linkedin.com/learning/', description: 'Professional skills and technology courses.', tags: ['Careers', 'Learning'] },
  { id: '33', title: 'Coursera', url: 'https://www.coursera.org/', description: 'Professional and academic courses from universities and companies.', tags: ['Careers', 'Learning'] },
  { id: '34', title: 'edX', url: 'https://www.edx.org/', description: 'University and professional online education.', tags: ['Careers', 'Learning'] },
  { id: '35', title: 'Udemy', url: 'https://www.udemy.com/', description: 'Large marketplace of technical and professional courses.', tags: ['Careers', 'Learning'] },
  { id: '36', title: 'Internshala', url: 'https://internshala.com/', description: 'Internships, fresher roles and career learning in India.', tags: ['Careers', 'Internships', 'India'] },
  { id: '37', title: 'Wellfound', url: 'https://wellfound.com/jobs', description: 'Startup jobs and technology roles.', tags: ['Careers', 'Jobs', 'Startups'] },
  { id: '38', title: 'LinkedIn Jobs', url: 'https://www.linkedin.com/jobs/', description: 'Professional jobs and internship discovery.', tags: ['Careers', 'Jobs'] },
  { id: '39', title: 'Indeed', url: 'https://www.indeed.com/', description: 'Large job search platform.', tags: ['Careers', 'Jobs'] },
  { id: '40', title: 'Naukri', url: 'https://www.naukri.com/', description: 'Indian job search and recruitment platform.', tags: ['Careers', 'Jobs', 'India'] },
  { id: '41', title: 'Foundit', url: 'https://www.foundit.in/', description: 'Jobs, internships and career opportunities in India.', tags: ['Careers', 'Jobs', 'India'] },
  { id: '42', title: 'GitHub Jobs & Careers', url: 'https://github.com/careers', description: 'Technology career opportunities at GitHub.', tags: ['Careers', 'Technology'] },
  { id: '43', title: 'Google Careers', url: 'https://www.google.com/about/careers/applications/jobs/results/', description: 'Technology and business roles at Google.', tags: ['Careers', 'Technology'] },
  { id: '44', title: 'Microsoft Careers', url: 'https://jobs.careers.microsoft.com/', description: 'Technology and business opportunities at Microsoft.', tags: ['Careers', 'Technology'] },
  { id: '45', title: 'Amazon Jobs', url: 'https://www.amazon.jobs/', description: 'Technology, operations and corporate opportunities.', tags: ['Careers', 'Technology'] },
  { id: '46', title: 'TCS Careers', url: 'https://www.tcs.com/careers', description: 'Technology careers and graduate opportunities.', tags: ['Careers', 'India'] },
  { id: '47', title: 'Infosys Careers', url: 'https://www.infosys.com/careers.html', description: 'Technology and graduate career opportunities.', tags: ['Careers', 'India'] },
  { id: '48', title: 'Wipro Careers', url: 'https://careers.wipro.com/', description: 'Technology and professional opportunities.', tags: ['Careers', 'India'] },
  { id: '49', title: 'Accenture Careers', url: 'https://www.accenture.com/in-en/careers', description: 'Technology, consulting and digital roles.', tags: ['Careers', 'India'] },
  { id: '50', title: 'Deloitte Careers', url: 'https://www.deloitte.com/global/en/careers.html', description: 'Technology, consulting, risk and business careers.', tags: ['Careers'] },
  { id: '51', title: 'Figma Community', url: 'https://www.figma.com/community', description: 'Design resources, templates and community projects.', tags: ['Platforms', 'Design'] },
  { id: '52', title: 'Canva Design School', url: 'https://www.canva.com/designschool/', description: 'Design learning and creative resources.', tags: ['Platforms', 'Design'] },
  { id: '53', title: 'Product Hunt', url: 'https://www.producthunt.com/', description: 'Discover new technology products and tools.', tags: ['Platforms', 'Discovery'] },
  { id: '54', title: 'AlternativeTo', url: 'https://alternativeto.net/', description: 'Find alternatives to software and online services.', tags: ['Platforms', 'Discovery'] },
  { id: '55', title: 'G2', url: 'https://www.g2.com/', description: 'Software discovery, reviews and comparisons.', tags: ['Platforms', 'Reviews'] },
  { id: '56', title: 'Capterra', url: 'https://www.capterra.com/', description: 'Software discovery and category comparisons.', tags: ['Platforms', 'Reviews'] },
  { id: '57', title: '99acres', url: 'https://www.99acres.com/', description: 'Indian property listings and real-estate discovery.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '58', title: 'Housing.com', url: 'https://housing.com/', description: 'Property discovery, listings and market information.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '59', title: 'MagicBricks', url: 'https://www.magicbricks.com/', description: 'Indian property listings and real-estate resources.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '60', title: 'NoBroker', url: 'https://www.nobroker.in/', description: 'Property rental and buying platform.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '61', title: 'Square Yards', url: 'https://www.squareyards.com/', description: 'Real-estate listings, advisory and property services.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '62', title: 'JLL India', url: 'https://www.jll.co.in/', description: 'Commercial real-estate services and advisory.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '63', title: 'CBRE India', url: 'https://www.cbre.co.in/', description: 'Commercial real-estate services and advisory.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '64', title: 'Godrej Properties', url: 'https://www.godrejproperties.com/', description: 'Residential and commercial real-estate developer.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '65', title: 'Prestige Group', url: 'https://www.prestigegroup.in/', description: 'Residential, commercial and hospitality developer.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '66', title: 'DLF', url: 'https://www.dlf.in/', description: 'Integrated real-estate development and infrastructure.', tags: ['Business', 'Real Estate', 'India'] },
  { id: '67', title: 'GitHub', url: 'https://github.com/', description: 'Code hosting, collaboration and developer ecosystem.', tags: ['Platforms', 'Developer'] },
  { id: '68', title: 'Vercel', url: 'https://vercel.com/', description: 'Frontend deployment and application infrastructure.', tags: ['Platforms', 'Developer'] },
  { id: '69', title: 'Render', url: 'https://render.com/', description: 'Cloud hosting for web services and applications.', tags: ['Platforms', 'Developer'] },
  { id: '70', title: 'Firebase', url: 'https://firebase.google.com/', description: 'Application backend, authentication and cloud services.', tags: ['Platforms', 'Developer'] },
  { id: '71', title: 'Supabase', url: 'https://supabase.com/', description: 'Open-source backend platform with database and authentication.', tags: ['Platforms', 'Developer'] },
  { id: '72', title: 'MongoDB Atlas', url: 'https://www.mongodb.com/atlas', description: 'Managed cloud database platform.', tags: ['Platforms', 'Developer'] },
  { id: '73', title: 'Postman', url: 'https://www.postman.com/', description: 'API development, testing and collaboration.', tags: ['Platforms', 'Developer'] },
  { id: '74', title: 'Docker', url: 'https://www.docker.com/', description: 'Container development and deployment platform.', tags: ['Platforms', 'Developer'] },
  { id: '75', title: 'Cloudflare', url: 'https://www.cloudflare.com/', description: 'Web security, networking and edge infrastructure.', tags: ['Platforms', 'Developer', 'Security'] },
  { id: '76', title: 'Notion', url: 'https://www.notion.com/', description: 'Workspace for notes, projects, knowledge and collaboration.', tags: ['Platforms', 'Productivity'] },
  { id: '77', title: 'Trello', url: 'https://trello.com/', description: 'Visual project and task management.', tags: ['Platforms', 'Productivity'] },
  { id: '78', title: 'Slack', url: 'https://slack.com/', description: 'Team communication and workflow collaboration.', tags: ['Platforms', 'Productivity'] },
  { id: '79', title: 'Google Workspace', url: 'https://workspace.google.com/', description: 'Cloud productivity and collaboration suite.', tags: ['Platforms', 'Productivity'] },
  { id: '80', title: 'Microsoft 365', url: 'https://www.microsoft.com/microsoft-365', description: 'Productivity and collaboration suite.', tags: ['Platforms', 'Productivity'] },
  { id: '81', title: 'Zapier', url: 'https://zapier.com/', description: 'Workflow automation across online services.', tags: ['Platforms', 'Automation'] },
  { id: '82', title: 'n8n', url: 'https://n8n.io/', description: 'Self-hostable workflow automation platform.', tags: ['Platforms', 'Automation'] },
  { id: '83', title: 'Make', url: 'https://www.make.com/', description: 'Visual workflow automation platform.', tags: ['Platforms', 'Automation'] },
  { id: '84', title: 'Coursera Career Academy', url: 'https://www.coursera.org/career-academy', description: 'Career-focused learning pathways.', tags: ['Careers', 'Learning'] },
  { id: '85', title: 'MIT OpenCourseWare', url: 'https://ocw.mit.edu/', description: 'Free course materials from MIT.', tags: ['Learning', 'Academic'] },
  { id: '86', title: 'Stanford Online', url: 'https://online.stanford.edu/', description: 'Online learning from Stanford.', tags: ['Learning', 'Academic'] },
  { id: '87', title: 'Harvard Online', url: 'https://pll.harvard.edu/', description: 'Professional and academic online learning.', tags: ['Learning', 'Academic'] },
  { id: '88', title: 'Google Career Certificates', url: 'https://grow.google/certificates/', description: 'Career-focused technology certificates.', tags: ['Careers', 'Learning'] },
  { id: '89', title: 'AWS Educate', url: 'https://aws.amazon.com/education/awseducate/', description: 'Cloud education resources and learning paths.', tags: ['Learning', 'Cloud'] },
  { id: '90', title: 'Cisco Networking Academy', url: 'https://www.netacad.com/', description: 'Networking and cybersecurity education.', tags: ['Cybersecurity', 'Networking', 'Learning'] },
  { id: '91', title: 'ISC2', url: 'https://www.isc2.org/', description: 'Cybersecurity professional education and resources.', tags: ['Cybersecurity', 'Careers'] },
  { id: '92', title: 'CompTIA', url: 'https://www.comptia.org/', description: 'IT and cybersecurity certification resources.', tags: ['Cybersecurity', 'Careers'] },
  { id: '93', title: 'HackerOne', url: 'https://www.hackerone.com/', description: 'Bug bounty and vulnerability disclosure platform.', tags: ['Cybersecurity', 'Careers'] },
  { id: '94', title: 'Bugcrowd', url: 'https://www.bugcrowd.com/', description: 'Crowdsourced security testing and bug bounty platform.', tags: ['Cybersecurity', 'Careers'] },
  { id: '95', title: 'AngelList Talent', url: 'https://wellfound.com/', description: 'Startup hiring and technology career discovery.', tags: ['Careers', 'Startups'] },
  { id: '96', title: 'Remote OK', url: 'https://remoteok.com/', description: 'Remote technology and startup jobs.', tags: ['Careers', 'Remote'] },
  { id: '97', title: 'We Work Remotely', url: 'https://weworkremotely.com/', description: 'Remote job discovery across industries.', tags: ['Careers', 'Remote'] },
  { id: '98', title: 'FlexJobs', url: 'https://www.flexjobs.com/', description: 'Remote and flexible job listings.', tags: ['Careers', 'Remote'] },
  { id: '99', title: 'Upwork', url: 'https://www.upwork.com/', description: 'Freelance work and professional services marketplace.', tags: ['Careers', 'Freelancing'] },
  { id: '100', title: 'Fiverr', url: 'https://www.fiverr.com/', description: 'Freelance services marketplace.', tags: ['Careers', 'Freelancing'] }
];

export const initialLinks: ResourceLink[] = sourceLinks.map(link => ({ ...link, isFavorite: false, visitCount: 0 }));
