const visible = (el) => { const r = el.getBoundingClientRect(); const s = getComputedStyle(el); return r.width > 0 && r.height > 0 && s.display !== 'none' && s.visibility !== 'hidden'; };
const describe = (el) => ({ tag: el.tagName.toLowerCase(), type: el instanceof HTMLInputElement ? el.type : undefined, name: el.getAttribute('name') || '', id: el.id || '', label: el.getAttribute('aria-label') || '', placeholder: el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement ? el.placeholder : '', text: el instanceof HTMLButtonElement ? el.innerText.trim().slice(0, 200) : '', value: el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement ? el.value : '', options: el instanceof HTMLSelectElement ? [...el.options].map(o => ({ text: o.text, value: o.value })) : undefined, checked: el instanceof HTMLInputElement ? el.checked : undefined });
function findField(target) { const wanted = String(target?.name || target?.id || target?.label || target?.placeholder || '').toLowerCase(); if (!wanted) return null; const c = [...document.querySelectorAll('input, textarea, select')].filter(visible); return c.find(el => [el.name, el.id, el.getAttribute('aria-label'), el.getAttribute('placeholder')].filter(Boolean).some(v => String(v).toLowerCase() === wanted)) || c.find(el => [el.name, el.id, el.getAttribute('aria-label'), el.getAttribute('placeholder')].filter(Boolean).some(v => String(v).toLowerCase().includes(wanted))); }
function setValue(el, value) { if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) { const proto = el instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(proto, 'value')?.set?.call(el, String(value)); } else if (el instanceof HTMLSelectElement) el.value = String(value); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); }
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message?.type === 'STREAM_EARN_EXTRACT_PAGE') { const text = document.body?.innerText?.slice(0, 50000) || ''; const links = [...document.querySelectorAll('a[href]')].slice(0, 200).map(a => ({ title: (a.textContent || '').trim().slice(0, 200), url: a.href })).filter(x => x.title || x.url); const fields = [...document.querySelectorAll('input, textarea, select, button')].filter(visible).slice(0, 300).map(describe); sendResponse({ ok: true, page: { title: document.title, url: location.href, text, links, fields } }); return true; }
  if (message?.type === 'STREAM_EARN_FILL_FORM') { const changes = []; for (const item of Array.isArray(message.fields) ? message.fields : []) { const el = findField(item); if (!el) { changes.push({ target: item, ok: false, error: 'Field not found' }); continue; } if (el instanceof HTMLInputElement && ['submit','button','image'].includes(el.type)) { changes.push({ target: item, ok: false, error: 'Submit control cannot be filled' }); continue; } if (el instanceof HTMLInputElement && ['checkbox','radio'].includes(el.type)) { el.checked = Boolean(item.value); el.dispatchEvent(new Event('change', { bubbles: true })); } else setValue(el, item.value); changes.push({ target: item, ok: true }); } sendResponse({ ok: true, changes }); return true; }
  if (message?.type === 'STREAM_EARN_CLICK') { const wanted = String(message.text || '').trim().toLowerCase(); const candidates = [...document.querySelectorAll('button, a, input[type="button"], input[type="submit"]')].filter(visible); const el = candidates.find(x => (x.textContent || (x instanceof HTMLInputElement ? x.value : '')).trim().toLowerCase() === wanted); if (!el) { sendResponse({ ok: false, error: 'Button not found' }); return true; } el.click(); sendResponse({ ok: true }); return true; }
});
