const visible = (el) => { const r = el.getBoundingClientRect(); const s = getComputedStyle(el); return r.width > 0 && r.height > 0 && s.display !== 'none' && s.visibility !== 'hidden'; };
const labelText = (el) => { const id = el.id; const explicit = id ? document.querySelector(`label[for="${CSS.escape(id)}"]`)?.innerText : ''; const parent = el.closest('label')?.innerText; return String(el.getAttribute('aria-label') || explicit || parent || '').trim().slice(0, 300); };
const describe = (el, index) => ({ index, tag: el.tagName.toLowerCase(), type: el instanceof HTMLInputElement ? el.type : undefined, name: el.getAttribute('name') || '', id: el.id || '', label: labelText(el), placeholder: el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement ? el.placeholder : '', text: el instanceof HTMLButtonElement ? el.innerText.trim().slice(0, 200) : '', value: el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement ? el.value : '', options: el instanceof HTMLSelectElement ? [...el.options].map(o => ({ text: o.text, value: o.value })) : undefined, checked: el instanceof HTMLInputElement ? el.checked : undefined });
const controls = () => [...document.querySelectorAll('input, textarea, select, button')].filter(visible);
function findField(target) { const wanted = String(target?.name || target?.id || target?.label || target?.placeholder || target?.index || '').toLowerCase(); const c = controls(); if (target?.index != null && c[Number(target.index)]) return c[Number(target.index)]; if (!wanted) return null; return c.find(el => [el.name, el.id, el.getAttribute('aria-label'), el.getAttribute('placeholder'), labelText(el)].filter(Boolean).some(v => String(v).toLowerCase() === wanted)) || c.find(el => [el.name, el.id, el.getAttribute('aria-label'), el.getAttribute('placeholder'), labelText(el)].filter(Boolean).some(v => String(v).toLowerCase().includes(wanted))); }
function setNativeValue(el, value) { if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) { const proto = el instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(proto, 'value')?.set?.call(el, String(value)); } else if (el instanceof HTMLSelectElement) el.value = String(value); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); }
function findClickable(target) { const wanted = String(target?.text || target?.label || target?.index || '').trim().toLowerCase(); const c = [...document.querySelectorAll('button, a, input[type="button"], input[type="submit"], [role="button"]')].filter(visible); if (target?.index != null && c[Number(target.index)]) return c[Number(target.index)]; return c.find(x => String(x.textContent || (x instanceof HTMLInputElement ? x.value : '') || x.getAttribute('aria-label') || '').trim().toLowerCase() === wanted) || c.find(x => String(x.textContent || (x instanceof HTMLInputElement ? x.value : '') || x.getAttribute('aria-label') || '').trim().toLowerCase().includes(wanted)); }
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message?.type === 'STREAM_EARN_EXTRACT_PAGE') { const text = document.body?.innerText?.slice(0, 80000) || ''; const links = [...document.querySelectorAll('a[href]')].slice(0, 300).map(a => ({ title: (a.textContent || '').trim().slice(0, 200), url: a.href })).filter(x => x.title || x.url); const fields = controls().slice(0, 500).map(describe); sendResponse({ ok: true, page: { title: document.title, url: location.href, text, links, fields } }); return true; }
  if (message?.type === 'STREAM_EARN_FILL_FORM') { const changes = []; for (const item of Array.isArray(message.fields) ? message.fields : []) { const el = findField(item); if (!el) { changes.push({ target: item, ok: false, error: 'Field not found' }); continue; } if (el instanceof HTMLInputElement && ['submit','button','image'].includes(el.type)) { changes.push({ target: item, ok: false, error: 'Submit control cannot be filled' }); continue; } if (el instanceof HTMLInputElement && ['checkbox','radio'].includes(el.type)) { el.checked = Boolean(item.value); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); } else setNativeValue(el, item.value); changes.push({ target: item, ok: true, observedValue: el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement || el instanceof HTMLSelectElement ? el.value : undefined }); } sendResponse({ ok: true, changes }); return true; }
  if (message?.type === 'STREAM_EARN_CLICK') { const el = findClickable(message); if (!el) { sendResponse({ ok: false, error: 'Clickable control not found' }); return true; } el.scrollIntoView({ behavior: 'instant', block: 'center' }); el.click(); sendResponse({ ok: true, text: (el.textContent || '').trim().slice(0, 200) }); return true; }
});
window.addEventListener('message', event => { if (event.source !== window || event.origin !== window.location.origin) return; const message = event.data; if (!message || message.source !== 'streamearn-web' || !message.requestId) return; chrome.runtime.sendMessage(message.payload, response => { window.postMessage({ source: 'streamearn-extension', requestId: message.requestId, response: response || { ok: false, error: 'No extension response' } }, window.location.origin); }); });
