import { NextRequest, NextResponse } from 'next/server';
import crypto from 'node:crypto';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { rejectCrossOrigin } from '@/lib/security';
export const runtime='nodejs';
const categories=['ai_news','internships','scholarships','earnings'] as const;
function clean(v:unknown,max:number){return typeof v==='string'?v.trim().slice(0,max):''}
export async function GET(request:NextRequest){const category=new URL(request.url).searchParams.get('category');if(category&&!categories.includes(category as any))return NextResponse.json({error:'Invalid category'},{status:400});try{const sb=await createSupabaseServerClient();let q=sb.from('scheduler_items').select('*').is('archived_at',null).order('created_at',{ascending:false}).limit(100);if(category)q=q.eq('category',category);const {data,error}=await q;if(error)throw error;return NextResponse.json(data||[],{headers:{'Cache-Control':'public, max-age=60, stale-while-revalidate=300'}})}catch{return NextResponse.json({error:'Unable to load scheduler items'},{status:500})}}
export async function POST(request:NextRequest){const blocked=rejectCrossOrigin(request);if(blocked)return blocked;try{const body=await request.json();const category=clean(body?.category,30) as typeof categories[number];if(!categories.includes(category))return NextResponse.json({error:'Invalid category'},{status:400});const title=clean(body?.title,500);const url=clean(body?.url,2000);if(!title||!/^https?:\/\//i.test(url))return NextResponse.json({error:'Invalid item'},{status:400});const description=clean(body?.description,10000);const source=clean(body?.source,300);const publishedAt=body?.publishedAt?new Date(body.publishedAt).toISOString():null;const contentHash=crypto.createHash('sha256').update(JSON.stringify({category,title,description,url,publishedAt})).digest('hex');const sb=await createSupabaseServerClient();const {data,error}=await sb.from('scheduler_items').insert({category,title,description,source,url,published_at:publishedAt,content_hash:contentHash}).select('*').single();if(error?.code==='23505')return NextResponse.json({ok:true,duplicate:true},{status:200});if(error)throw error;return NextResponse.json(data,{status:201,headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({error:'Unable to append scheduler item'},{status:500})}}
