'use client';

import { useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { CalendarClock, ExternalLink, GraduationCap, Globe2, MapPin, Search, Sparkles, BriefcaseBusiness, CheckCircle2 } from 'lucide-react';
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { Header } from '@/components/header';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

export const dynamic = 'force-dynamic';

const opportunities = [
  { id:'outreachy-dec-2026', type:'Internship', status:'Closing soon', title:'Outreachy — December 2026 Cohort', org:'Outreachy', area:'Open Source • Software • Security • Research', location:'Global', mode:'Remote • Paid', deadline:'31 Aug 2026', url:'https://www.outreachy.org/apply/', image:'outreachy-dec-2026', note:'December 2026 applications are open Aug 24–31. India is in the Northern Hemisphere, so student cohort eligibility depends on having 42 consecutive days free during the May–August cohort rules; verify the official student eligibility before applying.' },
  { id:'drdo-sspl-2026', type:'Internship', status:'Closing soon', title:'DRDO SSPL Paid Internship — 6 Months', org:'DRDO • SSPL', area:'Engineering • Research • Technology', location:'Delhi, India', mode:'Onsite', deadline:'30 Sep 2026', url:'https://www.drdo.gov.in/drdo/offerings/vacancies?page=1', image:'drdo-sspl-2026', note:'Official DRDO vacancy listing shows a paid six-month internship with an application end date of 30 Sep 2026. Check the advertisement for exact branch, year and document requirements.' },
  { id:'panw-early-career', type:'Internship', status:'Open now', title:'Palo Alto Networks Early-in-Career Internships', org:'Palo Alto Networks', area:'Cybersecurity • Unit 42 • Software • Security Research', location:'Global / India roles vary', mode:'Location-specific', url:'https://jobs.paloaltonetworks.com/en/early-in-career', image:'panw-early-career', note:'Global cybersecurity company with a 12-week internship program and India early-career activity. Search current openings because eligibility and location are posting-specific.' },
  { id:'crowdstrike-university', type:'Internship', status:'Open now', title:'CrowdStrike University & Intern Programs', org:'CrowdStrike', area:'Cybersecurity • Software • Data • Security Engineering', location:'Global • Pune, India and other locations', mode:'Location-specific', url:'https://www.crowdstrike.com/en-gb/careers/university-interns/', image:'crowdstrike-university', note:'CrowdStrike states its university program offers paid positions and recruits strongly across cybersecurity, software engineering, computer science and data science, with internship locations including Pune.' },
  { id:'ibm-internships', type:'Internship', status:'Open now', title:'IBM Internship Programs', org:'IBM', area:'Software • AI • Cloud • Security • Data', location:'Global / India', mode:'Location-specific', url:'https://www.ibm.com/careers/internships', image:'ibm-internships', note:'IBM maintains an active internship ecosystem and entry-level programs for enrolled students. Use the official live search for current roles and location eligibility.' },
  { id:'microsoft-global', type:'Internship', status:'Open now', title:'Microsoft Global University Internships', org:'Microsoft', area:'Software • Cybersecurity • Cloud • AI', location:'Global', mode:'Remote / Hybrid / Onsite varies', url:'https://careers.microsoft.com/v2/global/en/students', image:'microsoft-global', note:"Microsoft's official student portal covers university internships across job families. Individual postings determine year, location, work authorization and technical requirements." },
  { id:'microsoft-india', type:'Internship', status:'Open now', title:'Microsoft India Student & Early-Career Search', org:'Microsoft', area:'Software • Security • Data • Cloud', location:'India', mode:'Location-specific', url:'https://careers.microsoft.com/v2/global/en/students?qcountry=India', image:'microsoft-india', note:'Official India student search. The Explore Microsoft program itself is for first/second-year students, so use the broader India search for third-year roles.' },
  { id:'google-students', type:'Internship', status:'Open now', title:'Google Students & Internships', org:'Google', area:'Software • Security • AI • Research', location:'Global', mode:'Location-specific', url:'https://www.google.com/about/careers/applications/students', image:'google-students', note:'Official student portal covering internships and student/research opportunities. Each live posting has its own degree, graduation and location requirements.' },
  { id:'google-india-search', type:'Internship', status:'Open now', title:'Google India Internship Search', org:'Google', area:'Software • AI • Systems • Security', location:'India', mode:'Location-specific', url:'https://www.google.com/about/careers/applications/jobs/results/?location=India&employment_type=INTERN', image:'google-india-search', note:'Live official India internship search. Use current postings rather than relying on expired social-media listings.' },
  { id:'cern-student', type:'Internship', status:'Upcoming', title:'CERN Student Opportunities', org:'CERN', area:'Computer Science • Engineering • Computing • Research', location:'Geneva, Switzerland', mode:'Onsite', url:'https://careers.cern/student-opportunities', image:'cern-student', note:'CERN runs technical student and summer opportunities. Cycle dates and eligibility vary by program, so verify the current opening before applying.' },
  { id:'drdo-internships', type:'Internship', status:'Open now', title:'DRDO Paid Internship Radar', org:'DRDO • Government of India', area:'Engineering • Cyber/IT-adjacent • Defence Research', location:'India', mode:'Onsite / institute-specific', url:'https://drdo.gov.in/drdo/en/search/node?keys=Internship', image:'drdo-internships', note:'DRDO continuously publishes institute-specific paid internship notices. Current 2026–27 listings include engineering/science UG opportunities; each lab advertisement has its own eligibility and deadline.' },
  { id:'palo-alto-india', type:'Internship', status:'Open now', title:'Palo Alto Networks India Early Career', org:'Palo Alto Networks', area:'Cybersecurity • Unit 42 • MDR • Cortex', location:'India', mode:'Onsite / hybrid varies', url:'https://jobs.paloaltonetworks.com/en/india', image:'palo-alto-india', note:'The India careers hub currently highlights early-career and cybersecurity opportunities, including Unit 42 internship activity. Search current India roles for exact eligibility.' },
  { id:'nsp', type:'Scholarship', status:'Open now', title:'National Scholarship Portal — 2026–27', org:'Government of India', area:'Merit • Welfare • Central & State schemes', location:'India', mode:'Online', deadline:'Scheme-specific', url:'https://scholarships.gov.in/All-Scholarships', image:'nsp', note:'The official 2026–27 catalogue is live. Only schemes whose published eligibility fits your current UG status should be treated as matches; OTR is required.' },
  { id:'pm-yasasvi-college', type:'Scholarship', status:'Open now', title:'PM YASASVI Top Class Education in College — OBC/EBC/DNT', org:'Government of India', area:'Undergraduate • Tuition • Living support', location:'India', mode:'Online via NSP', deadline:'31 Oct 2026', url:'https://scholarships.gov.in/All-Scholarships', image:'pm-yasasvi-college', note:'Current NSP 2026–27 listing. Published eligibility includes OBC/EBC/DNT status, notified institutions and parental income not above ₹2.5 lakh. Your stated ₹2 lakh ceiling fits the income criterion, but the institution/course list must be verified.' },
  { id:'tn-bc-postmatric', type:'Scholarship', status:'Open now', title:'Tamil Nadu BC / MBC / DNC Post-Matric Scholarship', org:'Government of Tamil Nadu', area:'Professional UG • Tuition • Exam • Book support', location:'Tamil Nadu', mode:'Institution / state portal', deadline:'Scheme/institution specific', url:'https://www.bcw.tn.gov.in/sub_page/8', image:'tn-bc-postmatric', note:'Current Tamil Nadu guidance covers BC/MBC/DNC college students, including professional courses. Published conditions include income limits and institution/course rules; the current guidance should be checked with SRM/UMIS before applying.' },
  { id:'tn-central-institutions', type:'Scholarship', status:'Open now', title:'Tamil Nadu BC/MBC/DNC Assistance for Central Institutions', org:'Government of Tamil Nadu', area:'UG • IIT/IIM/IIIT/NIT/Central Universities', location:'Tamil Nadu domicile • India', mode:'Institution / state process', deadline:'Scheme/institution specific', url:'https://bcmbcmw.tn.gov.in/welfschemes.htm', image:'tn-central-institutions', note:'Tamil Nadu publishes a separate scholarship route for BC/MBC/DNC students studying in eligible Central Government institutions, with a published ₹2.5 lakh annual income ceiling. SRM is not in the named IIT/IIM/IIIT/NIT/Central University group, so this is shown as a reference, not a confirmed match.' },
  { id:'pm-usp', type:'Scholarship', status:'Open now', title:'PM-USP Central Sector Scholarship — NSP Renewal', org:'Government of India', area:'Merit-based undergraduate support', location:'India', mode:'Online', deadline:'30 Sep 2026', url:'https://scholarships.gov.in/All-Scholarships', image:'pm-usp', note:'The official 2026–27 NSP page currently shows renewal applications open through 30 Sep 2026. It is relevant only if you are an existing eligible awardee/renewal candidate; do not treat it as a new fresh application without checking your prior award status.' },
  { id:'nsp-eligibility', type:'Scholarship', status:'Open now', title:'NSP Scholarship Eligibility & Scheme Finder', org:'Government of India', area:'Eligibility • Scheme discovery • Applications', location:'India', mode:'Online', url:'https://scholarships.gov.in/Students', image:'nsp-eligibility', note:'Official student portal with scheme eligibility, application and OTR functions. Use this as the primary verification layer before applying to any NSP listing.' },
  { id:'india-scholarship-directory', type:'Scholarship', status:'Open now', title:'Tamil Nadu Scholarship & Welfare Scheme Directory', org:'Government of Tamil Nadu', area:'BC • MBC • DNC • Higher Education Assistance', location:'Tamil Nadu', mode:'Online / Institution', url:'https://www.india.gov.in/category/benefits-social-development/subcategory/benefits-grants-subsidies/details/bc-mbc-and-minorities-welfare-scholarship-status', image:'india-scholarship-directory', note:'Government directory for Tamil Nadu BC/MBC/Minorities scholarship services, useful for discovering current state assistance and status routes.' },
];

const tabs = ['All','Internships','Scholarships'];
const statuses = ['All','Closing soon','Open now','Upcoming'];
function imageUrl(seed:string){ return `https://picsum.photos/seed/${encodeURIComponent(`streamearn-${seed}`)}/900/560`; }

export default function OpportunitiesPage(){
  const searchParams = useSearchParams();
  const requestedType = searchParams.get('type');
  const initialTab = requestedType === 'Internships' || requestedType === 'Scholarships' ? requestedType : 'All';
  const [tab,setTab]=useState(initialTab); const [status,setStatus]=useState('All'); const [query,setQuery]=useState(''); const [list,setList]=useState(true);
  const filtered=useMemo(()=>opportunities.filter(o=>(tab==='All'||o.type===tab)&&(status==='All'||o.status.toLowerCase().includes(status.toLowerCase()))&&(`${o.title} ${o.org} ${o.area} ${o.location} ${o.mode}`.toLowerCase().includes(query.toLowerCase()))),[tab,status,query]);
  const internshipCount=opportunities.filter(o=>o.type==='Internship').length;
  const scholarshipCount=opportunities.filter(o=>o.type==='Scholarship').length;
  return <SidebarProvider><UnifiedSidebar/><SidebarInset><Header showSidebarTrigger/><main className="min-h-screen px-4 pb-12 pt-5 sm:px-6 lg:px-8">
    <section className="mx-auto max-w-7xl overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="relative p-5 sm:p-7"><div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_20%_20%,hsl(var(--primary)/.16),transparent_32%),radial-gradient(circle_at_80%_10%,hsl(var(--primary)/.1),transparent_28%)]"/><div className="relative max-w-3xl"><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-primary"><Sparkles className="h-3.5 w-3.5"/>Opportunity Radar</div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Internships & Scholarships</h1><p className="mt-2 text-sm text-muted-foreground">Verified opportunity discovery for a 3rd-year B.Tech CSE Cyber Security student — India, Tamil Nadu, remote and global sources.</p></div><div className="relative mt-5 flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, cybersecurity, AI, research, scholarship..." className="h-10 pl-9"/></div><div className="flex gap-1 rounded-lg border bg-background p-1">{tabs.map(t=><Button key={t} variant={tab===t?'secondary':'ghost'} size="sm" onClick={()=>setTab(t)}>{t}</Button>)}</div><Button variant="outline" size="sm" onClick={()=>setList(v=>!v)}>{list?'Grid':'List'}</Button></div></div></section>
    <section className="mx-auto mt-5 max-w-7xl"><div className="mb-3 flex flex-wrap items-center gap-1.5">{statuses.map(s=><Button key={s} size="sm" variant={status===s?'default':'outline'} className="h-7 px-2.5 text-xs" onClick={()=>setStatus(s)}>{s}</Button>)}<span className="ml-auto text-xs text-muted-foreground">{filtered.length} matched • {internshipCount} internships • {scholarshipCount} scholarships</span></div><div className={list?'space-y-2':'grid gap-3 sm:grid-cols-2 xl:grid-cols-3'}>{filtered.map(o=><article key={o.id} className="group overflow-hidden rounded-xl border bg-card transition hover:border-primary/40 hover:shadow-sm">{list?<div className="flex gap-3 p-3"><img src={imageUrl(o.image)} alt="" className="h-20 w-24 shrink-0 rounded-lg object-cover"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><Badge variant={o.type==='Internship'?'default':'secondary'}>{o.type}</Badge><Badge variant="outline">{o.status}</Badge>{o.deadline&&<Badge variant="outline">Due {o.deadline}</Badge>}</div><h2 className="mt-1 text-sm font-semibold leading-tight">{o.title}</h2><p className="mt-0.5 text-xs text-muted-foreground">{o.org} • {o.area}</p><div className="mt-1.5 flex flex-wrap gap-2 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1"><Globe2 className="h-3 w-3"/>{o.location}</span><span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3"/>{o.mode}</span></div><p className="mt-1.5 line-clamp-2 text-xs text-muted-foreground">{o.note}</p></div><Button asChild size="sm" className="mt-auto h-8 shrink-0"><a href={o.url} target="_blank" rel="noreferrer">Official <ExternalLink className="ml-1 h-3 w-3"/></a></Button></div>:<div><img src={imageUrl(o.image)} alt="" className="h-32 w-full object-cover"/><div className="p-3"><div className="flex flex-wrap gap-1.5"><Badge>{o.type}</Badge><Badge variant="outline">{o.status}</Badge>{o.deadline&&<Badge variant="outline">Due {o.deadline}</Badge>}</div><h2 className="mt-1.5 text-sm font-semibold">{o.title}</h2><p className="mt-1 text-xs text-muted-foreground">{o.org} • {o.location}</p><p className="mt-2 line-clamp-3 text-xs text-muted-foreground">{o.note}</p><Button asChild size="sm" className="mt-3 h-8"><a href={o.url} target="_blank" rel="noreferrer">Open official source <ExternalLink className="ml-1 h-3 w-3"/></a></Button></div></div>}</article>)}</div>{filtered.length===0&&<div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No matching opportunities in the current verified set. Try another search or status.</div>}</section>
    <section className="mx-auto mt-5 grid max-w-7xl gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-card p-4"><BriefcaseBusiness className="h-4 w-4 text-primary"/><h3 className="mt-2 text-sm font-semibold">Internships</h3><p className="mt-1 text-xs text-muted-foreground">{internshipCount} current official portals/programs spanning cybersecurity, software, AI, research and government.</p></div><div className="rounded-xl border bg-card p-4"><GraduationCap className="h-4 w-4 text-primary"/><h3 className="mt-2 text-sm font-semibold">Scholarships</h3><p className="mt-1 text-xs text-muted-foreground">{scholarshipCount} current government and higher-education routes with eligibility notes.</p></div><div className="rounded-xl border bg-card p-4"><CalendarClock className="h-4 w-4 text-primary"/><h3 className="mt-2 text-sm font-semibold">Daily radar</h3><p className="mt-1 text-xs text-muted-foreground">Daily research checks openings, deadlines, eligibility changes and stale listings before updates are committed.</p></div></section>
    <div className="mx-auto mt-4 flex max-w-7xl items-center gap-2 rounded-lg border bg-muted/30 px-3 py-2 text-[11px] text-muted-foreground"><CheckCircle2 className="h-3.5 w-3.5 text-primary"/>Official sources are preferred. A portal is not treated as an individual eligible opening unless its current posting confirms the required year, location and eligibility.</div>
  </main></SidebarInset></SidebarProvider>;
}
