'use client';

import { useMemo, useState } from 'react';
import { CalendarClock, ExternalLink, GraduationCap, Globe2, MapPin, Search, Sparkles, BriefcaseBusiness } from 'lucide-react';
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { Header } from '@/components/header';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';

const opportunities = [
  { id:'microsoft-global', type:'Internship', status:'Open now', title:'Microsoft Global University Internships', org:'Microsoft', area:'Software • Cybersecurity • Cloud • AI', location:'Global', mode:'Remote / Hybrid / Onsite varies', url:'https://careers.microsoft.com/v2/global/en/students', image:'stream-opportunity-microsoft-global-01', note:"Microsoft's global university internship portal covers current Bachelor’s, Master’s, MBA and PhD students across job families and solution areas." },
  { id:'microsoft-india', type:'Internship', status:'Upcoming', title:'Microsoft Early in Profession — India', org:'Microsoft', area:'Software • Security • Data • Cloud', location:'India', mode:'Onsite / hybrid varies', url:'https://careers.microsoft.com/v2/global/en/students?qcountry=India', image:'stream-opportunity-microsoft-india-02', note:'Official India student and early-career portal; openings change continuously.' },
  { id:'google-students', type:'Internship', status:'Open now', title:'Google Students & Internships', org:'Google', area:'Software • Security • AI • Research', location:'Global', mode:'Location-specific', url:'https://www.google.com/about/careers/applications/students', image:'stream-opportunity-google-students-03', note:'Official student portal with internships and student researcher opportunities; each posting has its own eligibility.' },
  { id:'google-india-search', type:'Internship', status:'Open now', title:'Google India University Internship Search', org:'Google', area:'Software • AI • Systems • Security', location:'India', mode:'Location-specific', url:'https://www.google.com/about/careers/applications/jobs/results/?location=India&employment_type=INTERN', image:'stream-opportunity-google-india-04', note:'Use the live official search rather than relying on stale individual postings.' },
  { id:'cern-student', type:'Internship', status:'Upcoming', title:'CERN Student Opportunities', org:'CERN', area:'Computer Science • Engineering • Computing', location:'Geneva, Switzerland', mode:'Onsite', url:'https://careers.cern/student-opportunities', image:'stream-opportunity-cern-05', note:'CERN offers technical internships and summer programmes; cycles and eligibility vary.' },
  { id:'nsp', type:'Scholarship', status:'Open now', title:'National Scholarship Portal — 2026–27', org:'Government of India', area:'Merit • Welfare • Central & State schemes', location:'India', mode:'Online', url:'https://scholarships.gov.in/All-Scholarships', image:'stream-opportunity-nsp-06', note:'Official 2026–27 scholarship catalogue. Check each scheme for current-year eligibility and verification requirements.' },
  { id:'nsp-student', type:'Scholarship', status:'Open now', title:'National Scholarship Portal — Student Portal', org:'Government of India', area:'Scholarship discovery • eligibility • applications', location:'India', mode:'Online', url:'https://scholarships.gov.in/Students', image:'stream-opportunity-nsp-student-07', note:'Official student portal. Academic Year 2026–27 is open and scheme eligibility is published by the portal.' },
  { id:'pm-usp', type:'Scholarship', status:'Open now', title:'PM-USP Central Sector Scholarship — NSP', org:'Government of India', area:'Merit-based undergraduate support', location:'India', mode:'Online', url:'https://scholarships.gov.in/All-Scholarships', image:'stream-opportunity-pmusp-08', note:'Listed on the official NSP 2026–27 catalogue. Verify fresh/renewal and income/merit requirements before applying.' },
  { id:'obc-top-class', type:'Scholarship', status:'Open now', title:'PM YASASVI Top Class Education in College', org:'Government of India', area:'Undergraduate financial support', location:'India', mode:'Online', url:'https://scholarships.gov.in/All-Scholarships', image:'stream-opportunity-yasasvi-09', note:'Current 2026–27 NSP listing. Eligibility is determined by the official scheme rules and institution list.' },
  { id:'scholarship-search', type:'Scholarship', status:'Open now', title:'NSP Scheme & Eligibility Search', org:'Government of India', area:'Search all current schemes', location:'India', mode:'Online', url:'https://scholarships.gov.in/allschemesdomicile', image:'stream-opportunity-nsp-search-10', note:'Use the official scheme search to verify domicile, category, course, year and income conditions.' },
];

const tabs = ['All','Internships','Scholarships'];
const statuses = ['All','Closing soon','Open now','Upcoming'];
function imageUrl(seed:string){ return `https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80&sig=${encodeURIComponent(seed)}`; }

export default function OpportunitiesPage(){
  const [tab,setTab]=useState('All'); const [status,setStatus]=useState('All'); const [query,setQuery]=useState(''); const [list,setList]=useState(true);
  const filtered=useMemo(()=>opportunities.filter(o=>(tab==='All'||o.type===tab)&&(status==='All'||o.status.toLowerCase().includes(status.toLowerCase()))&&(`${o.title} ${o.org} ${o.area} ${o.location}`.toLowerCase().includes(query.toLowerCase()))),[tab,status,query]);
  return <SidebarProvider><UnifiedSidebar/><SidebarInset><Header showSidebarTrigger/><main className="min-h-screen px-4 pb-12 pt-5 sm:px-6 lg:px-8">
    <section className="mx-auto max-w-7xl overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="relative p-5 sm:p-7"><div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_20%_20%,hsl(var(--primary)/.16),transparent_32%),radial-gradient(circle_at_80%_10%,hsl(var(--primary)/.1),transparent_28%)]"/><div className="relative max-w-3xl"><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.16em] text-primary"><Sparkles className="h-3.5 w-3.5"/>Opportunities</div><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Internships & Scholarships</h1><p className="mt-2 text-sm text-muted-foreground">A focused opportunity radar for credible internships and undergraduate scholarships across India and globally.</p></div><div className="relative mt-5 flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search company, cybersecurity, AI, research, scholarship..." className="h-10 pl-9"/></div><div className="flex gap-1 rounded-lg border bg-background p-1">{tabs.map(t=><Button key={t} variant={tab===t?'secondary':'ghost'} size="sm" onClick={()=>setTab(t)}>{t}</Button>)}</div><Button variant="outline" size="sm" onClick={()=>setList(v=>!v)}>{list?'Grid':'List'}</Button></div></div></section>
    <section className="mx-auto mt-5 max-w-7xl"><div className="mb-3 flex flex-wrap items-center gap-1.5">{statuses.map(s=><Button key={s} size="sm" variant={status===s?'default':'outline'} className="h-7 px-2.5 text-xs" onClick={()=>setStatus(s)}>{s}</Button>)}<span className="ml-auto text-xs text-muted-foreground">{filtered.length} matched</span></div><div className={list?'space-y-2':'grid gap-3 sm:grid-cols-2 xl:grid-cols-3'}>{filtered.map(o=><article key={o.id} className="group overflow-hidden rounded-xl border bg-card transition hover:border-primary/40 hover:shadow-sm">{list?<div className="flex gap-3 p-3"><img src={imageUrl(o.image)} alt="" className="h-20 w-24 shrink-0 rounded-lg object-cover"/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><Badge variant={o.type==='Internship'?'default':'secondary'}>{o.type}</Badge><Badge variant="outline">{o.status}</Badge></div><h2 className="mt-1 text-sm font-semibold leading-tight">{o.title}</h2><p className="mt-0.5 text-xs text-muted-foreground">{o.org} • {o.area}</p><div className="mt-1.5 flex flex-wrap gap-2 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-1"><Globe2 className="h-3 w-3"/>{o.location}</span><span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3"/>{o.mode}</span></div><p className="mt-1.5 line-clamp-2 text-xs text-muted-foreground">{o.note}</p></div><Button asChild size="sm" className="mt-auto h-8 shrink-0"><a href={o.url} target="_blank" rel="noreferrer">Official <ExternalLink className="ml-1 h-3 w-3"/></a></Button></div>:<div><img src={imageUrl(o.image)} alt="" className="h-32 w-full object-cover"/><div className="p-3"><div className="flex gap-1.5"><Badge>{o.type}</Badge><Badge variant="outline">{o.status}</Badge></div><h2 className="mt-1.5 text-sm font-semibold">{o.title}</h2><p className="mt-1 text-xs text-muted-foreground">{o.org} • {o.location}</p><p className="mt-2 line-clamp-3 text-xs text-muted-foreground">{o.note}</p><Button asChild size="sm" className="mt-3 h-8"><a href={o.url} target="_blank" rel="noreferrer">Open official source <ExternalLink className="ml-1 h-3 w-3"/></a></Button></div></div>}</article>)}</div>{filtered.length===0&&<div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No matching opportunities in the current verified set. Try another search or status.</div>}</section>
    <section className="mx-auto mt-5 grid max-w-7xl gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-card p-4"><BriefcaseBusiness className="h-4 w-4 text-primary"/><h3 className="mt-2 text-sm font-semibold">Internships</h3><p className="mt-1 text-xs text-muted-foreground">Global, India, remote, research, software, AI and cybersecurity sources.</p></div><div className="rounded-xl border bg-card p-4"><GraduationCap className="h-4 w-4 text-primary"/><h3 className="mt-2 text-sm font-semibold">Scholarships</h3><p className="mt-1 text-xs text-muted-foreground">Current undergraduate scholarship portals and official scheme sources.</p></div><div className="rounded-xl border bg-card p-4"><CalendarClock className="h-4 w-4 text-primary"/><h3 className="mt-2 text-sm font-semibold">Daily radar</h3><p className="mt-1 text-xs text-muted-foreground">The scheduled StreamEarn refresh checks for new openings, deadline changes and stale listings.</p></div></section>
  </main></SidebarInset></SidebarProvider>;
}
