'use client';
import React, { useState, useMemo } from 'react';
import { Header } from '@/components/header';
import { Breadcrumbs } from '@/components/breadcrumbs';
import { Input } from '@/components/ui/input';
import { Search, ExternalLink } from 'lucide-react';
import { coursesData, type Course } from '@/lib/courses-data';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Icon } from '@/components/icons';
import Image from 'next/image';
import placeholderImages from '@/lib/placeholder-images.json' with { type: 'json' };
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { ScrollArea } from '@/components/ui/scroll-area';

function CourseCard({course}:{course:Course}){const image=placeholderImages[course.imageKey as keyof typeof placeholderImages]||placeholderImages.futureAbstract;return <div className="themed-card group overflow-hidden rounded-xl border"><div className="relative aspect-video"><Image src={image.src} alt={course.title} width={image.width} height={image.height} className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" /><div className="absolute right-4 top-4 rounded-full bg-background/80 p-2"><Icon name={course.icon} className="h-5 w-5 text-accent" /></div></div><div className="p-6"><h3 className="mb-2 font-serif text-xl font-bold">{course.title}</h3><p className="mb-4 text-sm text-muted-foreground">{course.description}</p><Button className="btn-main w-full">Start Learning <ExternalLink className="ml-2 h-4 w-4" /></Button></div></div>}

export default function CoursesPage(){const [searchQuery,setSearchQuery]=useState('');const [openCategories,setOpenCategories]=useState<string[]>(coursesData.map(c=>c.id));const filteredCourses=useMemo(()=>!searchQuery?coursesData:coursesData.map(category=>({...category,courses:category.courses.filter(course=>course.title.toLowerCase().includes(searchQuery.toLowerCase())||course.description.toLowerCase().includes(searchQuery.toLowerCase()))})).filter(category=>category.courses.length),[searchQuery]);return <SidebarProvider><UnifiedSidebar /><SidebarInset><Header showSidebarTrigger /><ScrollArea className="h-[calc(100vh-4rem)]"><main><div className="container mx-auto px-4 py-8 md:py-12"><div className="mb-12 text-center"><Breadcrumbs path={[{name:'Courses',href:'/courses'}]} /><h1 className="mt-4 font-serif text-4xl tracking-tight text-accent md:text-5xl">The Ultimate Course Library for AI & Online Earning</h1><p className="mx-auto mt-4 max-w-3xl text-lg text-muted-foreground">Learn practical skills for the digital economy from a single organised library.</p></div><div className="relative mx-auto mb-12 w-full max-w-2xl"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground" /><Input placeholder="Search courses..." className="w-full rounded-full bg-card py-6 pl-12 pr-4 text-lg shadow-lg" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} /></div><Accordion type="multiple" value={openCategories} onValueChange={setOpenCategories} className="w-full space-y-4">{filteredCourses.map(category=><AccordionItem value={category.id} key={category.id} className="border-b-0"><AccordionTrigger className="rounded-lg bg-card px-4 py-3 font-serif text-2xl tracking-tight text-accent hover:no-underline md:text-3xl">{category.name}</AccordionTrigger><AccordionContent className="pt-6"><div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">{category.courses.map(course=><CourseCard key={course.id} course={course} />)}</div></AccordionContent></AccordionItem>)}</Accordion></div></main></ScrollArea></SidebarInset></SidebarProvider>;}
