'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, FileText, ListTodo, Plus, Search, StickyNote, Target, Trash2, Undo2 } from 'lucide-react';
import Link from 'next/link';
import StickyWall from '@/components/planner/sticky-wall';

type Tab='today'|'week'|'calendar'|'tasks'|'notes'|'sticky'|'progress';
type Status='Not started'|'In progress'|'Done'|'Blocked';
type Priority='Low'|'Medium'|'High';
type Task={id:string;title:string;date:string;done:boolean;deleted:boolean;priority:Priority;status:Status;order:number;notes:string};
type Note={id:string;title:string;text:string;date:string;kind:string};
type Store={tasks:Task[];notes:Note[]};
const KEY='streamearn-planner-v7';
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const dateObj=(s:string)=>{const d=new Date(`${s}T12:00:00`);return Number.isNaN(d.getTime())?new Date():d};
const moveDate=(s:string,n:number)=>{const d=dateObj(s);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const safeDate=(v:any)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(dateObj(v).getTime())?v:today();
const fresh=():Store=>({tasks:[],notes:[]});
function sanitize(raw:any):Store{const s=fresh();if(!raw||typeof raw!=='object')return s;if(Array.isArray(raw.tasks))s.tasks=raw.tasks.filter(Boolean).map((x:any,i:number)=>({id:typeof x.id==='string'?x.id:uid(),title:typeof x.title==='string'?x.title.trim():'',date:safeDate(x.date),done:Boolean(x.done),deleted:Boolean(x.deleted),priority:['Low','Medium','High'].includes(x.priority)?x.priority:'Medium',status:['Not started','In progress','Done','Blocked'].includes(x.status)?x.status:'Not started',order:Number.isFinite(x.order)?x.order:i,notes:typeof x.notes==='string'?x.notes:''})).filter((x:any)=>x.title);if(Array.isArray(raw.notes))s.notes=raw.notes.filter(Boolean).map((x:any)=>({id:typeof x.id==='string'?x.id:uid(),title:typeof x.title==='string'?x.title:'Untitled',text:typeof x.text==='string'?x.text:'',date:safeDate(x.date),kind:typeof x.kind==='string'?x.kind:'note'}));return s}
function load():Store{if(typeof window==='undefined')return fresh();try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw)return sanitize(raw);const legacy=JSON.parse(localStorage.getItem('streamearn-planner-v6')||'null');return sanitize(legacy)}catch{return fresh()}}

export default function PlannerV2(){
 const [tab,setTab]=useState<Tab>('today');const [date,setDate]=useState(today());const [store,setStore]=useState<Store>(fresh);const [ready,setReady]=useState(false);const [task,setTask]=useState('');const [query,setQuery]=useState('');const [noteTitle,setNoteTitle]=useState('');const [noteText,setNoteText]=useState('');
 useEffect(()=>{try{setStore(load())}finally{setReady(true)}},[]);useEffect(()=>{if(ready){try{localStorage.setItem(KEY,JSON.stringify(store))}catch{}}},[ready,store]);
 const active=useMemo(()=>store.tasks.filter(t=>!t.deleted).sort((a,b)=>a.order-b.order),[store.tasks]);const archived=store.tasks.filter(t=>t.deleted);const completed=active.filter(t=>t.done).length;const percent=active.length?Math.round(completed/active.length*100):0;const dayTasks=useMemo(()=>active.filter(t=>t.date===date&&t.title.toLowerCase().includes(query.toLowerCase())),[active,date,query]);
 const week=useMemo(()=>Array.from({length:7},(_,i)=>moveDate(date,i)),[date]);const month=useMemo(()=>{const first=dateObj(date);first.setDate(1);const start=first.getDay();const days=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();return Array.from({length:42},(_,i)=>i<start||i>=start+days?null:`${first.getFullYear()}-${String(first.getMonth()+1).padStart(2,'0')}-${String(i-start+1).padStart(2,'0')}`)},[date]);
 const addTask=()=>{const v=task.trim();if(!v)return;const max=active.reduce((m,t)=>Math.max(m,t.order),-1);setStore(s=>({...s,tasks:[...s.tasks,{id:uid(),title:v,date,done:false,deleted:false,priority:'Medium',status:'Not started',order:max+1,notes:''}]}));setTask('')};
 const patchTask=(id:string,p:Partial<Task>)=>setStore(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,...p}:t)}));
 const toggle=(id:string)=>setStore(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,done:!t.done,status:t.done?'In progress':'Done'}:t)}));
 const archive=(id:string)=>patchTask(id,{deleted:true});const restore=(id:string)=>patchTask(id,{deleted:false});
 const move=(id:string,dir:-1|1)=>setStore(s=>{const list=s.tasks.filter(t=>!t.deleted).sort((a,b)=>a.order-b.order);const i=list.findIndex(t=>t.id===id);const j=i+dir;if(i<0||j<0||j>=list.length)return s;const a=list[i],b=list[j];return {...s,tasks:s.tasks.map(t=>t.id===a.id?{...t,order:b.order}:t.id===b.id?{...t,order:a.order}:t)}});
 const addNote=(kind:string)=>{const text=noteText.trim();if(!text)return;setStore(s=>({...s,notes:[{id:uid(),title:noteTitle.trim()||kind,text,date,kind},...s.notes]}));setNoteTitle('');setNoteText('')};
 if(!ready)return <main className="min-h-screen bg-background p-8"><p className="text-sm text-muted-foreground">Loading Planner…</p></main>;
 return <main className="min-h-screen bg-background"><div className="mx-auto max-w-[1440px] px-4 py-5 md:px-7 md:py-7"><header className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><Link href="/" className="text-xs text-muted-foreground hover:text-foreground">← StreamEarn</Link><p className="mt-3 text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">Personal command centre</p><h1 className="text-3xl font-semibold tracking-tight">Planner</h1><p className="mt-1 text-sm text-muted-foreground">Tasks, monthly calendar, notes, status, priority and Sticky Wall — local-first and private.</p></div><div className="flex items-center gap-1 rounded-lg border bg-card p-1"><button className="rounded-md p-2 hover:bg-muted" onClick={()=>setDate(moveDate(date,-1))}><ChevronLeft className="h-4 w-4"/></button><button className="rounded-md px-3 py-2 text-xs font-medium hover:bg-muted" onClick={()=>setDate(today())}>Today</button><button className="rounded-md p-2 hover:bg-muted" onClick={()=>setDate(moveDate(date,1))}><ChevronRight className="h-4 w-4"/></button></div></header>
 <nav className="mb-5 flex gap-1 overflow-x-auto border-b pb-2">{([['today','Today',ClipboardList],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',Check],['notes','Pages & Notes',FileText],['sticky','Sticky Wall',StickyNote],['progress','Progress',Target]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex shrink-0 items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</nav>
 {tab==='today'&&<section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">{date===today()?'Today':dateObj(date).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</h2><p className="text-xs text-muted-foreground">Use the controls on each task to change priority and status.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{dayTasks.filter(t=>!t.done).length} pending</span></div><form className="mb-3 flex gap-2" onSubmit={e=>{e.preventDefault();addTask()}}><input value={task} onChange={e=>setTask(e.target.value)} className="h-9 flex-1 rounded-md border bg-background px-3 text-sm" placeholder="Add a task…"/><button className="rounded-md bg-foreground px-3 text-xs font-semibold text-background"><Plus className="mr-1 inline h-4 w-4"/>Add</button></form><div className="mb-3 flex items-center gap-2"><Search className="h-3.5 w-3.5 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-8 w-full rounded-md border bg-background px-3 text-xs" placeholder="Search tasks…"/></div><div className="space-y-2">{dayTasks.length===0?<p className="py-12 text-center text-sm text-muted-foreground">No tasks for this day.</p>:dayTasks.map(t=><TaskRow key={t.id} task={t} onToggle={()=>toggle(t.id)} onArchive={()=>archive(t.id)} onMoveUp={()=>move(t.id,-1)} onMoveDown={()=>move(t.id,1)} onPriority={p=>patchTask(t.id,{priority:p})} onStatus={s=>patchTask(t.id,{status:s})} onNotes={n=>patchTask(t.id,{notes:n})}/>)}</div></div><aside className="space-y-3"><Stat label="Completion" value={`${percent}%`}/><Stat label="Active tasks" value={String(active.length)}/><Stat label="Pending today" value={String(dayTasks.filter(t=>!t.done).length)}/></aside></section>}
 {tab==='week'&&<section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{week.map(d=><button key={d} onClick={()=>{setDate(d);setTab('today')}} className="min-h-36 rounded-xl border bg-card p-3 text-left hover:bg-muted"><p className="text-xs font-semibold">{dateObj(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[11px] text-muted-foreground">{dateObj(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p><div className="mt-3 space-y-1">{active.filter(t=>t.date===d).slice(0,6).map(t=><div key={t.id} className="truncate text-xs">• {t.title}</div>)}</div></button>)}</section>}
 {tab==='calendar'&&<section className="rounded-xl border bg-card p-4 md:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{dateObj(date).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><p className="text-xs text-muted-foreground">Monthly view · click a date to plan</p></div><div className="flex gap-1"><button className="rounded-md border p-2 hover:bg-muted" onClick={()=>setDate(moveDate(date,-28))}><ChevronLeft className="h-4 w-4"/></button><button className="rounded-md border px-3 py-2 text-xs" onClick={()=>setDate(today())}>Today</button><button className="rounded-md border p-2 hover:bg-muted" onClick={()=>setDate(moveDate(date,28))}><ChevronRight className="h-4 w-4"/></button></div></div><div className="grid grid-cols-7 border-b pb-2 text-center text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map(d=><div key={d} className="truncate px-1">{d}</div>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{month.map((d,i)=>d?<button key={`${d}-${i}`} onClick={()=>{setDate(d);setTab('today')}} className={`min-h-28 rounded-lg border p-2 text-left transition hover:bg-muted ${d===today()?'border-primary bg-primary/5':''}`}><div className="flex items-center justify-between"><span className="text-xs font-semibold">{dateObj(d).getDate()}</span>{active.filter(t=>t.date===d).length>0&&<span className="rounded-full bg-muted px-1.5 py-0.5 text-[9px]">{active.filter(t=>t.date===d).length}</span>}</div><div className="mt-2 space-y-1">{active.filter(t=>t.date===d).slice(0,3).map(t=><div key={t.id} className={`truncate rounded px-1.5 py-1 text-[10px] ${t.done?'bg-muted text-muted-foreground line-through':'bg-background'}`}>{t.title}</div>)}</div></button>:<div key={`empty-${i}`} className="min-h-28 rounded-lg bg-muted/20"/>)}</div></section>}
 {tab==='tasks'&&<section className="grid gap-5"><div className="rounded-xl border bg-card p-4"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">All To-Do</h2><span className="text-xs text-muted-foreground">Drag order with ↑ ↓</span></div><div className="space-y-2">{active.length===0?<p className="py-10 text-sm text-muted-foreground">No tasks yet.</p>:active.map(t=><TaskRow key={t.id} task={t} onToggle={()=>toggle(t.id)} onArchive={()=>archive(t.id)} onMoveUp={()=>move(t.id,-1)} onMoveDown={()=>move(t.id,1)} onPriority={p=>patchTask(t.id,{priority:p})} onStatus={s=>patchTask(t.id,{status:s})} onNotes={n=>patchTask(t.id,{notes:n})}/>)}</div></div>{archived.length>0&&<div className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Archive</h3><div className="mt-2 space-y-2">{archived.map(t=><div key={t.id} className="flex items-center gap-2 text-xs"><span className="flex-1 truncate">{t.title}</span><button className="rounded border px-2 py-1" onClick={()=>restore(t.id)}><Undo2 className="mr-1 inline h-3.5 w-3.5"/>Restore</button></div>)}</div></div>}</section>}
 {tab==='notes'&&<section className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Pages & Notes</h2><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} className="mt-3 h-9 w-full rounded-md border bg-background px-3 text-sm" placeholder="Title"/><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} className="mt-2 min-h-48 w-full rounded-md border bg-background p-3 text-sm" placeholder="Write something…"/><div className="mt-2 flex gap-2"><button onClick={()=>addNote('page')} className="rounded-md bg-foreground px-3 py-2 text-xs text-background">Save Page</button><button onClick={()=>addNote('meeting')} className="rounded-md border px-3 py-2 text-xs">Meeting</button><button onClick={()=>addNote('note')} className="rounded-md border px-3 py-2 text-xs">Quick Note</button></div></div><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Saved</h2><div className="mt-3 space-y-2">{store.notes.length===0?<p className="text-sm text-muted-foreground">Nothing saved yet.</p>:store.notes.map(n=><article key={n.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><strong className="text-sm">{n.title}</strong><span className="text-[10px] uppercase text-muted-foreground">{n.kind}</span></div><p className="mt-1 whitespace-pre-wrap text-xs text-muted-foreground">{n.text}</p></article>)}</div></div></section>}
 {tab==='sticky'&&<StickyWall compact/>}
 {tab==='progress'&&<section className="grid gap-4 sm:grid-cols-3"><Stat label="Tasks" value={String(active.length)}/><Stat label="Completed" value={String(completed)}/><Stat label="Completion" value={`${percent}%`}/></section>}
 </div></main>;
}
function TaskRow({task,onToggle,onArchive,onMoveUp,onMoveDown,onPriority,onStatus,onNotes}:{task:Task;onToggle:()=>void;onArchive:()=>void;onMoveUp:()=>void;onMoveDown:()=>void;onPriority:(p:Priority)=>void;onStatus:(s:Status)=>void;onNotes:(n:string)=>void}){return <div className="rounded-lg border bg-background p-3"><div className="flex items-start gap-3"><button onClick={onToggle} className="mt-0.5 shrink-0" aria-label="Toggle task">{task.done?<span className="grid h-5 w-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="h-3 w-3"/></span>:<span className="block h-5 w-5 rounded-full border-2"/>}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`text-sm font-medium ${task.done?'line-through text-muted-foreground':''}`}>{task.title}</span><span className={`rounded-full px-2 py-0.5 text-[10px] ${task.priority==='High'?'bg-red-100 text-red-700':task.priority==='Medium'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}`}>{task.priority}</span><span className="rounded-full border px-2 py-0.5 text-[10px] text-muted-foreground">{task.status}</span></div>{task.notes&&<p className="mt-1 text-xs text-muted-foreground">{task.notes}</p>}<div className="mt-2 flex flex-wrap items-center gap-2"><select value={task.priority} onChange={e=>onPriority(e.target.value as Priority)} className="h-7 rounded-md border bg-card px-2 text-[11px]"><option>Low</option><option>Medium</option><option>High</option></select><select value={task.status} onChange={e=>onStatus(e.target.value as Status)} className="h-7 rounded-md border bg-card px-2 text-[11px]"><option>Not started</option><option>In progress</option><option>Done</option><option>Blocked</option></select><input value={task.notes} onChange={e=>onNotes(e.target.value)} className="h-7 min-w-[180px] flex-1 rounded-md border bg-card px-2 text-[11px]" placeholder="Task notes…"/></div></div><div className="flex shrink-0 items-center gap-1"><button onClick={onMoveUp} className="rounded p-1.5 hover:bg-muted" title="Move up">↑</button><button onClick={onMoveDown} className="rounded p-1.5 hover:bg-muted" title="Move down">↓</button><button onClick={onArchive} className="rounded p-1.5 text-muted-foreground hover:bg-muted hover:text-red-600" title="Archive"><Trash2 className="h-4 w-4"/></button></div></div></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>}
