'use client';

import { useEffect, useMemo, useState } from 'react';
import { Archive, CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, FileText, GripVertical, ListTodo, Plus, Search, StickyNote, Target, Trash2, X } from 'lucide-react';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { PlannerStickyWorkspace } from '@/components/planner-sticky-workspace';

type Tab='today'|'week'|'calendar'|'tasks'|'notes'|'sticky'|'progress';
type Status='To do'|'In progress'|'Waiting'|'Blocked'|'Done';
type Priority='P1'|'P2'|'P3'|'P4';
type Task={id:string;title:string;description:string;date:string;status:Status;priority:Priority;done:boolean;section:string;tag:string;order:number;deleted:boolean;createdAt:string;updatedAt:string};
type Note={id:string;title:string;text:string;date:string;createdAt:string;updatedAt:string};
type Store={tasks:Task[];notes:Note[]};
const KEY='streamearn-planner-v8';
const STATUSES:Status[]=['To do','In progress','Waiting','Blocked','Done'];
const PRIORITIES:Priority[]=['P1','P2','P3','P4'];
const fresh=():Store=>({tasks:[],notes:[]});
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const iso=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
const dateObj=(s:string)=>{const d=new Date(`${s}T12:00:00`);return Number.isNaN(d.getTime())?new Date():d};
const shift=(s:string,n:number)=>{const d=dateObj(s);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const priorityRank=(p:Priority)=>({P1:1,P2:2,P3:3,P4:4}[p]);
const statusRank=(s:Status)=>({Blocked:1,'In progress':2,Waiting:3,'To do':4,Done:5}[s]);
function clean(raw:any):Store{
 const s=fresh();
 if(raw&&Array.isArray(raw.tasks)) s.tasks=raw.tasks.filter((x:any)=>x&&typeof x.title==='string'&&x.title.trim()).map((x:any,i:number)=>{const done=Boolean(x.done)||x.status==='Done';return{id:typeof x.id==='string'?x.id:uid(),title:x.title.trim(),description:typeof x.description==='string'?x.description:'',date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:today(),status:STATUSES.includes(x.status)?x.status:(done?'Done':'To do'),priority:PRIORITIES.includes(x.priority)?x.priority:'P3',done,status:STATUSES.includes(x.status)?x.status:(done?'Done':'To do'),section:typeof x.section==='string'&&x.section.trim()?x.section.trim():'My tasks',tag:typeof x.tag==='string'?x.tag:'',order:Number.isFinite(x.order)?x.order:i,deleted:Boolean(x.deleted),createdAt:typeof x.createdAt==='string'?x.createdAt:iso(),updatedAt:typeof x.updatedAt==='string'?x.updatedAt:iso()};}).map(({done,status,...x}:any)=>({...x,done,status}));
 if(raw&&Array.isArray(raw.notes)) s.notes=raw.notes.filter((x:any)=>x&&typeof x.text==='string').map((x:any)=>({id:typeof x.id==='string'?x.id:uid(),title:typeof x.title==='string'&&x.title.trim()?x.title:'Note',text:x.text,date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:today(),createdAt:typeof x.createdAt==='string'?x.createdAt:iso(),updatedAt:typeof x.updatedAt==='string'?x.updatedAt:iso()}));
 return s;
}
function migrate(){
 if(typeof window==='undefined')return fresh();
 const keys=[KEY,'streamearn-planner-v7','streamearn-planner-v6'];
 for(const key of keys){try{const raw=JSON.parse(localStorage.getItem(key)||'null');if(raw){const data=clean(raw);return data;}}catch{}}
 return fresh();
}
function monthDays(s:string){const d=dateObj(s);d.setDate(1);const first=d.getDay();const days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return Array.from({length:42},(_,i)=>{const n=i-first+1;return n>0&&n<=days?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`:''})}

export default function PlannerV2(){
 const [store,setStore]=useState<Store>(fresh);const [ready,setReady]=useState(false);const [tab,setTab]=useState<Tab>('today');const [date,setDate]=useState(today());
 const [task,setTask]=useState('');const [taskDescription,setTaskDescription]=useState('');const [priority,setPriority]=useState<Priority>('P3');const [status,setStatus]=useState<Status>('To do');const [section,setSection]=useState('My tasks');const [tag,setTag]=useState('');
 const [search,setSearch]=useState('');const [statusFilter,setStatusFilter]=useState<'All'|Status>('All');const [priorityFilter,setPriorityFilter]=useState<'All'|Priority>('All');const [sort,setSort]=useState<'Manual'|'Priority'|'Date'|'Status'>('Manual');
 const [selected,setSelected]=useState<string[]>([]);const [expanded,setExpanded]=useState<string|null>(null);const [noteTitle,setNoteTitle]=useState('');const [noteText,setNoteText]=useState('');const [dragId,setDragId]=useState<string|null>(null);
 useEffect(()=>{setStore(migrate());setReady(true)},[]);
 useEffect(()=>{if(ready){try{localStorage.setItem(KEY,JSON.stringify(store))}catch{}}},[store,ready]);
 const active=store.tasks.filter(t=>!t.deleted);const archived=store.tasks.filter(t=>t.deleted);const completed=active.filter(t=>t.status==='Done'||t.done).length;
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();let a=active.filter(t=>(!q||`${t.title} ${t.description} ${t.section} ${t.tag} ${t.priority} ${t.status}`.toLowerCase().includes(q))&&(statusFilter==='All'||t.status===statusFilter)&&(priorityFilter==='All'||t.priority===priorityFilter));if(sort==='Priority')a.sort((x,y)=>priorityRank(x.priority)-priorityRank(y.priority)||x.order-y.order);else if(sort==='Date')a.sort((x,y)=>x.date.localeCompare(y.date)||x.order-y.order);else if(sort==='Status')a.sort((x,y)=>statusRank(x.status)-statusRank(y.status)||x.order-y.order);else a.sort((x,y)=>x.order-y.order);return a},[active,search,statusFilter,priorityFilter,sort]);
 const dayTasks=filtered.filter(t=>t.date===date);const overdue=filtered.filter(t=>t.date<today()&&t.status!=='Done');const upcoming=filtered.filter(t=>t.date>date&&t.status!=='Done');
 const week=useMemo(()=>Array.from({length:7},(_,i)=>shift(date,i)),[date]);const days=useMemo(()=>monthDays(date),[date]);
 const percent=active.length?Math.round(completed/active.length*100):0;
 const addTask=()=>{const v=task.trim();if(!v)return;const max=store.tasks.reduce((m,t)=>Math.max(m,t.order),-1)+1;const now=iso();setStore(s=>({...s,tasks:[...s.tasks,{id:uid(),title:v,description:taskDescription.trim(),date,status,priority,done:status==='Done',section:section.trim()||'My tasks',tag:tag.trim(),order:max,deleted:false,createdAt:now,updatedAt:now}]}));setTask('');setTaskDescription('');setTag('');setPriority('P3');setStatus('To do');};
 const patch=(id:string,p:Partial<Task>)=>setStore(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,...p,done:p.status==='Done'?true:(p.status&&p.status!=='Done'?false:(p.done??t.done)),updatedAt:iso()}:t)}));
 const archive=(id:string)=>patch(id,{deleted:true});const restore=(id:string)=>patch(id,{deleted:false});
 const reorder=(id:string,dir:-1|1)=>setStore(s=>{const ids=s.tasks.filter(t=>!t.deleted).sort((a,b)=>a.order-b.order);const i=ids.findIndex(t=>t.id===id);const j=i+dir;if(i<0||j<0||j>=ids.length)return s;[ids[i],ids[j]]=[ids[j],ids[i]];const orders=new Map(ids.map((t,k)=>[t.id,k]));return{...s,tasks:s.tasks.map(t=>orders.has(t.id)?{...t,order:orders.get(t.id)!,updatedAt:iso()}:t)}});
 const drop=(targetId:string)=>{if(!dragId||dragId===targetId)return;setStore(s=>{const ids=s.tasks.filter(t=>!t.deleted).sort((a,b)=>a.order-b.order);const from=ids.findIndex(t=>t.id===dragId),to=ids.findIndex(t=>t.id===targetId);if(from<0||to<0)return s;const moved=ids.splice(from,1)[0];ids.splice(to,0,moved);const orders=new Map(ids.map((t,k)=>[t.id,k]));return{...s,tasks:s.tasks.map(t=>orders.has(t.id)?{...t,order:orders.get(t.id)!,updatedAt:iso()}:t)}});setDragId(null)};
 const addNote=()=>{const text=noteText.trim();if(!text)return;const now=iso();setStore(s=>({...s,notes:[{id:uid(),title:noteTitle.trim()||'Note',text,date,createdAt:now,updatedAt:now},...s.notes]}));setNoteTitle('');setNoteText('')};
 const deleteSelected=()=>{if(!selected.length)return;setStore(s=>({...s,tasks:s.tasks.map(t=>selected.includes(t.id)?{...t,deleted:true,updatedAt:iso()}:t)}));setSelected([])};
 const updateSelected=(p:Partial<Task>)=>{if(!selected.length)return;setStore(s=>({...s,tasks:s.tasks.map(t=>selected.includes(t.id)?{...t,...p,done:p.status==='Done'?true:(p.status&&p.status!=='Done'?false:t.done),updatedAt:iso()}:t)}));setSelected([])};
 const toggleSelect=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 if(!ready)return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen p-8"><p className="text-sm text-muted-foreground">Loading Planner…</p></main></SidebarInset></SidebarProvider>;
 const TaskRow=({t,index,compact=false}:{t:Task;index:number;compact?:boolean})=><article draggable onDragStart={()=>setDragId(t.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(t.id)} className={`group rounded-lg border bg-card transition ${expanded===t.id?'ring-1 ring-primary/30':''}`}>
   <div className="flex items-start gap-2.5 px-3 py-2.5">
    <button onClick={()=>patch(t.id,{status:t.status==='Done'?'To do':'Done'})} className="mt-0.5 shrink-0" aria-label={t.status==='Done'?'Mark incomplete':'Mark complete'}>{t.status==='Done'?<span className="grid h-5 w-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="h-3 w-3"/></span>:<span className="block h-5 w-5 rounded-full border-2 border-muted-foreground/50 hover:border-primary"/>}</button>
    <button onClick={()=>setExpanded(expanded===t.id?null:t.id)} className="min-w-0 flex-1 text-left"><div className={`text-sm font-medium ${t.status==='Done'?'text-muted-foreground line-through':''}`}>{t.title}</div><div className="mt-1 flex flex-wrap items-center gap-1.5 text-[10px] text-muted-foreground"><span>{t.date}</span><span className={`rounded px-1.5 py-0.5 ${t.priority==='P1'?'bg-red-500/15 text-red-600':t.priority==='P2'?'bg-orange-500/15 text-orange-600':t.priority==='P3'?'bg-blue-500/15 text-blue-600':'bg-muted'}`}>{t.priority}</span><span className="rounded bg-muted px-1.5 py-0.5">{t.status}</span>{t.tag&&<span className="rounded bg-muted px-1.5 py-0.5">#{t.tag}</span>}</div></button>
    <input type="checkbox" checked={selected.includes(t.id)} onChange={()=>toggleSelect(t.id)} className="mt-1 h-4 w-4 shrink-0" aria-label="Select task"/>
    {!compact&&<button draggable={false} onClick={()=>reorder(t.id,-1)} className="hidden rounded p-1 text-muted-foreground hover:bg-muted md:block" title="Move up"><ChevronLeft className="h-3 w-3 rotate-90"/></button>}
    {!compact&&<button draggable={false} onClick={()=>reorder(t.id,1)} className="hidden rounded p-1 text-muted-foreground hover:bg-muted md:block" title="Move down"><ChevronRight className="h-3 w-3 rotate-90"/></button>}
    <GripVertical className="mt-1 h-4 w-4 shrink-0 text-muted-foreground/30"/>
    <button onClick={()=>archive(t.id)} className="mt-0.5 rounded p-1 text-muted-foreground opacity-0 transition group-hover:opacity-100 hover:bg-red-500/10 hover:text-red-600" title="Archive"><Archive className="h-3.5 w-3.5"/></button>
   </div>
   {expanded===t.id&&<div className="grid gap-3 border-t px-3 py-3 md:grid-cols-[1fr_260px]">
    <div><textarea value={t.description} onChange={e=>patch(t.id,{description:e.target.value})} placeholder="Add a description…" className="min-h-20 w-full resize-y rounded-md border bg-background p-2.5 text-xs outline-none"/><div className="mt-2 flex flex-wrap gap-2"><input value={t.section} onChange={e=>patch(t.id,{section:e.target.value})} placeholder="Section" className="h-8 rounded-md border bg-background px-2 text-xs"/><input value={t.tag} onChange={e=>patch(t.id,{tag:e.target.value})} placeholder="Label" className="h-8 rounded-md border bg-background px-2 text-xs"/></div></div>
    <div className="grid grid-cols-2 gap-2"><label className="text-[10px] text-muted-foreground">Status<select value={t.status} onChange={e=>patch(t.id,{status:e.target.value as Status})} className="mt-1 h-8 w-full rounded-md border bg-background px-2 text-xs">{STATUSES.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[10px] text-muted-foreground">Priority<select value={t.priority} onChange={e=>patch(t.id,{priority:e.target.value as Priority})} className="mt-1 h-8 w-full rounded-md border bg-background px-2 text-xs">{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></label><label className="col-span-2 text-[10px] text-muted-foreground">Date<input type="date" value={t.date} onChange={e=>patch(t.id,{date:e.target.value})} className="mt-1 h-8 w-full rounded-md border bg-background px-2 text-xs"/></label></div>
   </div>}
 </article>;
 const toolbar=<div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-1 rounded-md border bg-card p-1"><button onClick={()=>setStatusFilter('All')} className={`rounded px-2 py-1 text-[10px] ${statusFilter==='All'?'bg-foreground text-background':''}`}>All</button>{STATUSES.map(s=><button key={s} onClick={()=>setStatusFilter(s)} className={`rounded px-2 py-1 text-[10px] ${statusFilter===s?'bg-foreground text-background':''}`}>{s}</button>)}</div><select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value as any)} className="h-7 rounded-md border bg-card px-2 text-[10px]"><option value="All">All priority</option>{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as any)} className="h-7 rounded-md border bg-card px-2 text-[10px]"><option>Manual</option><option>Priority</option><option>Date</option><option>Status</option></select>{selected.length>0&&<><span className="text-[10px] text-muted-foreground">{selected.length} selected</span><select onChange={e=>{if(e.target.value)updateSelected({status:e.target.value as Status})}} className="h-7 rounded-md border bg-card px-2 text-[10px]"><option value="">Set status…</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><select onChange={e=>{if(e.target.value)updateSelected({priority:e.target.value as Priority})}} className="h-7 rounded-md border bg-card px-2 text-[10px]"><option value="">Set priority…</option>{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><button onClick={deleteSelected} className="inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[10px] text-red-600"><Trash2 className="h-3 w-3"/>Archive</button><button onClick={()=>setSelected([])} className="rounded p-1"><X className="h-3 w-3"/></button></>}</div>;
 return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen bg-background"><div className="mx-auto max-w-[1380px] px-4 py-5 md:px-7 md:py-7">
  <header className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">Personal command centre</p><h1 className="text-3xl font-semibold tracking-tight">Planner</h1><p className="mt-1 text-sm text-muted-foreground">Plan your day, keep tasks moving, and capture ideas in one workspace.</p></div><div className="flex items-center gap-1 rounded-lg border bg-card p-1"><button className="rounded-md p-2 hover:bg-muted" onClick={()=>setDate(shift(date,-1))}><ChevronLeft className="h-4 w-4"/></button><button className="rounded-md px-3 py-2 text-xs font-medium hover:bg-muted" onClick={()=>setDate(today())}>Today</button><button className="rounded-md p-2 hover:bg-muted" onClick={()=>setDate(shift(date,1))}><ChevronRight className="h-4 w-4"/></button></div></header>
  <nav className="mb-4 flex flex-wrap gap-1 border-b pb-2">{([['today','Today',ClipboardList],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',Check],['notes','Notes',FileText],['sticky','Sticky Wall',StickyNote],['progress','Progress',Target]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</nav>
  {tab==='today'&&<section className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Stat label="Today" value={String(dayTasks.length)}/><Stat label="Completed" value={String(completed)}/><Stat label="High priority" value={String(active.filter(t=>t.priority==='P1').length)}/></div><div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="rounded-xl border bg-card p-4"><div className="mb-3"><h2 className="text-base font-semibold">My day</h2><p className="text-xs text-muted-foreground">Keep the list focused. Use the checkbox to finish, then continue with the next item.</p></div><form onSubmit={e=>{e.preventDefault();addTask()}} className="grid gap-2 md:grid-cols-[1fr_auto_auto_auto]"><input value={task} onChange={e=>setTask(e.target.value)} placeholder="Add a task…" className="h-9 rounded-md border bg-background px-3 text-sm"/><select value={priority} onChange={e=>setPriority(e.target.value as Priority)} className="h-9 rounded-md border bg-background px-2 text-xs">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value as Status)} className="h-9 rounded-md border bg-background px-2 text-xs">{STATUSES.map(s=><option key={s}>{s}</option>)}</select><button className="inline-flex h-9 items-center justify-center gap-1 rounded-md bg-foreground px-3 text-xs font-semibold text-background"><Plus className="h-4 w-4"/>Add</button></form><div className="mt-2 grid gap-2 md:grid-cols-[1fr_auto]"><input value={taskDescription} onChange={e=>setTaskDescription(e.target.value)} placeholder="Optional description" className="h-8 rounded-md border bg-background px-3 text-xs"/><div className="flex gap-2"><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-8 rounded-md border bg-background px-2 text-xs"/><input value={tag} onChange={e=>setTag(e.target.value)} placeholder="label" className="h-8 w-24 rounded-md border bg-background px-2 text-xs"/></div></div><div className="mt-4">{dayTasks.length===0?<Empty text="Nothing planned for this day."/>:<div className="space-y-1.5">{dayTasks.map((t,i)=><TaskRow key={t.id} t={t} index={i}/>)}</div>}</div></div><aside className="space-y-3"><div className="rounded-xl border bg-card p-4"><h3 className="text-xs font-semibold">Focus</h3><p className="mt-2 text-2xl font-semibold">{dayTasks.filter(t=>t.status!=='Done').length}</p><p className="text-xs text-muted-foreground">open tasks today</p></div><div className="rounded-xl border bg-card p-4"><h3 className="text-xs font-semibold">Overdue</h3><p className="mt-2 text-2xl font-semibold">{overdue.length}</p><p className="text-xs text-muted-foreground">needs attention</p></div><div className="rounded-xl border bg-card p-4"><h3 className="text-xs font-semibold">Upcoming</h3><p className="mt-2 text-2xl font-semibold">{upcoming.length}</p><p className="text-xs text-muted-foreground">scheduled ahead</p></div></aside></div></section>}
  {tab==='week'&&<section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Week</h2><p className="text-xs text-muted-foreground">A compact view of the next seven days.</p></div></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{week.map(d=><button key={d} onClick={()=>{setDate(d);setTab('today')}} className={`min-h-40 rounded-xl border bg-card p-3 text-left hover:bg-muted ${d===today()?'ring-1 ring-primary/30':''}`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold">{dateObj(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[11px] text-muted-foreground">{dateObj(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p></div><span className="rounded-full bg-muted px-2 py-0.5 text-[9px]">{active.filter(t=>t.date===d).length}</span></div><div className="mt-3 space-y-1.5">{active.filter(t=>t.date===d).sort((a,b)=>a.order-b.order).slice(0,6).map(t=><div key={t.id} className={`truncate text-xs ${t.status==='Done'?'line-through text-muted-foreground':''}`}>{t.status==='Done'?'✓':'○'} {t.title}</div>)}</div></button>)}</div></section>}
  {tab==='calendar'&&<section className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{dateObj(date).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><p className="text-xs text-muted-foreground">Monthly calendar</p></div><div className="flex items-center gap-1"><button onClick={()=>setDate(shift(date,-30))} className="rounded-md border p-2"><ChevronLeft className="h-4 w-4"/></button><button onClick={()=>setDate(today())} className="rounded-md border px-2.5 py-1.5 text-xs">Today</button><button onClick={()=>setDate(shift(date,30))} className="rounded-md border p-2"><ChevronRight className="h-4 w-4"/></button></div></div><div className="grid grid-cols-7 border-l border-t">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="border-b border-r bg-muted/40 p-2 text-center text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{d}</div>)}{days.map((d,i)=>d?<button key={`${d}-${i}`} onClick={()=>{setDate(d);setTab('today')}} className={`min-h-32 border-b border-r p-2 text-left align-top hover:bg-muted/40 ${d===today()?'bg-primary/5':''}`}><div className="flex items-center justify-between"><span className={`text-xs font-semibold ${d===today()?'text-primary':''}`}>{dateObj(d).getDate()}</span><span className="text-[9px] text-muted-foreground">{active.filter(t=>t.date===d).length||''}</span></div><div className="mt-2 space-y-1">{active.filter(t=>t.date===d).sort((a,b)=>a.order-b.order).slice(0,4).map(t=><div key={t.id} className={`truncate rounded px-1.5 py-1 text-[10px] ${t.status==='Done'?'bg-muted text-muted-foreground line-through':'border bg-background'}`}>{t.title}</div>)}</div></button>:<div key={`blank-${i}`} className="min-h-32 border-b border-r bg-muted/10"/>)}</div></section>}
  {tab==='tasks'&&<section className="space-y-3"><div className="rounded-xl border bg-card p-3"><div className="grid gap-2 md:grid-cols-[1fr_auto]"><div className="flex items-center gap-2 rounded-md border bg-background px-3"><Search className="h-3.5 w-3.5 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks, labels, priorities or status…" className="h-8 w-full bg-transparent text-xs outline-none"/></div><button onClick={()=>setSelected(filtered.map(t=>t.id))} className="rounded-md border px-3 py-1.5 text-xs">Select visible</button></div><div className="mt-2">{toolbar}</div></div><div className="rounded-xl border bg-card p-3"><div className="mb-2 flex items-center justify-between"><h2 className="font-semibold">To-Do list</h2><span className="text-xs text-muted-foreground">{filtered.length} tasks</span></div>{filtered.length===0?<Empty text="No tasks match these filters."/>:<div className="space-y-1.5">{filtered.map((t,i)=><TaskRow key={t.id} t={t} index={i} />)}</div>}</div><details className="rounded-xl border bg-card p-3"><summary className="cursor-pointer text-xs font-semibold text-muted-foreground">Archived ({archived.length})</summary><div className="mt-3 space-y-1.5">{archived.length===0?<p className="text-xs text-muted-foreground">Nothing archived.</p>:archived.map(t=><div key={t.id} className="flex items-center gap-3 rounded-md border p-2.5 text-xs"><span className="flex-1 truncate">{t.title}</span><button onClick={()=>restore(t.id)} className="text-primary">Restore</button></div>)}</div></details></section>}
  {tab==='notes'&&<section className="grid gap-4 lg:grid-cols-[360px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Notes</h2><p className="mt-1 text-xs text-muted-foreground">Capture meeting notes, ideas and supporting context.</p><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Title" className="mt-4 h-9 w-full rounded-md border bg-background px-3 text-sm"/><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Write anything…" className="mt-2 min-h-52 w-full rounded-md border bg-background p-3 text-xs"/><button onClick={addNote} className="mt-2 inline-flex items-center gap-1 rounded-md bg-foreground px-3 py-2 text-xs text-background"><Plus className="h-4 w-4"/>Save note</button></div><div className="space-y-2">{store.notes.length===0?<Empty text="No notes yet."/>:store.notes.map(n=><article key={n.id} className="rounded-xl border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">{n.title}</h3><p className="mt-0.5 text-[10px] text-muted-foreground">{n.date}</p></div><button onClick={()=>setStore(s=>({...s,notes:s.notes.filter(x=>x.id!==n.id)}))} className="rounded p-1 text-muted-foreground hover:text-red-600"><Trash2 className="h-3.5 w-3.5"/></button></div><p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{n.text}</p></article>)}</div></section>}
  {tab==='sticky'&&<PlannerStickyWorkspace embedded/>}
  {tab==='progress'&&<section className="space-y-4"><div className="grid gap-3 sm:grid-cols-4"><Stat label="Active" value={String(active.length)}/><Stat label="Done" value={String(completed)}/><Stat label="Completion" value={`${percent}%`}/><Stat label="Blocked" value={String(active.filter(t=>t.status==='Blocked').length)}/></div><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Work distribution</h2><div className="mt-4 space-y-3">{STATUSES.map(s=>{const n=active.filter(t=>t.status===s).length;const w=active.length?Math.round(n/active.length*100):0;return <div key={s}><div className="mb-1 flex justify-between text-xs"><span>{s}</span><span>{n}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${w}%`}}/></div></div>})}</div></div></section>}
 </div></main></SidebarInset></SidebarProvider>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-4"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="grid min-h-28 place-items-center rounded-lg border border-dashed p-5 text-center"><div><p className="text-sm text-muted-foreground">{text}</p></div></div>}
