'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, FileText, ListTodo, Plus, Search, StickyNote, Target, Trash2, X } from 'lucide-react';
import Link from 'next/link';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { PlannerStickyWorkspace } from '@/components/planner-sticky-workspace';

type Tab='today'|'week'|'calendar'|'tasks'|'notes'|'sticky'|'progress';
type Status='Not started'|'In progress'|'Done'|'Blocked';
type Priority='Low'|'Medium'|'High';
type Task={id:string;title:string;date:string;done:boolean;priority:Priority;status:Status;deleted:boolean};
type Note={id:string;title:string;text:string;date:string};
type Store={tasks:Task[];notes:Note[]};
const KEY='streamearn-planner-v7';
const fresh=():Store=>({tasks:[],notes:[]});
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const asDate=(s:string)=>{const d=new Date(`${s}T12:00:00`);return Number.isNaN(d.getTime())?new Date():d};
const shift=(s:string,n:number)=>{const d=asDate(s);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const clean=(raw:any):Store=>({tasks:Array.isArray(raw?.tasks)?raw.tasks.filter((x:any)=>x&&typeof x.title==='string').map((x:any)=>({id:typeof x.id==='string'?x.id:uid(),title:x.title.trim(),date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:today(),done:Boolean(x.done),priority:x.priority==='High'||x.priority==='Low'?x.priority:'Medium',status:['Not started','In progress','Done','Blocked'].includes(x.status)?x.status:(x.done?'Done':'Not started'),deleted:Boolean(x.deleted)})).filter((x:any)=>x.title):[],notes:Array.isArray(raw?.notes)?raw.notes.filter((x:any)=>x&&typeof x.text==='string').map((x:any)=>({id:typeof x.id==='string'?x.id:uid(),title:typeof x.title==='string'?x.title:'Note',text:x.text,date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:today()})):[]});

export default function PlannerV2(){
 const [store,setStore]=useState<Store>(fresh); const [ready,setReady]=useState(false); const [tab,setTab]=useState<Tab>('today'); const [date,setDate]=useState(today()); const [task,setTask]=useState(''); const [search,setSearch]=useState(''); const [noteTitle,setNoteTitle]=useState(''); const [noteText,setNoteText]=useState('');
 useEffect(()=>{try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw)setStore(clean(raw));else{const legacy=JSON.parse(localStorage.getItem('streamearn-planner-v6')||'null');setStore(clean(legacy||{}))}}catch{setStore(fresh())}finally{setReady(true)}},[]);
 useEffect(()=>{if(ready){try{localStorage.setItem(KEY,JSON.stringify(store))}catch{}}},[store,ready]);
 const active=store.tasks.filter(t=>!t.deleted); const archived=store.tasks.filter(t=>t.deleted); const visible=active.filter(t=>!search||`${t.title} ${t.priority} ${t.status}`.toLowerCase().includes(search.toLowerCase())); const completed=active.filter(t=>t.done||t.status==='Done').length; const percent=active.length?Math.round(completed/active.length*100):0;
 const dayTasks=visible.filter(t=>t.date===date); const week=useMemo(()=>Array.from({length:7},(_,i)=>shift(date,i)),[date]);
 const month=useMemo(()=>{const d=asDate(date);d.setDate(1);const first=d.getDay();const days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return Array.from({length:42},(_,i)=>{const n=i-first+1;return n>0&&n<=days?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`:''})},[date]);
 const addTask=()=>{const v=task.trim();if(!v)return;setStore(s=>({...s,tasks:[...s.tasks,{id:uid(),title:v,date,done:false,priority:'Medium',status:'Not started',deleted:false}]}));setTask('')};
 const patch=(id:string,p:Partial<Task>)=>setStore(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,...p,done:p.status==='Done'?true:(p.done??t.done)}:t)}));
 const remove=(id:string)=>patch(id,{deleted:true});
 const move=(id:string,dir:-1|1)=>setStore(s=>{const a=[...s.tasks];const i=a.findIndex(t=>t.id===id);if(i<0)return s;const j=i+dir;if(j<0||j>=a.length)return s;[a[i],a[j]]=[a[j],a[i]];return{...s,tasks:a}});
 const addNote=()=>{if(!noteText.trim())return;setStore(s=>({...s,notes:[{id:uid(),title:noteTitle.trim()||'Note',text:noteText.trim(),date},...s.notes]}));setNoteTitle('');setNoteText('')};
 if(!ready)return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen p-8"><p className="text-sm text-muted-foreground">Loading Planner…</p></main></SidebarInset></SidebarProvider>;
 const taskList=(items:Task[])=>items.length===0?<p className="py-10 text-center text-sm text-muted-foreground">No tasks.</p>:<div className="divide-y">{items.map((t,i)=><div key={t.id} className="group grid grid-cols-[auto_1fr_auto] items-center gap-3 py-3"><button aria-label="Mark task done" onClick={()=>patch(t.id,{done:!t.done,status:!t.done?'Done':'Not started'})}>{t.done?<span className="grid h-5 w-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="h-3 w-3"/></span>:<span className="h-5 w-5 rounded-full border-2"/>}</button><div className="min-w-0"><div className={`truncate text-sm ${t.done?'line-through text-muted-foreground':''}`}>{t.title}</div><div className="mt-1 flex flex-wrap items-center gap-1.5"><select value={t.status} onChange={e=>patch(t.id,{status:e.target.value as Status})} className="h-6 rounded border bg-background px-1.5 text-[10px]"><option>Not started</option><option>In progress</option><option>Done</option><option>Blocked</option></select><select value={t.priority} onChange={e=>patch(t.id,{priority:e.target.value as Priority})} className="h-6 rounded border bg-background px-1.5 text-[10px]"><option>Low</option><option>Medium</option><option>High</option></select><span className="text-[10px] text-muted-foreground">{t.date}</span></div></div><div className="flex items-center gap-1 opacity-100 md:opacity-0 md:group-hover:opacity-100"><button onClick={()=>move(t.id,-1)} className="rounded border px-1.5 py-1 text-[10px]" aria-label="Move up">↑</button><button onClick={()=>move(t.id,1)} className="rounded border px-1.5 py-1 text-[10px]" aria-label="Move down">↓</button><button onClick={()=>remove(t.id)} className="rounded p-1.5 text-muted-foreground hover:text-red-600" aria-label="Archive"><Trash2 className="h-3.5 w-3.5"/></button></div></div>)}</div>;
 return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen bg-background"><div className="mx-auto max-w-[1320px] px-4 py-5 md:px-7 md:py-7"><header className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">Personal command centre</p><h1 className="text-3xl font-semibold tracking-tight">Planner</h1><p className="mt-1 text-sm text-muted-foreground">Organize tasks, notes, calendar and your Sticky Wall in one place.</p></div><div className="flex items-center gap-1 rounded-lg border bg-card p-1"><button className="rounded-md p-2 hover:bg-muted" onClick={()=>setDate(shift(date,-1))}><ChevronLeft className="h-4 w-4"/></button><button className="rounded-md px-3 py-2 text-xs font-medium hover:bg-muted" onClick={()=>setDate(today())}>Today</button><button className="rounded-md p-2 hover:bg-muted" onClick={()=>setDate(shift(date,1))}><ChevronRight className="h-4 w-4"/></button></div></header>
 <nav className="mb-5 flex flex-wrap gap-1 border-b pb-2">{([['today','Today',ClipboardList],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',Check],['notes','Notes',FileText],['sticky','Sticky Wall',StickyNote],['progress','Progress',Target]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</nav>
 {tab==='today'&&<section className="grid gap-5 lg:grid-cols-[1fr_300px]"><div className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">{date===today()?'Today':asDate(date).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</h2></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{dayTasks.filter(t=>!t.done).length} pending</span></div><form onSubmit={e=>{e.preventDefault();addTask()}} className="mb-3 flex gap-2"><input value={task} onChange={e=>setTask(e.target.value)} placeholder="Add a task…" className="h-9 flex-1 rounded-md border bg-background px-3 text-sm"/><button className="rounded-md bg-foreground px-3 text-xs font-semibold text-background"><Plus className="mr-1 inline h-4 w-4"/>Add</button></form><div className="mb-3 flex items-center gap-2"><Search className="h-3.5 w-3.5 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search and filter…" className="h-8 w-full rounded-md border bg-background px-3 text-xs"/></div>{taskList(dayTasks)}</div><aside className="space-y-3"><Stat label="Completion" value={`${percent}%`}/><Stat label="Active tasks" value={String(active.length)}/><Stat label="High priority" value={String(active.filter(t=>t.priority==='High').length)}/></aside></section>}
 {tab==='week'&&<section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{week.map(d=><button key={d} onClick={()=>{setDate(d);setTab('today')}} className="min-h-36 rounded-xl border bg-card p-3 text-left hover:bg-muted"><p className="text-xs font-semibold">{asDate(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[11px] text-muted-foreground">{asDate(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p><div className="mt-3 space-y-1">{active.filter(t=>t.date===d).slice(0,6).map(t=><div key={t.id} className="truncate text-xs">{t.done?'✓':'○'} {t.title}</div>)}</div></button>)}</section>}
 {tab==='calendar'&&<section className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{asDate(date).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><p className="text-xs text-muted-foreground">Monthly calendar</p></div></div><div className="grid grid-cols-7 border-l border-t">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="border-b border-r bg-muted/40 p-2 text-center text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{d}</div>)}{month.map((d,i)=>d?<button key={`${d}-${i}`} onClick={()=>{setDate(d);setTab('today')}} className={`min-h-28 border-b border-r p-2 text-left align-top hover:bg-muted/40 ${d===today()?'bg-primary/5':''}`}><div className="flex items-center justify-between"><span className={`text-xs font-semibold ${d===today()?'text-primary':''}`}>{asDate(d).getDate()}</span>{active.filter(t=>t.date===d).length>0&&<span className="rounded bg-muted px-1.5 py-0.5 text-[9px]">{active.filter(t=>t.date===d).length}</span>}</div><div className="mt-2 space-y-1">{active.filter(t=>t.date===d).slice(0,3).map(t=><div key={t.id} className={`truncate rounded px-1.5 py-1 text-[10px] ${t.done?'bg-muted text-muted-foreground line-through':'bg-background border'}`}>{t.title}</div>)}</div></button>:<div key={`blank-${i}`} className="min-h-28 border-b border-r bg-muted/10"/> )}</div></section>}
 {tab==='tasks'&&<section className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">All tasks</h2><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…" className="h-8 w-48 rounded-md border bg-background px-3 text-xs"/></div>{taskList(visible)}{archived.length>0&&<details className="mt-5"><summary className="cursor-pointer text-xs font-semibold text-muted-foreground">Archived ({archived.length})</summary><div className="mt-2 divide-y">{archived.map(t=><div key={t.id} className="flex items-center gap-2 py-2 text-xs"><span className="flex-1">{t.title}</span><button onClick={()=>patch(t.id,{deleted:false})} className="text-primary">Restore</button></div>)}</div></details>}</section>}
 {tab==='notes'&&<section className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Pages & Notes</h2><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Title" className="mt-3 h-9 w-full rounded-md border bg-background px-3 text-sm"/><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Write notes…" className="mt-2 min-h-48 w-full rounded-md border bg-background p-3 text-sm"/><button onClick={addNote} className="mt-2 rounded-md bg-foreground px-3 py-2 text-xs text-background">Save note</button></div><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Saved</h2><div className="mt-3 space-y-2">{store.notes.length===0?<p className="text-sm text-muted-foreground">Nothing saved.</p>:store.notes.map(n=><article key={n.id} className="rounded-lg border p-3"><div className="flex justify-between"><strong className="text-sm">{n.title}</strong><span className="text-[10px] text-muted-foreground">{n.date}</span></div><p className="mt-2 whitespace-pre-wrap text-xs text-muted-foreground">{n.text}</p></article>)}</div></div></section>}
 {tab==='sticky'&&<PlannerStickyWorkspace/>}
 {tab==='progress'&&<section className="grid gap-4 sm:grid-cols-4"><Stat label="Active" value={String(active.length)}/><Stat label="Completed" value={String(completed)}/><Stat label="Completion" value={`${percent}%`}/><Stat label="Blocked" value={String(active.filter(t=>t.status==='Blocked').length)}/></section>}
 </div></main></SidebarInset></SidebarProvider>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-4"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>}
