'use client';

import { useEffect, useMemo, useState } from 'react';
import { Archive, CalendarDays, Check, ChevronLeft, ChevronRight, FileText, Flag, GripVertical, ListTodo, MoveDown, MoveUp, Plus, Search, StickyNote, Target, X } from 'lucide-react';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { PlannerStickyWorkspace } from '@/components/planner-sticky-workspace';

type Tab = 'today' | 'week' | 'calendar' | 'tasks' | 'notes' | 'sticky' | 'progress';
type Status = 'To do' | 'In progress' | 'Waiting' | 'Blocked' | 'Done';
type Priority = 'None' | 'Low' | 'Medium' | 'High';
type Task = { id: string; title: string; description: string; date: string; status: Status; priority: Priority; done: boolean; tags: string[]; order: number; deleted: boolean; updated: string };
type Note = { id: string; title: string; text: string; date: string; updated: string };
type Store = { tasks: Task[]; notes: Note[] };

const KEY = 'streamearn-planner-v9';
const STATUSES: Status[] = ['To do', 'In progress', 'Waiting', 'Blocked', 'Done'];
const PRIORITIES: Priority[] = ['None', 'Low', 'Medium', 'High'];
const fresh = (): Store => ({ tasks: [], notes: [] });
const uid = () => globalThis.crypto?.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const now = () => new Date().toISOString();
const today = () => new Date().toISOString().slice(0, 10);
const safeDate = (value: unknown) => typeof value === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(value) ? value : today();
const dateObj = (value: string) => new Date(`${safeDate(value)}T12:00:00`);
const shift = (value: string, amount: number) => { const d = dateObj(value); d.setDate(d.getDate() + amount); return d.toISOString().slice(0, 10); };
const monthCells = (value: string) => { const d = dateObj(value); d.setDate(1); const first = d.getDay(); const count = new Date(d.getFullYear(), d.getMonth() + 1, 0).getDate(); return Array.from({ length: 42 }, (_, i) => { const n = i - first + 1; return n < 1 || n > count ? '' : `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(n).padStart(2, '0')}`; }); };

function sanitize(raw: any): Store {
  const store = fresh();
  if (!raw || typeof raw !== 'object') return store;
  if (Array.isArray(raw.tasks)) store.tasks = raw.tasks.map((x: any, i: number) => {
    const done = Boolean(x?.done) || x?.status === 'Done';
    const status: Status = STATUSES.includes(x?.status) ? x.status : (done ? 'Done' : 'To do');
    const priority: Priority = PRIORITIES.includes(x?.priority) ? x.priority : 'None';
    return { id: typeof x?.id === 'string' ? x.id : uid(), title: typeof x?.title === 'string' ? x.title.trim() : '', description: typeof x?.description === 'string' ? x.description : '', date: safeDate(x?.date), status, priority, done: status === 'Done' || done, tags: Array.isArray(x?.tags) ? x.tags.filter((t: any) => typeof t === 'string').slice(0, 8) : [], order: Number.isFinite(x?.order) ? x.order : i, deleted: Boolean(x?.deleted), updated: typeof x?.updated === 'string' ? x.updated : now() } as Task;
  }).filter((x: Task) => x.title);
  if (Array.isArray(raw.notes)) store.notes = raw.notes.map((x: any) => ({ id: typeof x?.id === 'string' ? x.id : uid(), title: typeof x?.title === 'string' && x.title.trim() ? x.title.trim() : 'Untitled note', text: typeof x?.text === 'string' ? x.text : '', date: safeDate(x?.date), updated: typeof x?.updated === 'string' ? x.updated : now() })).filter((x: Note) => x.text.trim());
  return store;
}

function loadStore(): Store {
  if (typeof window === 'undefined') return fresh();
  const keys = [KEY, 'streamearn-planner-v8', 'streamearn-planner-v7', 'streamearn-planner-v6'];
  for (const key of keys) { try { const raw = JSON.parse(localStorage.getItem(key) || 'null'); if (raw) return sanitize(raw); } catch {} }
  return fresh();
}

export default function PlannerV4() {
  const [store, setStore] = useState<Store>(fresh);
  const [ready, setReady] = useState(false);
  const [tab, setTab] = useState<Tab>('today');
  const [date, setDate] = useState(today());
  const [taskTitle, setTaskTitle] = useState('');
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<'All' | Status>('All');
  const [priorityFilter, setPriorityFilter] = useState<'All' | Priority>('All');
  const [sort, setSort] = useState<'Manual' | 'Priority' | 'Date' | 'Status'>('Manual');
  const [selected, setSelected] = useState<string[]>([]);
  const [openTask, setOpenTask] = useState<string | null>(null);
  const [noteTitle, setNoteTitle] = useState('');
  const [noteText, setNoteText] = useState('');

  useEffect(() => { setStore(loadStore()); setReady(true); }, []);
  useEffect(() => { if (ready) try { localStorage.setItem(KEY, JSON.stringify(store)); } catch {} }, [store, ready]);

  const active = useMemo(() => store.tasks.filter(t => !t.deleted), [store.tasks]);
  const archived = useMemo(() => store.tasks.filter(t => t.deleted), [store.tasks]);
  const completed = active.filter(t => t.status === 'Done' || t.done).length;
  const percent = active.length ? Math.round(completed / active.length * 100) : 0;
  const normalized = search.trim().toLowerCase();
  const filtered = useMemo(() => {
    const list = active.filter(t => (!normalized || `${t.title} ${t.description} ${t.tags.join(' ')} ${t.status} ${t.priority}`.toLowerCase().includes(normalized)) && (statusFilter === 'All' || t.status === statusFilter) && (priorityFilter === 'All' || t.priority === priorityFilter));
    return [...list].sort((a, b) => sort === 'Priority' ? priorityRank(b.priority) - priorityRank(a.priority) || a.order - b.order : sort === 'Date' ? a.date.localeCompare(b.date) || a.order - b.order : sort === 'Status' ? STATUSES.indexOf(a.status) - STATUSES.indexOf(b.status) || a.order - b.order : a.order - b.order);
  }, [active, normalized, priorityFilter, sort, statusFilter]);
  const dayTasks = filtered.filter(t => t.date === date);
  const week = useMemo(() => Array.from({ length: 7 }, (_, i) => shift(date, i)), [date]);
  const days = useMemo(() => monthCells(date), [date]);

  const updateTask = (id: string, patch: Partial<Task>) => setStore(s => ({ ...s, tasks: s.tasks.map(t => t.id === id ? { ...t, ...patch, done: patch.status === 'Done' ? true : patch.status && patch.status !== 'Done' ? false : patch.done ?? t.done, updated: now() } : t) }));
  const addTask = () => { const title = taskTitle.trim(); if (!title) return; const order = active.reduce((m, t) => Math.max(m, t.order), -1) + 1; setStore(s => ({ ...s, tasks: [...s.tasks, { id: uid(), title, description: '', date, status: 'To do', priority: 'None', done: false, tags: [], order, deleted: false, updated: now() }] })); setTaskTitle(''); };
  const moveTask = (id: string, direction: -1 | 1) => setStore(s => { const ordered = [...s.tasks.filter(t => !t.deleted)].sort((a, b) => a.order - b.order); const i = ordered.findIndex(t => t.id === id); const j = i + direction; if (i < 0 || j < 0 || j >= ordered.length) return s; [ordered[i].order, ordered[j].order] = [ordered[j].order, ordered[i].order]; return { ...s, tasks: s.tasks.map(t => ordered.find(x => x.id === t.id) || t) }; });
  const toggleDone = (id: string) => { const t = active.find(x => x.id === id); if (t) updateTask(id, { status: t.status === 'Done' ? 'To do' : 'Done' }); };
  const addNote = () => { if (!noteText.trim()) return; setStore(s => ({ ...s, notes: [{ id: uid(), title: noteTitle.trim() || 'Untitled note', text: noteText.trim(), date, updated: now() }, ...s.notes] })); setNoteTitle(''); setNoteText(''); };
  const toggleSelect = (id: string) => setSelected(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  const archiveSelected = () => { if (!selected.length) return; setStore(s => ({ ...s, tasks: s.tasks.map(t => selected.includes(t.id) ? { ...t, deleted: true, updated: now() } : t) })); setSelected([]); };

  if (!ready) return <SidebarProvider><UnifiedSidebar /><SidebarInset><main className="min-h-screen p-6"><p className="text-sm text-muted-foreground">Loading Planner…</p></main></SidebarInset></SidebarProvider>;

  return <SidebarProvider><UnifiedSidebar /><SidebarInset><main className="min-h-screen w-full overflow-x-hidden bg-background"><div className="mx-auto w-full max-w-[1320px] min-w-0 px-3 py-4 sm:px-5 lg:px-6">
    <header className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Planner</h1><p className="mt-0.5 text-xs text-muted-foreground">Tasks, dates, notes and your Sticky Wall.</p></div><div className="flex items-center gap-1 rounded-lg border bg-card p-1"><button className="rounded-md p-1.5 hover:bg-muted" onClick={() => setDate(shift(date, -1))} aria-label="Previous"><ChevronLeft className="h-4 w-4" /></button><button className="rounded-md px-2.5 py-1.5 text-xs hover:bg-muted" onClick={() => setDate(today())}>Today</button><button className="rounded-md p-1.5 hover:bg-muted" onClick={() => setDate(shift(date, 1))} aria-label="Next"><ChevronRight className="h-4 w-4" /></button></div></header>
    <nav className="mb-4 flex min-w-0 flex-wrap gap-1 border-b pb-2">{([['today','Today',ListTodo],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',Check],['notes','Notes',FileText],['sticky','Sticky Wall',StickyNote],['progress','Progress',Target]] as const).map(([id,label,Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted'}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</nav>

    {tab === 'today' && <section className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_250px]"><div className="min-w-0 rounded-xl border bg-card"><div className="border-b p-4"><div className="flex items-center justify-between gap-2"><div><h2 className="font-semibold">{date===today()?'Today':dateObj(date).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h2><p className="mt-1 text-xs text-muted-foreground">Focus on what needs to be finished today.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-[11px]">{dayTasks.filter(t=>t.status!=='Done').length} pending</span></div><form onSubmit={e=>{e.preventDefault();addTask()}} className="mt-3 flex gap-2"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} className="h-9 min-w-0 flex-1 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" placeholder="Add a task…"/><button className="inline-flex h-9 items-center gap-1.5 rounded-lg bg-foreground px-3 text-xs font-semibold text-background"><Plus className="h-4 w-4"/>Add</button></form></div><TaskList tasks={dayTasks} selected={selected} onSelect={toggleSelect} onToggle={toggleDone} onPatch={updateTask} onMove={moveTask} onArchive={id=>updateTask(id,{deleted:true})} onOpen={setOpenTask}/></div><aside className="grid grid-cols-2 gap-2 lg:grid-cols-1"><Metric label="Today" value={String(active.filter(t=>t.date===today()).length)} /><Metric label="Overdue" value={String(active.filter(t=>t.date<today()&&t.status!=='Done').length)} /><Metric label="High priority" value={String(active.filter(t=>t.priority==='High'&&t.status!=='Done').length)} /><Metric label="Completion" value={`${percent}%`} /></aside></section>}

    {tab === 'week' && <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{week.map(d=><button key={d} onClick={()=>{setDate(d);setTab('today')}} className="min-h-32 rounded-xl border bg-card p-3 text-left hover:bg-muted/40"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold">{dateObj(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[11px] text-muted-foreground">{dateObj(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p></div><span className="text-[10px] text-muted-foreground">{active.filter(t=>t.date===d).length}</span></div><div className="mt-3 space-y-1">{active.filter(t=>t.date===d).slice(0,6).map(t=><div key={t.id} className={`truncate rounded-md border px-2 py-1 text-[10px] ${t.status==='Done'?'line-through text-muted-foreground':''}`}>{t.status==='Done'?'✓':'○'} {t.title}</div>)}</div></button>)}</section>}

    {tab === 'calendar' && <section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between gap-3 border-b p-3 sm:p-4"><div><h2 className="text-base font-semibold">{dateObj(date).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><p className="mt-0.5 text-[11px] text-muted-foreground">Monthly calendar</p></div><div className="flex items-center gap-1"><button onClick={()=>setDate(shift(date,-30))} className="rounded-md border p-1.5 hover:bg-muted" aria-label="Previous month"><ChevronLeft className="h-4 w-4"/></button><button onClick={()=>setDate(today())} className="rounded-md border px-2.5 py-1.5 text-[11px] hover:bg-muted">Today</button><button onClick={()=>setDate(shift(date,30))} className="rounded-md border p-1.5 hover:bg-muted" aria-label="Next month"><ChevronRight className="h-4 w-4"/></button></div></div><div className="grid grid-cols-7 border-l border-t">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="border-b border-r bg-muted/30 px-1 py-1.5 text-center text-[9px] font-semibold uppercase tracking-wide text-muted-foreground sm:px-2 sm:text-[10px]">{d}</div>)}{days.map((d,i)=>d?<button key={`${d}-${i}`} onClick={()=>{setDate(d);setTab('today')}} className={`min-h-20 overflow-hidden border-b border-r p-1.5 text-left align-top hover:bg-muted/30 sm:min-h-24 sm:p-2 ${d===today()?'bg-primary/5':''}`}><div className={`text-[10px] font-semibold sm:text-xs ${d===today()?'text-primary':''}`}>{dateObj(d).getDate()}</div><div className="mt-1 space-y-0.5">{active.filter(t=>t.date===d).slice(0,3).map(t=><div key={t.id} className={`truncate rounded px-1 py-0.5 text-[8px] sm:text-[9px] ${t.status==='Done'?'bg-muted text-muted-foreground line-through':t.priority==='High'?'bg-red-500/10 text-red-700':'bg-background border'}`}>{t.title}</div>)}{active.filter(t=>t.date===d).length>3&&<div className="text-[8px] text-muted-foreground">+{active.filter(t=>t.date===d).length-3} more</div>}</div></button>:<div key={`blank-${i}`} className="min-h-20 border-b border-r bg-muted/10 sm:min-h-24"/>)}</div></section>}

    {tab === 'tasks' && <section className="space-y-3"><div className="rounded-xl border bg-card p-3"><div className="grid gap-2 lg:grid-cols-[minmax(0,1fr)_auto_auto_auto]"> <div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks, labels, status…" className="h-9 w-full rounded-lg border bg-background pl-9 pr-3 text-xs"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as any)} className="h-9 rounded-lg border bg-background px-2 text-xs"><option>All</option>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value as any)} className="h-9 rounded-lg border bg-background px-2 text-xs"><option>All</option>{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as any)} className="h-9 rounded-lg border bg-background px-2 text-xs"><option>Manual</option><option>Priority</option><option>Date</option><option>Status</option></select></div>{selected.length>0&&<div className="mt-2 flex items-center gap-2"><span className="text-xs text-muted-foreground">{selected.length} selected</span><button onClick={archiveSelected} className="rounded-md bg-muted px-2.5 py-1.5 text-[11px]">Archive selected</button></div>}</div><div className="overflow-hidden rounded-xl border bg-card"><TaskList tasks={filtered} selected={selected} onSelect={toggleSelect} onToggle={toggleDone} onPatch={updateTask} onMove={moveTask} onArchive={id=>updateTask(id,{deleted:true})} onOpen={setOpenTask}/></div>{archived.length>0&&<details className="rounded-xl border bg-card"><summary className="cursor-pointer px-4 py-3 text-xs font-medium">Archived ({archived.length})</summary><div className="divide-y border-t">{archived.map(t=><div key={t.id} className="flex items-center gap-3 px-4 py-2.5 text-xs"><span className="flex-1 truncate">{t.title}</span><button onClick={()=>updateTask(t.id,{deleted:false})} className="text-primary">Restore</button></div>)}</div></details>}</section>}

    {tab === 'notes' && <section className="grid gap-3 lg:grid-cols-[340px_minmax(0,1fr)]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Notes</h2><p className="mt-1 text-xs text-muted-foreground">Capture ideas, study notes and meeting notes.</p><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Title" className="mt-3 h-9 w-full rounded-lg border bg-background px-3 text-sm"/><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} placeholder="Write something…" className="mt-2 min-h-44 w-full rounded-lg border bg-background p-3 text-sm outline-none"/><button onClick={addNote} className="mt-2 inline-flex items-center gap-1.5 rounded-lg bg-foreground px-3 py-2 text-xs font-semibold text-background"><Plus className="h-3.5 w-3.5"/>Save note</button></div><div className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Saved notes</h2><span className="text-xs text-muted-foreground">{store.notes.length}</span></div><div className="mt-3 space-y-2">{store.notes.length===0?<p className="py-10 text-center text-sm text-muted-foreground">Nothing saved yet.</p>:store.notes.map(n=><article key={n.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-medium">{n.title}</h3><span className="text-[10px] text-muted-foreground">{n.date}</span></div><button onClick={()=>setStore(s=>({...s,notes:s.notes.filter(x=>x.id!==n.id)}))} className="text-muted-foreground hover:text-red-600"><X className="h-4 w-4"/></button></div><p className="mt-2 whitespace-pre-wrap text-xs text-muted-foreground">{n.text}</p></article>)}</div></div></section>}

    {tab === 'sticky' && <PlannerStickyWorkspace />}
    {tab === 'progress' && <section className="space-y-3"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Active" value={String(active.length)}/><Metric label="Completed" value={String(completed)}/><Metric label="Completion" value={`${percent}%`}/><Metric label="Blocked" value={String(active.filter(t=>t.status==='Blocked').length)}/></div><div className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Progress</h2><span className="text-xs text-muted-foreground">{completed} of {active.length}</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-foreground" style={{width:`${percent}%`}}/></div></div></section>}
  </div></main></SidebarInset>
  {openTask && <TaskDetail task={active.find(t=>t.id===openTask)} onClose={()=>setOpenTask(null)} onPatch={updateTask}/>}</SidebarProvider>;
}

function priorityRank(p: Priority) { return ({High: 4, Medium: 3, Low: 2, None: 1} as Record<Priority, number>)[p]; }

function TaskList({ tasks, selected, onSelect, onToggle, onPatch, onMove, onArchive, onOpen }: { tasks: Task[]; selected: string[]; onSelect: (id:string)=>void; onToggle:(id:string)=>void; onPatch:(id:string,p:Partial<Task>)=>void; onMove:(id:string,d:-1|1)=>void; onArchive:(id:string)=>void; onOpen:(id:string)=>void }) {
  if (!tasks.length) return <p className="py-14 text-center text-sm text-muted-foreground">No tasks match this view.</p>;
  return <div className="divide-y">{tasks.map((task,index)=><div key={task.id} className="group flex items-start gap-2.5 px-3 py-3 sm:px-4"><button onClick={()=>onToggle(task.id)} className="mt-0.5 shrink-0" aria-label={task.done?'Mark incomplete':'Mark complete'}>{task.done?<span className="grid h-5 w-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="h-3 w-3"/></span>:<span className="block h-5 w-5 rounded-full border-2 border-muted-foreground/40 hover:border-primary"/>}</button><input type="checkbox" checked={selected.includes(task.id)} onChange={()=>onSelect(task.id)} className="mt-1 h-4 w-4 shrink-0" aria-label="Select task"/><div className="min-w-0 flex-1"><button onClick={()=>onOpen(task.id)} className={`block max-w-full truncate text-left text-sm font-medium ${task.done?'text-muted-foreground line-through':''}`}>{task.title}</button>{task.description&&<p className="mt-0.5 line-clamp-1 text-[11px] text-muted-foreground">{task.description}</p>}<div className="mt-1.5 flex flex-wrap items-center gap-1.5"><select value={task.status} onChange={e=>onPatch(task.id,{status:e.target.value as Status})} className="h-6 rounded-md border bg-background px-1.5 text-[10px]">{STATUSES.map(s=><option key={s}>{s}</option>)}</select><label className="inline-flex h-6 items-center gap-1 rounded-md border bg-background px-1.5 text-[10px]"><Flag className="h-3 w-3"/><select value={task.priority} onChange={e=>onPatch(task.id,{priority:e.target.value as Priority})} className="bg-transparent outline-none">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select></label><label className="inline-flex h-6 items-center rounded-md border bg-background px-1.5 text-[10px]"><input type="date" value={task.date} onChange={e=>onPatch(task.id,{date:e.target.value})} className="w-[92px] bg-transparent outline-none"/></label>{task.tags.slice(0,3).map(t=><span key={t} className="rounded-md bg-muted px-1.5 py-1 text-[10px] text-muted-foreground">#{t}</span>)}</div></div><div className="flex shrink-0 items-center gap-1 opacity-100 md:opacity-0 md:group-hover:opacity-100"><button onClick={()=>onMove(task.id,-1)} disabled={index===0} className="rounded-md border p-1.5 hover:bg-muted disabled:opacity-30" title="Move up"><MoveUp className="h-3 w-3"/></button><button onClick={()=>onMove(task.id,1)} disabled={index===tasks.length-1} className="rounded-md border p-1.5 hover:bg-muted disabled:opacity-30" title="Move down"><MoveDown className="h-3 w-3"/></button><GripVertical className="h-4 w-4 text-muted-foreground/25"/><button onClick={()=>onArchive(task.id)} className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-red-600" title="Archive"><Archive className="h-3.5 w-3.5"/></button></div></div>)}</div>;
}

function TaskDetail({ task, onClose, onPatch }: { task?: Task; onClose:()=>void; onPatch:(id:string,p:Partial<Task>)=>void }) {
  const [description,setDescription]=useState(task?.description||''); const [tags,setTags]=useState(task?.tags.join(', ')||''); if(!task)return null;
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/30" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="h-full w-full max-w-md overflow-y-auto border-l bg-background p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.16em] text-muted-foreground">Task details</p><h2 className="mt-1 text-lg font-semibold">{task.title}</h2></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-muted"><X className="h-4 w-4"/></button></div><div className="mt-5 space-y-4"><div><label className="text-xs font-semibold">Description</label><textarea value={description} onChange={e=>setDescription(e.target.value)} onBlur={()=>onPatch(task.id,{description})} placeholder="Add details…" className="mt-2 min-h-36 w-full rounded-xl border bg-card p-3 text-sm"/></div><div><label className="text-xs font-semibold">Labels</label><input value={tags} onChange={e=>setTags(e.target.value)} onBlur={()=>onPatch(task.id,{tags:tags.split(',').map(t=>t.trim().replace(/^#/,'')).filter(Boolean).slice(0,8)})} className="mt-2 h-10 w-full rounded-xl border bg-card px-3 text-sm" placeholder="study, cyber, project"/></div><div className="grid grid-cols-2 gap-2"><label className="rounded-xl border bg-card p-3 text-xs"><span className="text-muted-foreground">Status</span><select value={task.status} onChange={e=>onPatch(task.id,{status:e.target.value as Status})} className="mt-2 w-full bg-transparent font-medium outline-none">{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label className="rounded-xl border bg-card p-3 text-xs"><span className="text-muted-foreground">Priority</span><select value={task.priority} onChange={e=>onPatch(task.id,{priority:e.target.value as Priority})} className="mt-2 w-full bg-transparent font-medium outline-none">{PRIORITIES.map(p=><option key={p}>{p}</option>)}</select></label></div><label className="block rounded-xl border bg-card p-3 text-xs"><span className="text-muted-foreground">Due date</span><input type="date" value={task.date} onChange={e=>onPatch(task.id,{date:e.target.value})} className="mt-2 w-full bg-transparent font-medium outline-none"/></label></div></aside></div>;
}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-3.5"><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
