import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { AUTH_COOKIE, verifySession } from '@/lib/auth';
import { rejectCrossOrigin } from '@/lib/security';
export const runtime='nodejs';
async function okAuth(){return verifySession((await cookies()).get(AUTH_COOKIE)?.value)}
export async function GET(request:NextRequest){if(!await okAuth())return NextResponse.json({error:'Unauthorized'},{status:401});const projectId=new URL(request.url).searchParams.get('projectId')||'';if(!/^[0-9a-f-]{36}$/i.test(projectId))return NextResponse.json({error:'Invalid project id'},{status:400});try{const sb=await createSupabaseServerClient();const {data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {data,error}=await sb.from('project_tasks').select('*').eq('project_id',projectId).eq('owner_id',user.id).order('created_at',{ascending:true});if(error)throw error;return NextResponse.json(data||[],{headers:{'Cache-Control':'private,no-store'}})}catch{return NextResponse.json({error:'Unable to load tasks'},{status:500})}}
export async function POST(request:NextRequest){const blocked=rejectCrossOrigin(request);if(blocked)return blocked;if(!await okAuth())return NextResponse.json({error:'Unauthorized'},{status:401});try{const body=await request.json();const projectId=typeof body?.projectId==='string'?body.projectId:'';const title=typeof body?.title==='string'?body.title.trim().slice(0,300):'';if(!/^[0-9a-f-]{36}$/i.test(projectId)||!title)return NextResponse.json({error:'Invalid task'},{status:400});const sb=await createSupabaseServerClient();const {data:{user}}=await sb.auth.getUser();if(!user)return NextResponse.json({error:'Unauthorized'},{status:401});const {data:p}=await sb.from('projects').select('id').eq('id',projectId).eq('owner_id',user.id).maybeSingle();if(!p)return NextResponse.json({error:'Not found'},{status:404});const priority=['P0','P1','P2','P3'].includes(body.priority)?body.priority:'P2';const status=['todo','in-progress','blocked','done'].includes(body.status)?body.status:'todo';const {data,error}=await sb.from('project_tasks').insert({project_id:projectId,owner_id:user.id,title,description:typeof body.description==='string'?body.description.trim().slice(0,5000):'',priority,status,due_date:typeof body.dueDate==='string'?body.dueDate:null}).select('*').single();if(error)throw error;return NextResponse.json(data,{status:201,headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({error:'Unable to create task'},{status:500})}}
