'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Grip, Plus, RotateCcw, Search, Trash2, X } from 'lucide-react';

type Palette = 'lemon' | 'blush' | 'sky' | 'mint' | 'peach' | 'lilac';
type NoteStyle = 1 | 2 | 3 | 4 | 5;
export type StickyNote = { id:string; text:string; color:Palette; style:NoteStyle; x:number; y:number; rotation:number; created:string; updated:string; archived?:boolean };

const KEY='streamearn-planner-sticky-wall-v3';
const PALETTES:Record<Palette,{p1:string;p2:string;fold:string}>= {
  lemon:{p1:'#E9CD4E',p2:'#DDBB2E',fold:'#A98A20'}, blush:{p1:'#EC7FA6',p2:'#E66E9B',fold:'#B24A73'}, sky:{p1:'#85BCE9',p2:'#74B0E4',fold:'#4A7FB2'}, mint:{p1:'#90D18C',p2:'#7EC67C',fold:'#529A52'}, peach:{p1:'#E18B50',p2:'#DA7F41',fold:'#A85D2C'}, lilac:{p1:'#AC8FD6',p2:'#9E80CB',fold:'#7457A6'}
};
const COLORS=Object.keys(PALETTES) as Palette[];
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const safeNotes=(raw:any):StickyNote[]=>Array.isArray(raw)?raw.filter(Boolean).map((n:any)=>({id:typeof n.id==='string'?n.id:uid(),text:typeof n.text==='string'?n.text:'',color:COLORS.includes(n.color)?n.color:'lemon',style:[1,2,3,4,5].includes(n.style)?n.style:1,x:Number.isFinite(n.x)?n.x:24,y:Number.isFinite(n.y)?n.y:24,rotation:Number.isFinite(n.rotation)?n.rotation:0,created:typeof n.created==='string'?n.created:new Date().toISOString(),updated:typeof n.updated==='string'?n.updated:new Date().toISOString(),archived:Boolean(n.archived)})):[];

export default function StickyWall({compact=false}:{compact?:boolean}={}){
 const [notes,setNotes]=useState<StickyNote[]>([]); const [hydrated,setHydrated]=useState(false); const [color,setColor]=useState<Palette>('lemon'); const [style,setStyle]=useState<NoteStyle>(1); const [query,setQuery]=useState(''); const [showArchived,setShowArchived]=useState(false); const [calendar,setCalendar]=useState<string|null>(null); const [drag,setDrag]=useState<{id:string;dx:number;dy:number}|null>(null); const board=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);setNotes(safeNotes(raw?JSON.parse(raw):[]));}catch{setNotes([])}finally{setHydrated(true)}},[]);
 useEffect(()=>{if(hydrated){try{localStorage.setItem(KEY,JSON.stringify(notes))}catch{}}},[notes,hydrated]);
 useEffect(()=>{const move=(e:PointerEvent)=>{if(!drag||!board.current)return;const r=board.current.getBoundingClientRect();setNotes(v=>v.map(n=>n.id===drag.id?{...n,x:clamp(e.clientX-r.left-drag.dx,8,Math.max(8,r.width-270)),y:clamp(e.clientY-r.top-drag.dy,8,Math.max(8,r.height-270)),updated:new Date().toISOString()}:n))};const up=()=>setDrag(null);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[drag]);
 const visible=useMemo(()=>notes.filter(n=>(showArchived||!n.archived)&&n.text.toLowerCase().includes(query.toLowerCase())),[notes,query,showArchived]);
 const add=()=>{const i=notes.length;const now=new Date().toISOString();setNotes(v=>[{id:uid(),text:'',color,style,x:24+(i%4)*270,y:24+(Math.floor(i/4)%5)*260,rotation:[-2,1,-1,2,0][i%5],created:now,updated:now},...v]);setTimeout(()=>document.querySelector<HTMLTextAreaElement>('[data-new-sticky="true"]')?.focus(),20)};
 const update=(id:string,patch:Partial<StickyNote>)=>setNotes(v=>v.map(n=>n.id===id?{...n,...patch,updated:new Date().toISOString()}:n));
 const archive=(id:string)=>update(id,{archived:true}); const restore=(id:string)=>update(id,{archived:false}); const clear=()=>{if(confirm('Delete every sticky note on this device?'))setNotes([])};
 return <section className={`overflow-hidden rounded-2xl border bg-[#171210] text-[#F3E9DC] ${compact?'h-[calc(100vh-225px)] min-h-[560px]':''}`}>
   <header className="flex flex-wrap items-center gap-2 border-b border-white/10 bg-[#17110d]/90 px-3 py-2 backdrop-blur-xl"><div className="flex items-center gap-2"><div className="h-7 w-7 -rotate-6 rounded bg-gradient-to-br from-[#EFD45B] to-[#DDBB2E]"/><div><h2 className="font-serif text-xl leading-none">Sticky Wall</h2><p className="text-[9px] uppercase tracking-[.16em] text-[#9A8672]">Local • private • no AI</p></div></div><div className="ml-auto flex flex-wrap items-center gap-1.5"><div className="hidden items-center gap-1 rounded-full bg-white/[.06] px-2 py-1 sm:flex">{COLORS.map(k=><button key={k} onClick={()=>setColor(k)} aria-label={`Use ${k}`} className={`h-5 w-5 rounded-[5px] ${color===k?'ring-2 ring-[#F2C94C] ring-offset-2 ring-offset-[#171210]':''}`} style={{background:`linear-gradient(160deg,${PALETTES[k].p1},${PALETTES[k].p2})`}}/>)}</div><select value={style} onChange={e=>setStyle(Number(e.target.value) as NoteStyle)} className="rounded-full border border-white/10 bg-[#241C16] px-2.5 py-1.5 text-[11px] text-[#F3E9DC]"><option value="1">Tape</option><option value="2">Lined</option><option value="3">Grid</option><option value="4">Legal</option><option value="5">Stripe</option></select><button onClick={()=>setShowArchived(v=>!v)} className="rounded-full border border-white/10 px-2.5 py-1.5 text-[11px] text-[#C9B391]">{showArchived?'Hide archived':'Archived'}</button><button onClick={add} className="inline-flex items-center gap-1 rounded-full bg-[#F2C94C] px-3 py-1.5 text-[11px] font-semibold text-[#241C16]"><Plus className="h-3.5 w-3.5"/>New</button></div></header>
   <div className="flex items-center gap-2 border-b border-white/10 bg-[#17110d]/75 px-3 py-1.5"><div className="flex flex-1 items-center gap-2 rounded-full border border-white/10 bg-white/[.05] px-2.5 py-1.5"><Search className="h-3.5 w-3.5 text-[#9A8672]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notes…" className="w-full bg-transparent text-xs outline-none placeholder:text-[#756454]"/></div><span className="text-[10px] text-[#9A8672]">{visible.length}</span><button onClick={clear} aria-label="Clear notes" className="rounded-full p-1.5 text-[#9A8672] hover:text-red-300"><Trash2 className="h-3.5 w-3.5"/></button></div>
   <main ref={board} className={`relative overflow-auto bg-[radial-gradient(rgba(255,235,205,.08)_1px,transparent_1px)] [background-size:28px_28px] ${compact?'h-[calc(100%-95px)]':'h-[70vh] min-h-[520px]'}`}>{visible.length===0&&<div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="text-center"><div className="mx-auto mb-3 h-14 w-14 -rotate-6 rounded bg-gradient-to-br from-[#EFD45B] to-[#DDBB2E] shadow-xl"/><p className="text-sm text-[#C9B391]">{query?'No notes match your search.':'Nothing pinned yet.'}</p><p className="mt-1 text-xs text-[#756454]">Create a note and keep quick thoughts visible.</p></div></div>}{visible.map(n=><article key={n.id} onPointerDown={e=>{if((e.target as HTMLElement).closest('textarea,button'))return;const r=e.currentTarget.getBoundingClientRect();setDrag({id:n.id,dx:e.clientX-r.left,dy:e.clientY-r.top})}} className="absolute flex h-[230px] w-[230px] flex-col rounded-[3px] p-3.5 text-[#262019] shadow-[0_5px_12px_rgba(0,0,0,.4),0_25px_45px_-12px_rgba(0,0,0,.6)]" style={{left:n.x,top:n.y,transform:`rotate(${n.rotation}deg)`,background:`linear-gradient(175deg,${PALETTES[n.color].p1},${PALETTES[n.color].p2})`}}><div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-white/20 to-transparent"/>{n.style===1&&<div className="absolute -top-3 left-1/2 h-5 w-16 -translate-x-1/2 rotate-[-2deg] bg-white/30"/>}<div className="relative z-10 flex items-center justify-between"><span className="text-[8px] font-bold uppercase tracking-[.16em] opacity-50">{new Date(n.updated).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><div className="flex gap-1"><button onClick={()=>setCalendar(n.id)} className="rounded-full bg-black/10 p-1 opacity-70" title="Date"><CalendarDays className="h-3 w-3"/></button>{n.archived?<button onClick={()=>restore(n.id)} className="rounded-full bg-black/10 p-1" title="Restore"><RotateCcw className="h-3 w-3"/></button>:<button onClick={()=>archive(n.id)} className="rounded-full bg-black/10 p-1" title="Archive"><Trash2 className="h-3 w-3"/></button>}</div></div><textarea data-new-sticky={!n.text?'true':undefined} value={n.text} onChange={e=>update(n.id,{text:e.target.value})} placeholder="Write something…" className="relative z-10 mt-1 flex-1 resize-none overflow-auto bg-transparent font-serif text-[17px] leading-[1.45] outline-none placeholder:text-black/30"/><div className="relative z-10 flex items-center justify-between pt-1"><div className="flex gap-1">{COLORS.map(k=><button key={k} onClick={()=>update(n.id,{color:k})} className={`h-3 w-3 rounded-sm ${n.color===k?'ring-1 ring-black/60':''}`} style={{background:PALETTES[k].p1}}/>)}</div><Grip className="h-3.5 w-3.5 opacity-30"/></div><div className="pointer-events-none absolute -bottom-px -right-px h-7 w-7" style={{background:`linear-gradient(to top left,transparent 0 46%,rgba(255,255,255,.3) 47% 49%,${PALETTES[n.color].fold} 50%)`}}/></article>)}</main>
   {calendar&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setCalendar(null)}}><div className="w-[270px] rounded-2xl border border-white/10 bg-[#241C16] p-3 shadow-2xl"><div className="mb-2 flex items-center justify-between"><button onClick={()=>setCalendar(null)} className="rounded p-1 hover:bg-white/10"><X className="h-4 w-4"/></button><span className="text-xs">Pick a date</span><span/></div><div className="grid grid-cols-7 gap-1 text-center text-[9px] text-[#9A8672]">{['S','M','T','W','T','F','S'].map((d,i)=><span key={`${d}${i}`}>{d}</span>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{Array.from({length:31},(_,i)=><button key={i} onClick={()=>setCalendar(null)} className="h-8 rounded text-xs hover:bg-white/10">{i+1}</button>)}</div></div></div>}
 </section>
}
