'use client';
import { ArrowUpRight, BadgeDollarSign, CalendarClock, Code2 } from 'lucide-react';

type Pick={title:string;description:string;meta:string;deadline:string;reward:string;link:string;kind:string};
const picks:Pick[]=[
 {title:'Microsoft Copilot Student Ambassador',description:'Paid student ambassador program centered on AI advocacy, campus events and content. Requires full-time enrollment at an affiliated four-year university.',meta:'Microsoft · Student program',deadline:'Applications rolling from June 2026',reward:'Up to $1,500 on completion',link:'https://www.microsoft.com/en-us/microsoft-copilot/for-individuals/copilot-student-ambassador',kind:'AI + Community'},
 {title:'Zero Origin',description:'Student-only online hackathon with AI, automation, cloud, finance, health-tech and open-innovation problem tracks.',meta:'Online · Teams 2–4',deadline:'Sep 26, 2026 · 11:00 PM IST',reward:'₹2,500 cash prizes listed',link:'https://zero-origin.devpost.com/',kind:'AI + Build'},
 {title:'EC-Council HackAI Challenge @ RACEx360',description:'AI-security challenge focused on securing AI-powered enterprise systems, with red-team and defense themes.',meta:'Bengaluru · Individual registration',deadline:'Sep 10, 2026 registration close',reward:'₹1,75,000 total cash pool + CEH vouchers',link:'https://race.reva.edu.in/hackai-challenge-racex360/',kind:'AI Security'},
 {title:'FirstHack 2026',description:'Pan-India student hackathon with idea, build and pitch rounds. Open to every branch and year, including solo entries.',meta:'Online · Solo or teams 1–4',deadline:'Sep 15, 2026 · 11:59 PM IST',reward:'₹1,00,000 cash prize pool',link:'https://hackathon.firsthack.in/',kind:'Hackathon'},
];
const hash=(v:string)=>{let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const visual=(key:string)=>{const h=hash(key),a=h%360,b=(h*11)%360,s=`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 900 420'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='hsl(${a} 55% 30%)'/><stop offset='1' stop-color='hsl(${b} 50% 8%)'/></linearGradient></defs><rect width='900' height='420' fill='url(#g)'/><circle cx='${120+h%600}' cy='${80+h%220}' r='150' fill='rgba(255,255,255,.10)'/><path d='M0 330 Q220 ${250+h%100} 450 325 T900 300 V420 H0Z' fill='rgba(0,0,0,.22)'/><g stroke='rgba(255,255,255,.16)' fill='none'><circle cx='700' cy='120' r='68'/><circle cx='700' cy='120' r='30'/><path d='M90 80h250M90 100h170M90 120h210'/></g><text x='42' y='385' font-family='monospace' font-size='16' fill='rgba(255,255,255,.78)' letter-spacing='3'>CURRENT PICK</text><text x='42' y='407' font-family='monospace' font-size='10' fill='rgba(255,255,255,.48)'>${String(h).padStart(10,'0')}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(s)}`};
export function CurrentEarningPicks(){return <section className="px-4 pb-5 md:px-6"><div className="rounded-2xl border border-border/70 bg-card/70 p-4 md:p-5"><div className="flex flex-wrap items-end justify-between gap-2"><div><div className="text-[9px] font-semibold uppercase tracking-[.18em] text-accent">Verified picks · Sep 1, 2026</div><h2 className="mt-1 font-serif text-2xl tracking-tight md:text-3xl">Current ways to build, compete & earn</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-muted-foreground">Fresh opportunities with first-party or official event links. Check the eligibility and deadline on the source before applying.</p></div><div className="rounded-full border border-border bg-muted/40 px-2.5 py-1 text-[9px] text-muted-foreground">4 verified picks</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{picks.map(p=><article key={p.title} className="overflow-hidden rounded-xl border border-border bg-background/60"><img src={visual(p.title)} alt="" className="h-28 w-full object-cover" loading="lazy"/><div className="p-3"><div className="flex items-center gap-1.5 text-[9px] uppercase tracking-[.12em] text-muted-foreground"><span className="h-1.5 w-1.5 rounded-full bg-accent"/>{p.kind}</div><h3 className="mt-1.5 line-clamp-2 text-sm font-semibold">{p.title}</h3><p className="mt-1.5 line-clamp-3 text-[10px] leading-4 text-muted-foreground">{p.description}</p><div className="mt-3 space-y-1.5 text-[9px]"><div className="flex gap-2"><CalendarClock className="mt-0.5 h-3 w-3 shrink-0"/><span>{p.deadline}</span></div><div className="flex gap-2"><BadgeDollarSign className="mt-0.5 h-3 w-3 shrink-0"/><span>{p.reward}</span></div><div className="flex gap-2"><Code2 className="mt-0.5 h-3 w-3 shrink-0"/><span>{p.meta}</span></div></div><a href={p.link} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-[10px] font-medium hover:border-accent/50">Official source <ArrowUpRight className="h-3 w-3"/></a></div></article>)}</div></div></section>}
