'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ExternalLink, Grid2X2, List, Network, Newspaper, Search, Sparkles, X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { currentAIDirectory, type CurrentAICategory, type CurrentAITool } from '@/lib/current-ai-directory';
import { currentAIAdditions } from '@/lib/current-ai-additions';

const automationTools: CurrentAITool[] = [
  { name: 'n8n', url: 'https://n8n.io/', summary: 'Visual workflow automation with AI nodes, code steps and a self-hosting path.', tags: ['automation','workflow','self-hosted'], featured: true },
  { name: 'Zapier', url: 'https://zapier.com/', summary: 'Broad app automation with AI workflows, agents and MCP connectivity.', tags: ['automation','no-code','integrations'], featured: true },
  { name: 'Make', url: 'https://www.make.com/', summary: 'Visual scenarios with branching, transformations and AI workflow capabilities.', tags: ['automation','visual','workflow'] },
  { name: 'Gumloop', url: 'https://www.gumloop.com/', summary: 'AI-native workflows for research, data processing and agentic automation.', tags: ['ai-automation','agents','research'] },
  { name: 'Relevance AI', url: 'https://relevanceai.com/', summary: 'AI agents and workforces for repeatable business operations.', tags: ['agents','automation','workforce'] },
  { name: 'Lindy', url: 'https://www.lindy.ai/', summary: 'Assistant-style automation for recurring personal and business work.', tags: ['automation','assistants','agents'] },
  { name: 'Microsoft Power Automate', url: 'https://www.microsoft.com/en-us/power-platform/products/power-automate', summary: 'Enterprise workflow and desktop automation across Microsoft ecosystems.', tags: ['automation','enterprise','rpa'] },
  { name: 'UiPath', url: 'https://www.uipath.com/', summary: 'Enterprise RPA and agentic automation for UI-driven processes.', tags: ['rpa','enterprise','automation'] },
  { name: 'Relay.app', url: 'https://relay.app/', summary: 'Human-in-the-loop workflows with approvals and AI steps.', tags: ['automation','workflow','approvals'] },
];
const allDirectory = currentAIDirectory.map(c => c.id === 'automation' ? { ...c, tools: [...c.tools, ...automationTools] } : c).concat(currentAIAdditions);
const imageFor = (kind: string, id: string | number) => `https://picsum.photos/seed/streamearn-${encodeURIComponent(`${kind}-${id}`)}/1200/700`;
const logoFor = (url: string) => { try { return `${new URL(url).origin}/favicon.ico`; } catch { return ''; } };

function ToolCard({ tool, index, list }: { tool: CurrentAITool; index: number; list: boolean }) {
  const logo = logoFor(tool.url);
  return <article className={`group overflow-hidden rounded-xl border bg-background transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-md ${list ? 'flex min-h-[104px]' : ''}`}>
    <div className={`relative overflow-hidden bg-muted ${list ? 'w-28 shrink-0' : 'aspect-[16/5]'}`}><img src={imageFor('tool', `${tool.name}-${index}`)} alt="" className="h-full w-full object-cover" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent" />{tool.featured && <Badge className="absolute bottom-2 left-2 text-[9px]">Featured</Badge>}</div>
    <div className="min-w-0 flex-1 p-3"><div className="flex items-start gap-2"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border bg-card p-1.5"><img src={logo} alt="" className="h-full w-full object-contain" onError={e => { e.currentTarget.style.display='none'; }} /></div><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold group-hover:text-primary">{tool.name}</h3><p className="mt-0.5 line-clamp-2 text-[11px] leading-4 text-muted-foreground">{tool.summary}</p></div><ExternalLink className="h-3.5 w-3.5 shrink-0 text-muted-foreground" /></div><div className="mt-2 flex flex-wrap gap-1">{tool.tags.slice(0, 3).map(tag => <Badge key={tag} variant="outline" className="px-1.5 py-0 text-[9px]">{tag}</Badge>)}</div><a href={tool.url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex w-full items-center justify-center gap-1 rounded-md border px-2 py-1.5 text-[11px] font-medium transition hover:bg-primary hover:text-primary-foreground">Open official site <ExternalLink className="h-3 w-3" /></a></div>
  </article>;
}

export function EnhancedAiToolsContent() {
  const [query, setQuery] = useState('');
  const [view, setView] = useState<'grid'|'list'>('grid');
  const normalized = query.trim().toLowerCase();
  const categories = useMemo(() => allDirectory.map(c => ({ ...c, tools: c.tools.filter(t => !normalized || [t.name, t.summary, ...t.tags, c.name, c.description].join(' ').toLowerCase().includes(normalized)) })).filter(c => c.tools.length), [normalized]);
  const count = allDirectory.reduce((n,c)=>n+c.tools.length,0);
  const visibleCount = categories.reduce((n,c) => n+c.tools.length,0);
  return <div className="min-h-[calc(100vh-4rem)] overflow-x-hidden bg-background"><main className="mx-auto w-full max-w-[1500px] px-3 py-5 md:px-6 md:py-7"><div className="space-y-5">
    <section className="relative isolate overflow-hidden rounded-2xl border bg-card p-5 md:p-7"><div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden"><div className="mind-grid"/><div className="mind-orbit orbit-one"/><div className="mind-orbit orbit-two"/><div className="mind-node node-a">Research</div><div className="mind-node node-b">Build</div><div className="mind-node node-c">Automate</div><div className="mind-node node-d">Evaluate</div><div className="mind-node node-e">Create</div><div className="mind-center"><Network className="h-4 w-4"/> AI</div></div><div className="relative max-w-3xl space-y-4"><div className="flex flex-wrap gap-1.5"><Badge><Sparkles className="mr-1 h-3 w-3"/>Updated daily</Badge><Badge variant="secondary">{allDirectory.length} categories</Badge><Badge variant="secondary">{count}+ tools</Badge></div><div><h1 className="text-3xl font-semibold tracking-tight md:text-5xl">AI Intelligence</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground md:text-base">Explore the current AI ecosystem through one compact search. Find tools by name, category, capability, workflow or use case.</p></div><div className="relative max-w-2xl"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search AI tools, categories, automation, agents, research..." className="h-11 rounded-full bg-background/90 pl-10 pr-10" aria-label="Search AI tools and categories" />{query && <Button size="icon" variant="ghost" onClick={() => setQuery('')} className="absolute right-1 top-1/2 h-9 w-9 -translate-y-1/2 rounded-full" aria-label="Clear search"><X className="h-4 w-4"/></Button>}</div>{normalized && <div className="flex flex-wrap gap-1.5 text-[11px] text-muted-foreground"><span>Searching across:</span>{categories.slice(0, 5).map(c => <Badge key={c.id} variant="outline" className="text-[10px]">{c.name}</Badge>)}{categories.length > 5 && <span>+{categories.length - 5} categories</span>}</div>}</div></section>
    <div className="flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>{visibleCount} shown</span><div className="flex items-center gap-2"><div className="flex gap-1 rounded-md border bg-card p-0.5"><Button size="sm" variant={view==='grid'?'default':'ghost'} onClick={()=>setView('grid')} aria-label="Grid view" className="h-7"><Grid2X2 className="h-3.5 w-3.5" /></Button><Button size="sm" variant={view==='list'?'default':'ghost'} onClick={()=>setView('list')} aria-label="List view" className="h-7"><List className="h-3.5 w-3.5" /></Button></div><Link href="/news" className="hidden items-center gap-1.5 text-primary hover:underline md:inline-flex"><Newspaper className="h-3.5 w-3.5"/>Latest AI News</Link></div></div>
    <div className="space-y-6">{categories.map((category, categoryIndex) => <CategorySection key={category.id} category={category} index={categoryIndex} list={view==='list'} />)}</div>
    {!categories.length && <div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground">No tools or categories matched “{query}”. Try a capability such as automation, coding, research or agents.</div>}
  </div></main><style jsx>{`@keyframes drift{0%,100%{transform:translate3d(0,0,0)}50%{transform:translate3d(14px,-10px,0)}}@keyframes spinSlow{to{transform:rotate(360deg)}}.mind-grid{position:absolute;inset:0;background-image:linear-gradient(rgba(120,120,140,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(120,120,140,.08) 1px,transparent 1px);background-size:28px 28px;mask-image:radial-gradient(circle at 70% 50%,black,transparent 68%)}.mind-orbit{position:absolute;border:1px solid rgba(120,120,140,.18);border-radius:999px;animation:spinSlow 26s linear infinite}.orbit-one{width:360px;height:190px;right:5%;top:8%;transform:rotate(-12deg)}.orbit-two{width:280px;height:150px;right:9%;top:18%;transform:rotate(24deg);animation-direction:reverse}.mind-node{position:absolute;border:1px solid rgba(120,120,140,.22);background:rgba(20,20,24,.7);backdrop-filter:blur(6px);border-radius:999px;padding:5px 10px;font-size:10px;color:rgba(255,255,255,.72);animation:drift 5s ease-in-out infinite}.node-a{right:25%;top:15%}.node-b{right:8%;top:31%;animation-delay:.6s}.node-c{right:31%;bottom:15%;animation-delay:1.2s}.node-d{right:13%;bottom:11%;animation-delay:1.8s}.node-e{right:38%;top:34%;animation-delay:2.4s}.mind-center{position:absolute;right:18%;top:44%;display:flex;align-items:center;gap:5px;border:1px solid rgba(255,255,255,.28);background:rgba(20,20,24,.88);border-radius:999px;padding:8px 13px;font-size:12px;font-weight:600;box-shadow:0 0 40px rgba(255,255,255,.08)}@media(max-width:768px){.mind-grid,.mind-orbit,.mind-node,.mind-center{display:none}}`}</style></div>;
}

function CategorySection({ category, index, list }: { category: CurrentAICategory; index: number; list: boolean }) {
  return <section id={category.id} className="overflow-hidden rounded-xl border bg-card"><div className="relative h-24 overflow-hidden"><img src={imageFor('category', category.id)} alt="" className="h-full w-full object-cover" loading="lazy" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/35 to-transparent" /><div className="absolute bottom-3 left-4 right-4 text-white"><h2 className="text-lg font-semibold">{category.name}</h2><p className="mt-0.5 max-w-3xl truncate text-[11px] text-white/75">{category.description}</p></div></div><div className={list ? 'space-y-2 p-3' : 'grid gap-3 p-3 sm:grid-cols-2 xl:grid-cols-3'}>{category.tools.map((tool, toolIndex) => <ToolCard key={`${tool.name}-${toolIndex}`} tool={tool} index={index * 1000 + toolIndex} list={list} />)}</div></section>;
}
