'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { CalendarDays, Grip, MoreHorizontal, Plus, Search, Trash2 } from 'lucide-react';

type Palette='lemon'|'blush'|'sky'|'mint'|'peach'|'lilac';
type PaperStyle='plain'|'lined'|'grid'|'legal'|'stripe';
type Sticky={id:string;pageId:string;text:string;color:Palette;style:PaperStyle;x:number;y:number;rotation:number;done:boolean;created:string;updated:string;archived:boolean};
type Page={id:string;title:string;created:string;updated:string};
type Persisted={pages:Page[];notes:Sticky[];activePageId:string};
const KEY='streamearn-planner-sticky-v4';
const colors:Record<Palette,{a:string;b:string;fold:string}>={lemon:{a:'#E9CD4E',b:'#DDBB2E',fold:'#A98A20'},blush:{a:'#EC7FA6',b:'#E66E9B',fold:'#B24A73'},sky:{a:'#85BCE9',b:'#74B0E4',fold:'#4A7FB2'},mint:{a:'#90D18C',b:'#7EC67C',fold:'#529A52'},peach:{a:'#E18B50',b:'#DA7F41',fold:'#A85D2C'},lilac:{a:'#AC8FD6',b:'#9E80CB',fold:'#7457A6'}};
const papers:PaperStyle[]=['plain','lined','grid','legal','stripe'];
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;const now=()=>new Date().toISOString();
function makePage(title:string):Page{const t=now();return{id:uid(),title,created:t,updated:t}}
function load():Persisted{if(typeof window==='undefined')return{pages:[makePage('Main')],notes:[],activePageId:''};try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(!raw||typeof raw!=='object')return{pages:[makePage('Main')],notes:[],activePageId:''};const pages=Array.isArray(raw.pages)?raw.pages.filter((p:any)=>p&&typeof p.id==='string').map((p:any)=>({...p,title:typeof p.title==='string'&&p.title.trim()?p.title.trim():'Untitled'})):[];const safePages=pages.length?pages:[makePage('Main')];const pageIds=new Set(safePages.map(p=>p.id));const notes=Array.isArray(raw.notes)?raw.notes.filter((n:any)=>n&&typeof n==='object').map((n:any,i:number)=>({id:typeof n.id==='string'?n.id:uid(),pageId:pageIds.has(n.pageId)?n.pageId:safePages[0].id,text:typeof n.text==='string'?n.text:'',color:n.color in colors?n.color:'lemon',style:papers.includes(n.style)?n.style:'plain',x:Number.isFinite(n.x)?n.x:25+(i%4)*285,y:Number.isFinite(n.y)?n.y:25+(Math.floor(i/4)%4)*275,rotation:Number.isFinite(n.rotation)?n.rotation:[-2,1,-1,2,0][i%5],done:Boolean(n.done),created:typeof n.created==='string'?n.created:now(),updated:typeof n.updated==='string'?n.updated:now(),archived:Boolean(n.archived)})):[];return{pages:safePages,notes,activePageId:pageIds.has(raw.activePageId)?raw.activePageId:safePages[0].id}}catch{return{pages:[makePage('Main')],notes:[],activePageId:''}}}
export function PlannerStickyWorkspace(){const[data,setData]=useState<Persisted>(()=>({pages:[],notes:[],activePageId:''}));const[ready,setReady]=useState(false);const[q,setQ]=useState('');const[menu,setMenu]=useState<string|null>(null);const[drag,setDrag]=useState<{id:string;dx:number;dy:number}|null>(null);const board=useRef<HTMLDivElement>(null);useEffect(()=>{const d=load();if(!d.activePageId)d.activePageId=d.pages[0]?.id||'';setData(d);setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify(data))},[data,ready]);useEffect(()=>{const move=(e:PointerEvent)=>{if(!drag||!board.current)return;const r=board.current.getBoundingClientRect();setData(d=>({...d,notes:d.notes.map(n=>n.id===drag.id?{...n,x:Math.max(8,Math.min(e.clientX-r.left-drag.dx,Math.max(8,r.width-270))),y:Math.max(8,Math.min(e.clientY-r.top-drag.dy,Math.max(8,r.height-255))),updated:now()}:n)}))};const up=()=>setDrag(null);window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[drag]);
const page=data.pages.find(p=>p.id===data.activePageId)||data.pages[0];const notes=useMemo(()=>data.notes.filter(n=>n.pageId===page?.id&&!n.archived&&n.text.toLowerCase().includes(q.toLowerCase())),[data.notes,page?.id,q]);
const addPage=()=>{const p=makePage(`Page ${data.pages.length+1}`);setData(d=>({...d,pages:[...d.pages,p],activePageId:p.id}));};
const rename=(id:string)=>{const title=window.prompt('Page name',data.pages.find(p=>p.id===id)?.title||'Untitled');if(title?.trim())setData(d=>({...d,pages:d.pages.map(p=>p.id===id?{...p,title:title.trim(),updated:now()}:p)}));setMenu(null)};
const deletePage=(id:string)=>{if(data.pages.length<=1)return;if(!window.confirm('Delete this page and its notes?'))return;setData(d=>{const pages=d.pages.filter(p=>p.id!==id);return{pages,notes:d.notes.filter(n=>n.pageId!==id),activePageId:d.activePageId===id?pages[0].id:d.activePageId}});setMenu(null)};
const addNote=()=>{if(!page)return;const i=notes.length;const t=now();setData(d=>({...d,notes:[...d.notes,{id:uid(),pageId:page.id,text:'',color:'lemon',style:'plain',x:25+(i%4)*285,y:25+(Math.floor(i/4)%4)*275,rotation:[-2,1,-1,2,0][i%5],done:false,created:t,updated:t,archived:false}],pages:d.pages.map(p=>p.id===page.id?{...p,updated:t}:p)}))};
if(!ready)return <div className="rounded-2xl border p-6 text-sm text-muted-foreground">Loading Sticky Wall…</div>;
return <section className="overflow-hidden rounded-2xl border bg-[#171210] text-[#F3E9DC]"><div className="flex flex-wrap items-center gap-2 border-b border-white/10 bg-[#1c1510] px-3 py-2"><div className="flex min-w-0 items-center gap-1.5 overflow-x-auto">{data.pages.map(p=><div key={p.id} className="relative flex items-center"><button onClick={()=>setData(d=>({...d,activePageId:p.id}))} className={`rounded-lg px-3 py-1.5 text-xs ${p.id===page?.id?'bg-[#F2C94C] text-[#241C16] font-semibold':'text-[#C9B391] hover:bg-white/10'}`}>{p.title}</button><button onClick={()=>setMenu(menu===p.id?null:p.id)} className="rounded p-1 text-[#8f7d6b] hover:bg-white/10"><MoreHorizontal className="h-3.5 w-3.5"/></button>{menu===p.id&&<div className="absolute left-0 top-9 z-30 w-32 rounded-lg border border-white/10 bg-[#241C16] p-1 shadow-xl"><button onClick={()=>rename(p.id)} className="block w-full rounded px-2 py-1.5 text-left text-xs hover:bg-white/10">Rename</button><button onClick={()=>deletePage(p.id)} className="block w-full rounded px-2 py-1.5 text-left text-xs text-red-200 hover:bg-red-500/10">Delete</button></div>}</div>)}<button onClick={addPage} className="inline-flex items-center gap-1 rounded-lg border border-white/10 px-2.5 py-1.5 text-xs text-[#C9B391] hover:bg-white/10"><Plus className="h-3 w-3"/>Page</button></div><div className="ml-auto flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-white/10 bg-white/[.04] px-3 py-1.5 sm:flex"><Search className="h-3.5 w-3.5 text-[#9A8672]"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-36 bg-transparent text-xs outline-none placeholder:text-[#756454]" placeholder="Search page…"/></div><button onClick={addNote} className="inline-flex items-center gap-1.5 rounded-lg bg-[#F2C94C] px-3 py-1.5 text-xs font-semibold text-[#241C16]"><Plus className="h-3.5 w-3.5"/>Sticky</button></div></div><div ref={board} className="relative h-[600px] overflow-auto bg-[radial-gradient(rgba(255,235,205,.08)_1px,transparent_1px)] [background-size:28px_28px] p-2">{notes.length===0&&<div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="mx-auto mb-3 h-14 w-14 -rotate-6 rounded bg-[#E9CD4E] shadow-xl"/><p className="text-sm text-[#C9B391]">This page is empty</p></div></div>}{notes.map(n=><StickyNoteCard key={n.id} note={n} patch={(p)=>setData(d=>({...d,notes:d.notes.map(x=>x.id===n.id?{...x,...p,updated:now()}:x)}))} startDrag={e=>{if((e.target as HTMLElement).closest('textarea,button,select,input'))return;const r=e.currentTarget.getBoundingClientRect();setDrag({id:n.id,dx:e.clientX-r.left,dy:e.clientY-r.top})}}/> )}</div></section>}
function StickyNoteCard({note,patch,startDrag}:{note:Sticky;patch:(p:Partial<Sticky>)=>void;startDrag:(e:React.PointerEvent<HTMLDivElement>)=>void}){const p=colors[note.color]||colors.lemon;const pattern=note.style==='lined'?'bg-[repeating-linear-gradient(transparent_0_25px,rgba(0,0,0,.12)_25px_26px)]':note.style==='grid'?'bg-[radial-gradient(rgba(0,0,0,.14)_1px,transparent_1.4px)] [background-size:14px_14px]':note.style==='legal'?'bg-[linear-gradient(90deg,transparent_30px,rgba(217,72,15,.4)_30px_31.5px,transparent_31.5px)]':note.style==='stripe'?'bg-[repeating-linear-gradient(45deg,rgba(255,255,255,.1)_0_14px,transparent_14px_28px)]':'';return <article onPointerDown={startDrag} className="absolute flex h-[250px] w-[250px] flex-col rounded-[3px] p-4 text-[#262019] shadow-[0_5px_12px_rgba(0,0,0,.4),0_25px_45px_-12px_rgba(0,0,0,.6)]" style={{left:note.x,top:note.y,transform:`rotate(${note.rotation}deg)`,background:`linear-gradient(175deg,${p.a},${p.b})`}}><div className="relative z-10 flex items-center justify-between"><label className="flex items-center gap-1 text-[9px] font-bold uppercase tracking-[.15em] opacity-60"><input type="checkbox" checked={note.done} onChange={e=>patch({done:e.target.checked})} className="h-3.5 w-3.5"/>Done</label><div className="flex items-center gap-1"><select value={note.color} onChange={e=>patch({color:e.target.value as Palette})} className="w-16 rounded border border-black/10 bg-black/5 p-0.5 text-[9px]"><option value="lemon">Yellow</option><option value="blush">Pink</option><option value="sky">Blue</option><option value="mint">Green</option><option value="peach">Orange</option><option value="lilac">Purple</option></select><select value={note.style} onChange={e=>patch({style:e.target.value as PaperStyle})} className="w-16 rounded border border-black/10 bg-black/5 p-0.5 text-[9px]">{papers.map(s=><option key={s} value={s}>{s}</option>)}</select></div></div><textarea value={note.text} onChange={e=>patch({text:e.target.value})} placeholder="Write something…" className={`relative z-10 mt-2 min-h-0 flex-1 resize-none overflow-auto bg-transparent font-serif text-[18px] leading-[1.45] outline-none placeholder:text-black/35 ${pattern} ${note.done?'line-through opacity-60':''}`}/><div className="relative z-10 mt-2 flex items-center justify-between"><span className="text-[9px] uppercase tracking-wider opacity-40">{new Date(note.updated).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><Grip className="h-3.5 w-3.5 opacity-30"/></div><div className="pointer-events-none absolute -bottom-px -right-px h-7 w-7" style={{background:`linear-gradient(to top left,transparent 0 46%,rgba(255,255,255,.3) 47% 49%,${p.fold} 50%)`}}/></article>}
