'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, FileText, Flag, ListTodo, Plus, Search, StickyNote, Target, X } from 'lucide-react';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';
import { PlannerStickyWorkspace } from '@/components/planner-sticky-workspace';
import { createClient } from '@/lib/supabase/client';

type Tab='today'|'week'|'calendar'|'tasks'|'notes'|'sticky'|'progress';
type Status='To do'|'In progress'|'Waiting'|'Blocked'|'Done';
type Priority='None'|'Low'|'Medium'|'High';
type Task={id:string;title:string;description:string;date:string;status:Status;priority:Priority;done:boolean;tags:string[];order:number;deleted:boolean;updated:string};
type Note={id:string;title:string;text:string;date:string;updated:string};
const statusDb:Record<Status,string>={'To do':'todo','In progress':'in_progress','Waiting':'waiting','Blocked':'blocked','Done':'done'};
const statusUi:Record<string,Status>={todo:'To do',in_progress:'In progress',waiting:'Waiting',blocked:'Blocked',done:'Done'};
const priorityDb:Record<Priority,string>={None:'none',Low:'low',Medium:'medium',High:'high'};
const priorityUi:Record<string,Priority>={none:'None',low:'Low',medium:'Medium',high:'High'};
const fresh=()=>({tasks:[] as Task[],notes:[] as Note[]});
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const today=()=>new Date().toISOString().slice(0,10);
const dateObj=(v:string)=>new Date(`${v}T12:00:00`);
const shift=(v:string,n:number)=>{const d=dateObj(v);d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const month=(v:string)=>{const d=dateObj(v);d.setDate(1);const first=d.getDay(),count=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return Array.from({length:42},(_,i)=>{const n=i-first+1;return n<1||n>count?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`})};

export function PlannerCloud(){
 const db=useMemo(()=>createClient(),[]); const [store,setStore]=useState(fresh); const [tab,setTab]=useState<Tab>('today'); const [date,setDate]=useState(today()); const [title,setTitle]=useState(''); const [query,setQuery]=useState(''); const [status,setStatus]=useState<'All'|Status>('All'); const [priority,setPriority]=useState<'All'|Priority>('All'); const [notesTitle,setNotesTitle]=useState(''); const [notesText,setNotesText]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(true); const [sync,setSync]=useState<'syncing'|'saved'|'error'>('syncing');
 const migrate=async(userId:string)=>{try{const raw=JSON.parse(localStorage.getItem('streamearn-planner-v9')||'null');if(!raw)return;const tasks=Array.isArray(raw.tasks)?raw.tasks:[];const notes=Array.isArray(raw.notes)?raw.notes:[];if(tasks.length){const rows=tasks.filter((x:any)=>x?.title).map((x:any,i:number)=>({owner_id:userId,title:String(x.title).trim(),description:typeof x.description==='string'?x.description:'',due_date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:null,status:statusDb[x.status as Status]||'todo',priority:priorityDb[x.priority as Priority]||'none',tags:Array.isArray(x.tags)?x.tags.filter((t:any)=>typeof t==='string').slice(0,8):[],sort_order:Number.isFinite(x.order)?x.order:i,archived:Boolean(x.deleted)}));const {data:existing}=await db.from('planner_tasks').select('title,due_date').eq('owner_id',userId);const keys=new Set((existing||[]).map((x:any)=>`${x.title}|${x.due_date||''}`));const freshRows=rows.filter((x:any)=>!keys.has(`${x.title}|${x.due_date||''}`));if(freshRows.length)await db.from('planner_tasks').insert(freshRows)}if(notes.length){const rows=notes.filter((x:any)=>typeof x.text==='string'&&x.text.trim()).map((x:any)=>({owner_id:userId,title:typeof x.title==='string'&&x.title.trim()?x.title.trim():'Untitled note',body:x.text.trim(),note_date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:today()}));const {data:existing}=await db.from('planner_notes').select('title,body,note_date').eq('owner_id',userId);const keys=new Set((existing||[]).map((x:any)=>`${x.title}|${x.body}|${x.note_date}`));const freshRows=rows.filter((x:any)=>!keys.has(`${x.title}|${x.body}|${x.note_date}`));if(freshRows.length)await db.from('planner_notes').insert(freshRows)}localStorage.setItem('streamearn-planner-cloud-migrated','1')}catch{setSync('error')}};
 const load=async()=>{setLoading(true);setSync('syncing');const {data:{user}}=await db.auth.getUser();if(!user){setLoading(false);setSync('error');return}if(localStorage.getItem('streamearn-planner-cloud-migrated')!=='1')await migrate(user.id);const [tr,nr]=await Promise.all([db.from('planner_tasks').select('*').eq('owner_id',user.id).order('sort_order',{ascending:true}),db.from('planner_notes').select('*').eq('owner_id',user.id).order('note_date',{ascending:false})]);if(tr.error||nr.error){setSync('error')}else{setStore({tasks:(tr.data||[]).map((x:any)=>({id:x.id,title:x.title,description:x.description||'',date:x.due_date||today(),status:statusUi[x.status]||'To do',priority:priorityUi[x.priority]||'None',done:x.status==='done',tags:Array.isArray(x.tags)?x.tags:[],order:x.sort_order||0,deleted:Boolean(x.archived),updated:x.updated_at})),notes:(nr.data||[]).map((x:any)=>({id:x.id,title:x.title,text:x.body,date:x.note_date,updated:x.updated_at}))});setSync('saved')}setLoading(false)};
 useEffect(()=>{void load()},[]);
 const active=useMemo(()=>store.tasks.filter(t=>!t.deleted),[store.tasks]); const archived=useMemo(()=>store.tasks.filter(t=>t.deleted),[store.tasks]); const completed=active.filter(t=>t.done).length; const percent=active.length?Math.round(completed/active.length*100):0; const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return active.filter(t=>(!q||`${t.title} ${t.description} ${t.tags.join(' ')} ${t.status} ${t.priority}`.toLowerCase().includes(q))&&(status==='All'||t.status===status)&&(priority==='All'||t.priority===priority))},[active,query,status,priority]); const day=filtered.filter(t=>t.date===date); const week=Array.from({length:7},(_,i)=>shift(date,i)); const days=month(date);
 const save=async(fn:()=>Promise<void>)=>{setSync('syncing');try{await fn();setSync('saved')}catch{setSync('error')}};
 const addTask=async()=>{const t=title.trim();if(!t)return;const {data:{user}}=await db.auth.getUser();if(!user){setSync('error');return}const order=active.reduce((m,x)=>Math.max(m,x.order),-1)+1;await save(async()=>{const {data,error}=await db.from('planner_tasks').insert({owner_id:user.id,title:t,due_date:date,status:'todo',priority:'none',tags:[],sort_order:order}).select('*').single();if(error)throw error;if(data)setStore(s=>({...s,tasks:[...s.tasks,{id:data.id,title:data.title,description:'',date:data.due_date||today(),status:'To do',priority:'None',done:false,tags:[],order:data.sort_order||order,deleted:false,updated:data.updated_at}]}))});setTitle('')};
 const patch=async(t:Task,p:Partial<Task>)=>{const next={...t,...p,done:p.status==='Done'?true:p.status?false:t.done};setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===t.id?next:x)}));await save(async()=>{const {error}=await db.from('planner_tasks').update({title:next.title,description:next.description,due_date:next.date,status:statusDb[next.status],priority:priorityDb[next.priority],tags:next.tags,sort_order:next.order,archived:next.deleted}).eq('id',t.id).eq('owner_id',(await db.auth.getUser()).data.user?.id||'');if(error)throw error})};
 const addNote=async()=>{if(!notesText.trim())return;const user=(await db.auth.getUser()).data.user;if(!user){setSync('error');return}await save(async()=>{const {data,error}=await db.from('planner_notes').insert({owner_id:user.id,title:notesTitle.trim()||'Untitled note',body:notesText.trim(),note_date:date}).select('*').single();if(error)throw error;if(data)setStore(s=>({...s,notes:[{id:data.id,title:data.title,text:data.body,date:data.note_date,updated:data.updated_at},...s.notes]}))});setNotesTitle('');setNotesText('')};
 if(loading)return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen bg-background p-5"><div className="rounded-xl border bg-card p-5 text-sm text-muted-foreground">Loading Planner…</div></main></SidebarInset></SidebarProvider>;
 return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen w-full min-w-0 overflow-x-hidden bg-background"><div className="w-full min-w-0 px-4 py-4 sm:px-5 lg:px-7"><header className="mb-3 flex items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight">Planner</h1><p className="mt-0.5 text-xs text-muted-foreground">Tasks, dates, notes and your Sticky Wall.</p></div><div className="flex items-center gap-2"><span className={`hidden text-[10px] sm:inline ${sync==='saved'?'text-emerald-500':sync==='error'?'text-red-400':'text-muted-foreground'}`}>{sync==='saved'?'Saved to cloud':sync==='error'?'Sync needs attention':'Saving…'}</span><button className="rounded-lg border p-2 hover:bg-muted" onClick={()=>setDate(shift(date,-1))}><ChevronLeft className="h-4 w-4"/></button><button className="rounded-lg border px-3 py-2 text-xs" onClick={()=>setDate(today())}>Today</button><button className="rounded-lg border p-2 hover:bg-muted" onClick={()=>setDate(shift(date,1))}><ChevronRight className="h-4 w-4"/></button></div></header><nav className="mb-3 flex min-w-0 flex-wrap gap-1 border-b pb-2">{([['today','Today',ListTodo],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',Check],['notes','Notes',FileText],['sticky','Sticky Wall',StickyNote],['progress','Progress',Target]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</nav>
 {tab==='today'&&<section className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_230px]"><div className="rounded-xl border bg-card"><div className="border-b p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{date===today()?'Today':dateObj(date).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h2><p className="mt-1 text-xs text-muted-foreground">Focus on what needs to be finished.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-[11px]">{day.filter(t=>!t.done).length} pending</span></div><form onSubmit={e=>{e.preventDefault();void addTask()}} className="mt-3 flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} className="h-9 min-w-0 flex-1 rounded-lg border bg-background px-3 text-sm" placeholder="Add a task…"/><button className="h-9 rounded-lg bg-foreground px-3 text-xs font-semibold text-background"><Plus className="inline h-4 w-4"/> Add</button></form></div><TaskList tasks={day} onPatch={patch}/></div><aside className="grid grid-cols-2 gap-2 lg:grid-cols-1"><Metric label="Today" value={String(active.filter(t=>t.date===today()).length)}/><Metric label="Overdue" value={String(active.filter(t=>t.date<today()&&!t.done).length)}/><Metric label="High priority" value={String(active.filter(t=>t.priority==='High'&&!t.done).length)}/><Metric label="Completion" value={`${percent}%`}/></aside></section>}
 {tab==='week'&&<section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{week.map(d=><button key={d} onClick={()=>{setDate(d);setTab('today')}} className="min-h-28 rounded-xl border bg-card p-3 text-left"><p className="text-xs font-semibold">{dateObj(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[10px] text-muted-foreground">{d}</p><div className="mt-2 space-y-1">{active.filter(t=>t.date===d).slice(0,5).map(t=><div key={t.id} className="truncate rounded border px-2 py-1 text-[10px]">{t.done?'✓':'○'} {t.title}</div>)}</div></button>)}</section>}
 {tab==='calendar'&&<section className="overflow-hidden rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-3"><h2 className="font-semibold">{dateObj(date).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><div className="flex gap-1"><button onClick={()=>setDate(shift(date,-30))} className="rounded border p-1.5"><ChevronLeft className="h-4 w-4"/></button><button onClick={()=>setDate(today())} className="rounded border px-2 text-xs">Today</button><button onClick={()=>setDate(shift(date,30))} className="rounded border p-1.5"><ChevronRight className="h-4 w-4"/></button></div></div><div className="grid grid-cols-7">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div key={d} className="border-b border-r bg-muted/30 p-2 text-center text-[9px] font-semibold">{d}</div>)}{days.map((d,i)=>d?<button key={d+i} onClick={()=>{setDate(d);setTab('today')}} className="min-h-20 border-b border-r p-2 text-left align-top"><span className="text-xs font-semibold">{dateObj(d).getDate()}</span>{active.filter(t=>t.date===d).slice(0,2).map(t=><div key={t.id} className="mt-1 truncate rounded border px-1 py-0.5 text-[8px]">{t.title}</div>)}</button>:<div key={i} className="min-h-20 border-b border-r bg-muted/10"/>)}</div></section>}
 {tab==='tasks'&&<section className="space-y-3"><div className="rounded-xl border bg-card p-3"><div className="grid gap-2 lg:grid-cols-[minmax(0,1fr)_auto_auto]"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-9 w-full rounded-lg border bg-background pl-9 text-xs" placeholder="Search tasks…"/></div><select value={status} onChange={e=>setStatus(e.target.value as any)} className="h-9 rounded-lg border bg-background px-2 text-xs"><option>All</option>{(['To do','In progress','Waiting','Blocked','Done'] as Status[]).map(x=><option key={x}>{x}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value as any)} className="h-9 rounded-lg border bg-background px-2 text-xs"><option>All</option>{(['None','Low','Medium','High'] as Priority[]).map(x=><option key={x}>{x}</option>)}</select></div></div><div className="rounded-xl border bg-card"><TaskList tasks={filtered} onPatch={patch}/></div>{archived.length>0&&<details className="rounded-xl border bg-card"><summary className="cursor-pointer p-3 text-xs">Archived ({archived.length})</summary><div className="divide-y border-t">{archived.map(t=><div key={t.id} className="flex items-center gap-3 p-3 text-xs"><span className="flex-1 truncate">{t.title}</span><button className="text-primary" onClick={()=>void patch(t,{deleted:false})}>Restore</button></div>)}</div></details>}</section>}
 {tab==='notes'&&<section className="grid gap-3 lg:grid-cols-[320px_minmax(0,1fr)]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Notes</h2><input value={notesTitle} onChange={e=>setNotesTitle(e.target.value)} className="mt-3 h-9 w-full rounded-lg border bg-background px-3 text-sm" placeholder="Title"/><textarea value={notesText} onChange={e=>setNotesText(e.target.value)} className="mt-2 min-h-40 w-full rounded-lg border bg-background p-3 text-sm" placeholder="Write something…"/><button onClick={()=>void addNote()} className="mt-2 rounded-lg bg-foreground px-3 py-2 text-xs font-semibold text-background">Save note</button></div><div className="rounded-xl border bg-card p-4"><div className="flex justify-between"><h2 className="font-semibold">Saved notes</h2><span className="text-xs text-muted-foreground">{store.notes.length}</span></div><div className="mt-3 space-y-2">{store.notes.map(n=><article key={n.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><div><h3 className="text-sm font-medium">{n.title}</h3><span className="text-[10px] text-muted-foreground">{n.date}</span></div><button onClick={()=>void save(async()=>{const {error}=await db.from('planner_notes').delete().eq('id',n.id);if(error)throw error;setStore(s=>({...s,notes:s.notes.filter(x=>x.id!==n.id)}))})}><X className="h-4 w-4"/></button></div><p className="mt-2 whitespace-pre-wrap text-xs text-muted-foreground">{n.text}</p></article>)}</div></div></section>}
 {tab==='sticky'&&<PlannerStickyWorkspace/>}
 {tab==='progress'&&<section className="space-y-3"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Active" value={String(active.length)}/><Metric label="Completed" value={String(completed)}/><Metric label="Completion" value={`${percent}%`}/><Metric label="Blocked" value={String(active.filter(t=>t.status==='Blocked').length)}/></div><div className="rounded-xl border bg-card p-4"><div className="flex justify-between"><h2 className="font-semibold">Progress</h2><span className="text-xs text-muted-foreground">{completed} of {active.length}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-foreground" style={{width:`${percent}%`}}/></div></div></section>}
 </div></main></SidebarInset></SidebarProvider>
}
function TaskList({tasks,onPatch}:{tasks:Task[];onPatch:(t:Task,p:Partial<Task>)=>Promise<void>}){if(!tasks.length)return <p className="py-12 text-center text-sm text-muted-foreground">No tasks match this view.</p>;return <div className="divide-y">{tasks.map(t=><div key={t.id} className="flex items-start gap-3 p-3 sm:p-4"><button onClick={()=>void onPatch(t,{status:t.done?'To do':'Done'})}>{t.done?<span className="grid h-5 w-5 place-items-center rounded-full bg-primary text-primary-foreground"><Check className="h-3 w-3"/></span>:<span className="block h-5 w-5 rounded-full border-2 border-muted-foreground/40"/>}</button><div className="min-w-0 flex-1"><p className={`truncate text-sm font-medium ${t.done?'line-through text-muted-foreground':''}`}>{t.title}</p>{t.description&&<p className="mt-0.5 line-clamp-1 text-[11px] text-muted-foreground">{t.description}</p>}<div className="mt-1.5 flex flex-wrap gap-1.5"><select value={t.status} onChange={e=>void onPatch(t,{status:e.target.value as Status})} className="h-6 rounded border bg-background px-1.5 text-[10px]">{(['To do','In progress','Waiting','Blocked','Done'] as Status[]).map(x=><option key={x}>{x}</option>)}</select><select value={t.priority} onChange={e=>void onPatch(t,{priority:e.target.value as Priority})} className="h-6 rounded border bg-background px-1.5 text-[10px]">{(['None','Low','Medium','High'] as Priority[]).map(x=><option key={x}>{x}</option>)}</select><input type="date" value={t.date} onChange={e=>void onPatch(t,{date:e.target.value})} className="h-6 rounded border bg-background px-1.5 text-[10px]"/></div></div><button onClick={()=>void onPatch(t,{deleted:true})} className="rounded p-1 text-muted-foreground hover:text-red-500" title="Archive"><span className="sr-only">Archive</span><span>×</span></button></div>)}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-card p-3.5"><p className="text-[10px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
