'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight, CheckCircle2, CircleAlert, ExternalLink, Flag, ListChecks, Plus, RefreshCw, Rocket, Target, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

type Project={id:string;name:string;description:string;people:string[];organization:string;role:string;priority:string;status:string;progress:number;phase:string;nextAction:string;blockers:string[];techStack:string[];repository?:string;liveUrl?:string};
type Row={id:string;title:string;status:string;priority:string;due_date?:string|null};
const statusLabel:Record<string,string>={idea:'Idea',planning:'Planning','in-progress':'In progress',blocked:'Blocked',testing:'Testing',completed:'Completed',archived:'Archived'};

export default function ProjectWorkspace({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState('');const [project,setProject]=useState<Project|null>(null);const [tasks,setTasks]=useState<Row[]>([]);const [milestones,setMilestones]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [task,setTask]=useState('');const [milestone,setMilestone]=useState('');const [tab,setTab]=useState<'overview'|'execution'|'resources'>('overview');
 async function load(pid:string){setLoading(true);setError('');try{const [p,t,m]=await Promise.all([fetch(`/api/projects/${pid}`,{cache:'no-store'}),fetch(`/api/projects/tasks?projectId=${pid}`,{cache:'no-store'}),fetch(`/api/projects/milestones?projectId=${pid}`,{cache:'no-store'})]);if(!p.ok)throw new Error(p.status===401?'Please log in':'Unable to load project');setProject(await p.json());setTasks(t.ok?await t.json():[]);setMilestones(m.ok?await m.json():[])}catch(e){setError(e instanceof Error?e.message:'Unable to load project')}finally{setLoading(false)}}
 useEffect(()=>{params.then(x=>{setId(x.id);load(x.id)})},[params]);
 async function addTask(){if(!task.trim())return;const r=await fetch('/api/projects/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:id,title:task.trim()})});if(r.ok){setTask('');load(id)}else setError('Unable to create task')}
 async function addMilestone(){if(!milestone.trim())return;const r=await fetch('/api/projects/milestones',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:id,title:milestone.trim()})});if(r.ok){setMilestone('');load(id)}else setError('Unable to create milestone')}
 const doneTasks=useMemo(()=>tasks.filter(x=>x.status==='completed'||x.status==='done').length,[tasks]);const doneMilestones=useMemo(()=>milestones.filter(x=>x.status==='completed'||x.status==='done').length,[milestones]);const progress=Math.max(0,Math.min(100,project?.progress||0));
 if(loading)return <main className="mx-auto max-w-[1300px] space-y-5 p-4 md:p-8"><div className="h-5 w-32 animate-pulse rounded bg-muted"/><div className="h-40 animate-pulse rounded-3xl bg-muted"/><div className="grid gap-4 md:grid-cols-3"><div className="h-32 animate-pulse rounded-2xl bg-muted"/><div className="h-32 animate-pulse rounded-2xl bg-muted"/><div className="h-32 animate-pulse rounded-2xl bg-muted"/></div></main>;
 if(!project)return <main className="mx-auto max-w-5xl p-8"><p className="text-sm text-destructive">{error||'Project not found'}</p></main>;
 return <main className="min-h-screen bg-background"><div className="mx-auto max-w-[1300px] space-y-5 p-4 md:p-8">
  <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/projects" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="mr-1 h-4 w-4"/>Project command center</Link><Button variant="outline" onClick={()=>load(id)}><RefreshCw className="mr-2 h-4 w-4"/>Refresh workspace</Button></div>
  <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-card to-primary/5 p-6 md:p-8"><div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-primary/10 blur-3xl"/><div className="relative"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-primary/20 bg-primary/10 px-2.5 py-1 text-[10px] font-semibold text-primary">{project.priority}</span><span className="rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[10px] font-semibold">{statusLabel[project.status]||project.status}</span>{project.phase&&<span className="rounded-full border border-white/10 bg-white/[0.04] px-2.5 py-1 text-[10px]">{project.phase}</span>}</div><div className="mt-4 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-3xl font-bold tracking-tight md:text-5xl">{project.name}</h1><p className="mt-2 text-sm text-muted-foreground">{project.organization||'Independent'} · {project.role||'Owner'}</p></div><div className="w-full max-w-sm"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Overall delivery</span><b>{progress}%</b></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{width:`${progress}%`}}/></div></div></div></div></section>
  {error&&<div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card className="border-white/10"><CardContent className="p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><ListChecks className="h-4 w-4 text-primary"/>Tasks</div><div className="mt-2 text-2xl font-bold">{doneTasks}/{tasks.length}</div><p className="mt-1 text-[11px] text-muted-foreground">completed</p></CardContent></Card><Card className="border-white/10"><CardContent className="p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Flag className="h-4 w-4 text-primary"/>Milestones</div><div className="mt-2 text-2xl font-bold">{doneMilestones}/{milestones.length}</div><p className="mt-1 text-[11px] text-muted-foreground">completed</p></CardContent></Card><Card className="border-white/10"><CardContent className="p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Users className="h-4 w-4 text-primary"/>People</div><div className="mt-2 text-2xl font-bold">{project.people?.length||0}</div><p className="mt-1 text-[11px] text-muted-foreground">collaborators</p></CardContent></Card><Card className={`border-white/10 ${project.blockers?.length?'border-red-500/20':''}`}><CardContent className="p-4"><div className="flex items-center gap-2 text-xs text-muted-foreground"><CircleAlert className={`h-4 w-4 ${project.blockers?.length?'text-red-400':'text-primary'}`}/>Blockers</div><div className="mt-2 text-2xl font-bold">{project.blockers?.length||0}</div><p className="mt-1 text-[11px] text-muted-foreground">needs attention</p></CardContent></Card></section>
  <div className="flex gap-1 overflow-x-auto rounded-xl border border-white/10 bg-card/60 p-1"><button onClick={()=>setTab('overview')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab==='overview'?'bg-primary text-primary-foreground':'text-muted-foreground hover:text-foreground'}`}>Overview</button><button onClick={()=>setTab('execution')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab==='execution'?'bg-primary text-primary-foreground':'text-muted-foreground hover:text-foreground'}`}>Execution</button><button onClick={()=>setTab('resources')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${tab==='resources'?'bg-primary text-primary-foreground':'text-muted-foreground hover:text-foreground'}`}>Resources & team</button></div>
  {tab==='overview'&&<div className="grid gap-4 lg:grid-cols-[1.5fr_.8fr]"><Card className="border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><Rocket className="h-4 w-4 text-primary"/>Project brief</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm leading-6 text-muted-foreground">{project.description||'No project brief has been written yet. Use this space to define the outcome, scope and success criteria.'}</p><div className="rounded-xl border border-primary/15 bg-primary/[0.04] p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-primary">Next action</div><p className="mt-2 text-sm font-medium">{project.nextAction||'Set one concrete action that moves this project forward.'}</p></div>{project.blockers?.length>0&&<div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-red-300"><CircleAlert className="h-4 w-4"/>Blocked right now</div><ul className="mt-2 space-y-1 text-sm text-red-200">{project.blockers.map(x=><li key={x}>• {x}</li>)}</ul></div>}</CardContent></Card><Card className="border-white/10"><CardHeader><CardTitle>Project signals</CardTitle></CardHeader><CardContent className="space-y-4"><div><div className="text-[10px] uppercase tracking-wide text-muted-foreground">Phase</div><div className="mt-1 text-sm font-semibold">{project.phase||'Not set'}</div></div><div><div className="text-[10px] uppercase tracking-wide text-muted-foreground">Priority</div><div className="mt-1 text-sm font-semibold">{project.priority}</div></div><div><div className="text-[10px] uppercase tracking-wide text-muted-foreground">Owner / role</div><div className="mt-1 text-sm font-semibold">{project.role||'Owner'}</div></div><div><div className="text-[10px] uppercase tracking-wide text-muted-foreground">Team</div><div className="mt-2 flex flex-wrap gap-1.5">{project.people?.length?project.people.map(x=><span key={x} className="rounded-full bg-muted px-2 py-1 text-xs">{x}</span>):<span className="text-xs text-muted-foreground">Solo project</span>}</div></div></CardContent></Card></div>}
  {tab==='execution'&&<div className="grid gap-4 lg:grid-cols-2"><Card className="border-white/10"><CardHeader><CardTitle>Tasks</CardTitle><p className="text-xs text-muted-foreground">Turn the project into concrete actions.</p></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={task} onChange={e=>setTask(e.target.value)} placeholder="Add the next task…" onKeyDown={e=>e.key==='Enter'&&addTask()}/><Button size="icon" onClick={addTask} aria-label="Add task"><Plus className="h-4 w-4"/></Button></div>{tasks.length===0?<div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No tasks yet. Add the first executable action above.</div>:tasks.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-white/[0.02] p-3"><div className="flex min-w-0 items-center gap-2"><CheckCircle2 className="h-4 w-4 shrink-0 text-muted-foreground"/><span className="truncate text-sm">{x.title}</span></div><span className="shrink-0 rounded-full border px-2 py-1 text-[10px] text-muted-foreground">{x.status}</span></div>)}</CardContent></Card><Card className="border-white/10"><CardHeader><CardTitle>Milestones</CardTitle><p className="text-xs text-muted-foreground">Track meaningful checkpoints, not every tiny task.</p></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={milestone} onChange={e=>setMilestone(e.target.value)} placeholder="Add a milestone…" onKeyDown={e=>e.key==='Enter'&&addMilestone()}/><Button size="icon" onClick={addMilestone} aria-label="Add milestone"><Plus className="h-4 w-4"/></Button></div>{milestones.length===0?<div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">No milestones yet. Define the checkpoints that prove progress.</div>:milestones.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/5 bg-white/[0.02] p-3"><div className="flex min-w-0 items-center gap-2"><Target className="h-4 w-4 shrink-0 text-primary"/><span className="truncate text-sm">{x.title}</span></div><span className="shrink-0 rounded-full border px-2 py-1 text-[10px] text-muted-foreground">{x.status}</span></div>)}</CardContent></Card></div>}
  {tab==='resources'&&<div className="grid gap-4 lg:grid-cols-2"><Card className="border-white/10"><CardHeader><CardTitle>Technology & links</CardTitle></CardHeader><CardContent className="space-y-4"><div><div className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Tech stack</div><div className="flex flex-wrap gap-2">{project.techStack?.length?project.techStack.map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[0.03] px-2.5 py-1 text-xs">{x}</span>):<span className="text-sm text-muted-foreground">No stack recorded.</span>}</div></div><div className="flex flex-wrap gap-2">{project.repository&&<a href={project.repository} target="_blank" rel="noopener noreferrer"><Button variant="outline"><ExternalLink className="mr-2 h-4 w-4"/>Repository</Button></a>}{project.liveUrl&&<a href={project.liveUrl} target="_blank" rel="noopener noreferrer"><Button variant="outline"><ArrowUpRight className="mr-2 h-4 w-4"/>Live product</Button></a>}</div></CardContent></Card><Card className="border-white/10"><CardHeader><CardTitle>People & context</CardTitle></CardHeader><CardContent className="space-y-4"><div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Organization</div><div className="mt-1 text-sm font-medium">{project.organization||'Independent'}</div></div><div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Role</div><div className="mt-1 text-sm font-medium">{project.role||'Owner'}</div></div><div><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Collaborators</div><div className="mt-2 flex flex-wrap gap-2">{project.people?.length?project.people.map(x=><span key={x} className="rounded-full bg-muted px-2.5 py-1 text-xs">{x}</span>):<span className="text-sm text-muted-foreground">No collaborators recorded.</span>}</div></div></CardContent></Card></div>}
 </div></main>;
}
