'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Database, FileText, ListTodo, Plus, Repeat2, Search, Settings2, StickyNote, Target, Trash2, Undo2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';

type Tab = 'today'|'week'|'calendar'|'tasks'|'sticky'|'pages'|'recurring'|'database'|'progress'|'settings';
type Task = { id:string; title:string; date:string; done:boolean; deleted?:boolean; priority:'low'|'medium'|'high' };
type Note = { id:string; title:string; text:string; date:string; kind:'page'|'meeting'|'note' };
type Recurring = { id:string; title:string; cadence:'daily'|'weekdays'|'weekly'; active:boolean };
type Row = { id:string; name:string; status:string; due:string };
type Store = { tasks:Task[]; notes:Note[]; recurring:Recurring[]; rows:Row[]; lastPlanDate:string };

const KEY='streamearn-planner-v4';
const iso=(d:Date)=>d.toISOString().slice(0,10);
const today=()=>iso(new Date());
const dateOf=(s:string)=>new Date(`${s}T12:00:00`);
const shift=(s:string,n:number)=>{const d=dateOf(s);d.setDate(d.getDate()+n);return iso(d)};
const fresh=():Store=>({tasks:[],notes:[],recurring:[],rows:[],lastPlanDate:today()});
const rid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
function readStore():Store{if(typeof window==='undefined')return fresh();try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?{...fresh(),...x}:fresh()}catch{return fresh()}}
function carry(s:Store):Store{const t=today();if(s.lastPlanDate===t)return s;const old=s.tasks.filter(x=>x.date===s.lastPlanDate&&!x.done&&!x.deleted);const existing=new Set(s.tasks.filter(x=>x.date===t&&!x.deleted).map(x=>x.title.trim().toLowerCase()));const moved=old.filter(x=>!existing.has(x.title.trim().toLowerCase())).map(x=>({...x,id:rid(),date:t}));return {...s,tasks:[...s.tasks,...moved],lastPlanDate:t}}

const NAV:[Tab,string,any][]=[['today','Today',ClipboardList],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',CheckCircle2],['sticky','Sticky Wall',StickyNote],['pages','Pages & Notes',FileText],['recurring','Recurring',Repeat2],['database','Database',Database],['progress','Progress',Target],['settings','Settings',Settings2]];

export default function PlannerPage(){
 const [store,setStore]=useState<Store>(()=>carry(readStore()));
 const [tab,setTab]=useState<Tab>('today'); const [date,setDate]=useState(today()); const [task,setTask]=useState(''); const [filter,setFilter]=useState(''); const [noteTitle,setNoteTitle]=useState(''); const [noteText,setNoteText]=useState(''); const [recurring,setRecurring]=useState(''); const [rowName,setRowName]=useState(''); const [rowStatus,setRowStatus]=useState('Planned');
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(store))},[store]);
 const activeTasks=store.tasks.filter(x=>!x.deleted); const deleted=store.tasks.filter(x=>x.deleted); const completed=activeTasks.filter(x=>x.done).length; const percent=activeTasks.length?Math.round(completed/activeTasks.length*100):0;
 const dayTasks=useMemo(()=>activeTasks.filter(x=>x.date===date&&x.title.toLowerCase().includes(filter.toLowerCase())),[activeTasks,date,filter]);
 const week=useMemo(()=>Array.from({length:7},(_,i)=>shift(date,i)),[date]);
 const monthCells=useMemo(()=>{const first=dateOf(date);first.setDate(1);return Array.from({length:42},(_,i)=>{const d=new Date(first);d.setDate(i-first.getDay()+1);return iso(d)})},[date]);
 const addTask=()=>{const v=task.trim();if(!v)return;setStore(s=>({...s,tasks:[...s.tasks,{id:rid(),title:v,date,done:false,priority:'medium'}]}));setTask('')};
 const toggle=(id:string)=>setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===id?{...x,done:!x.done}:x)}));
 const trash=(id:string)=>setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===id?{...x,deleted:true}:x)}));
 const restore=(id:string)=>setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===id?{...x,deleted:false}:x)}));
 const addNote=(kind:Note['kind'])=>{const text=noteText.trim();if(!text)return;const title=noteTitle.trim()||({page:'Untitled page',meeting:'Meeting notes',note:'Quick note'}[kind]);setStore(s=>({...s,notes:[{id:rid(),title,text,date,kind},...s.notes]}));setNoteTitle('');setNoteText('')};
 const addRecurring=()=>{const v=recurring.trim();if(!v)return;setStore(s=>({...s,recurring:[...s.recurring,{id:rid(),title:v,cadence:'daily',active:true}]}));setRecurring('')};
 const addRow=()=>{const v=rowName.trim();if(!v)return;setStore(s=>({...s,rows:[...s.rows,{id:rid(),name:v,status:rowStatus,due:date}]}));setRowName('')};
 const goSticky=()=>{window.location.href='/planner/sticky'};
 let body:any;
 if(tab==='today')body=<Today date={date} tasks={dayTasks} task={task} setTask={setTask} add={addTask} filter={filter} setFilter={setFilter} toggle={toggle} trash={trash} percent={percent} completed={completed} total={activeTasks.length} goSticky={()=>setTab('sticky')}/>;
 else if(tab==='week')body=<Week days={week} tasks={activeTasks} pick={(d:string)=>{setDate(d);setTab('today')}}/>;
 else if(tab==='calendar')body=<Calendar cells={monthCells} tasks={activeTasks} pick={(d:string)=>{setDate(d);setTab('today')}}/>;
 else if(tab==='tasks')body=<Tasks tasks={activeTasks} deleted={deleted} toggle={toggle} trash={trash} restore={restore}/>;
 else if(tab==='sticky')body=<StickyLaunch open={goSticky}/>;
 else if(tab==='pages')body=<Pages title={noteTitle} setTitle={setNoteTitle} text={noteText} setText={setNoteText} add={addNote} notes={store.notes}/>;
 else if(tab==='recurring')body=<Recurring value={recurring} setValue={setRecurring} add={addRecurring} items={store.recurring} remove={(id:string)=>setStore(s=>({...s,recurring:s.recurring.filter(x=>x.id!==id)}))}/>;
 else if(tab==='database')body=<Database name={rowName} setName={setRowName} status={rowStatus} setStatus={setRowStatus} add={addRow} rows={store.rows} remove={(id:string)=>setStore(s=>({...s,rows:s.rows.filter(x=>x.id!==id)}))}/>;
 else if(tab==='progress')body=<Progress total={activeTasks.length} completed={completed} percent={percent}/>;
 else body=<Settings reset={()=>{localStorage.removeItem(KEY);setStore(fresh())}}/>;
 return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen bg-background"><div className="mx-auto max-w-[1280px] px-4 py-5 md:px-7 md:py-7">
  <header className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-[.18em] text-muted-foreground">Personal command centre</div><h1 className="text-3xl font-semibold tracking-tight">Planner</h1><p className="mt-1 text-sm text-muted-foreground">Tasks, calendar, notes, sticky wall, recurring work, database and progress — local-first and private.</p></div><div className="flex items-center gap-1 rounded-lg border bg-card p-1"><Button size="sm" variant="ghost" onClick={()=>setDate(shift(date,-1))}><ChevronLeft className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={()=>setDate(today())}>Today</Button><Button size="sm" variant="ghost" onClick={()=>setDate(shift(date,1))}><ChevronRight className="h-4 w-4"/></Button></div></header>
  <div className="mb-5 overflow-x-auto border-b pb-2"><div className="flex min-w-max gap-1">{NAV.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div></div>{body}
 </div></main></SidebarInset></SidebarProvider>;
}

function Today(p:any){return <section className="grid gap-5 lg:grid-cols-[1fr_300px]"><div className="rounded-xl border bg-card p-4 md:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{p.date===today()?'Today':dateOf(p.date).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</h2><p className="text-xs text-muted-foreground">Unfinished tasks carry forward automatically.</p></div><Badge variant="secondary">{p.tasks.filter((x:any)=>!x.done).length} pending</Badge></div><form className="mb-3 flex gap-2" onSubmit={(e:any)=>{e.preventDefault();p.add()}}><Input value={p.task} onChange={(e:any)=>p.setTask(e.target.value)} placeholder="Add a task…"/><Button size="sm" type="submit"><Plus className="mr-1.5 h-4 w-4"/>Add</Button></form><div className="mb-3 flex items-center gap-2"><Search className="h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8" value={p.filter} onChange={(e:any)=>p.setFilter(e.target.value)} placeholder="Filter tasks…"/></div><div className="divide-y">{p.tasks.length===0?<p className="py-12 text-center text-sm text-muted-foreground">No tasks for this day.</p>:p.tasks.map((t:any)=><div key={t.id} className="group flex items-center gap-3 py-3"><button onClick={()=>p.toggle(t.id)} aria-label="Toggle task">{t.done?<CheckCircle2 className="h-5 w-5 text-primary"/>:<span className="block h-5 w-5 rounded-full border-2"/>}</button><span className={`min-w-0 flex-1 text-sm ${t.done?'line-through text-muted-foreground':''}`}>{t.title}</span><Badge variant="outline" className="hidden text-[10px] sm:inline-flex">{t.priority}</Badge><button onClick={()=>p.trash(t.id)} className="opacity-0 group-hover:opacity-100" aria-label="Archive task"><Trash2 className="h-4 w-4 text-muted-foreground"/></button></div>)}</div></div><aside className="space-y-3"><Stat title="Progress" value={`${p.percent}%`} detail={`${p.completed} completed of ${p.total}`}/><Stat title="Active tasks" value={`${p.total}`} detail="across all dates"/><div className="rounded-xl border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Quick actions</p><div className="mt-2 grid gap-2"><Button size="sm" variant="outline" onClick={p.goSticky}><StickyNote className="mr-1.5 h-4 w-4"/>Sticky Wall</Button><Button size="sm" variant="outline">Pages & Notes</Button></div></div></aside></section>}
function Week({days,tasks,pick}:any){return <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{days.map((d:string)=><button key={d} onClick={()=>pick(d)} className="min-h-36 rounded-xl border bg-card p-3 text-left hover:border-primary/50 hover:bg-muted/30"><p className="text-xs font-semibold">{dateOf(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[11px] text-muted-foreground">{dateOf(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p><div className="mt-3 space-y-1.5">{tasks.filter((x:any)=>x.date===d).slice(0,6).map((x:any)=><div key={x.id} className={`truncate text-xs ${x.done?'line-through text-muted-foreground':''}`}>• {x.title}</div>)}</div></button>)}</section>}
function Calendar({cells,tasks,pick}:any){return <section className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Calendar</h2><span className="text-xs text-muted-foreground">Click a date</span></div><div className="grid grid-cols-7 gap-1">{cells.map((d:string,i:number)=>{const count=tasks.filter((x:any)=>x.date===d).length;return <button key={`${d}-${i}`} onClick={()=>pick(d)} className={`min-h-16 rounded-md border p-2 text-left hover:bg-muted ${d===today()?'border-primary':''}`}><span className="text-xs font-medium">{dateOf(d).getDate()}</span>{count>0&&<span className="mt-1 block text-[10px] text-muted-foreground">{count} task{count>1?'s':''}</span>}</button>})}</div></section>}
function Tasks({tasks,deleted,toggle,trash,restore}:any){return <section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">All To-Do</h2><div className="mt-3 divide-y">{tasks.length===0?<p className="py-10 text-sm text-muted-foreground">No tasks.</p>:tasks.map((t:any)=><div key={t.id} className="flex items-center gap-3 py-3"><button onClick={()=>toggle(t.id)}>{t.done?<CheckCircle2 className="h-5 w-5 text-primary"/>:<span className="block h-5 w-5 rounded-full border-2"/>}</button><span className={`min-w-0 flex-1 text-sm ${t.done?'line-through text-muted-foreground':''}`}>{t.title}</span><span className="text-[10px] text-muted-foreground">{t.date}</span><button onClick={()=>trash(t.id)}><Trash2 className="h-4 w-4 text-muted-foreground"/></button></div>)}</div></div><div className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Archive</h3><div className="mt-3 space-y-2">{deleted.length===0?<p className="text-xs text-muted-foreground">Archive is empty.</p>:deleted.map((t:any)=><div key={t.id} className="flex items-center gap-2 text-xs"><span className="flex-1 truncate">{t.title}</span><button onClick={()=>restore(t.id)} title="Restore"><Undo2 className="h-4 w-4"/></button></div>)}</div></div></section>}
function StickyLaunch({open}:any){return <section className="rounded-2xl border bg-card p-8 text-center"><div className="mx-auto mb-4 h-16 w-16 -rotate-6 rounded bg-gradient-to-br from-[#EFD45B] to-[#DDBB2E] shadow-xl"/><h2 className="text-xl font-semibold">Sticky Wall</h2><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">A tactile, draggable local sticky-note board with six colors, five paper styles, search, archive, date picker and persistent storage.</p><Button className="mt-5" onClick={open}><StickyNote className="mr-2 h-4 w-4"/>Open Sticky Wall</Button></section>}
function Pages(p:any){return <section className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Create a page or note</h2><Input className="mt-3" value={p.title} onChange={(e:any)=>p.setTitle(e.target.value)} placeholder="Title"/><textarea value={p.text} onChange={(e:any)=>p.setText(e.target.value)} placeholder="Write notes…" className="mt-2 min-h-44 w-full rounded-md border bg-background p-3 text-sm outline-none"/><div className="mt-2 grid grid-cols-3 gap-2"><Button size="sm" onClick={()=>p.add('page')}>Page</Button><Button size="sm" variant="outline" onClick={()=>p.add('meeting')}>Meeting</Button><Button size="sm" variant="outline" onClick={()=>p.add('note')}>Note</Button></div></div><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Saved</h2><div className="mt-3 grid gap-2">{p.notes.length===0?<p className="text-sm text-muted-foreground">Nothing saved yet.</p>:p.notes.map((n:any)=><article key={n.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">{n.title}</h3><Badge variant="secondary" className="text-[10px]">{n.kind}</Badge></div><p className="mt-1 whitespace-pre-wrap text-xs text-muted-foreground">{n.text}</p></article>)}</div></div></section>}
function Recurring({value,setValue,add,items,remove}:any){return <section className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Recurring tasks</h2><form className="mt-3 flex gap-2" onSubmit={(e:any)=>{e.preventDefault();add()}}><Input value={value} onChange={(e:any)=>setValue(e.target.value)} placeholder="e.g. Review alerts"/><Button size="sm" type="submit"><Plus className="h-4 w-4"/></Button></form><p className="mt-2 text-xs text-muted-foreground">Create repeatable reminders without any external service.</p></div><div className="rounded-xl border bg-card p-4"><div className="space-y-2">{items.length===0?<p className="text-sm text-muted-foreground">No recurring tasks.</p>:items.map((x:any)=><div key={x.id} className="flex items-center gap-3 rounded-lg border p-3"><Repeat2 className="h-4 w-4 text-muted-foreground"/><span className="flex-1 text-sm">{x.title}</span><Badge variant="outline">{x.cadence}</Badge><button onClick={()=>remove(x.id)}><Trash2 className="h-4 w-4 text-muted-foreground"/></button></div>)}</div></div></section>}
function Database(p:any){return <section className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Personal database</h2><Input className="mt-3" value={p.name} onChange={(e:any)=>p.setName(e.target.value)} placeholder="Item name"/><select className="mt-2 h-9 w-full rounded-md border bg-background px-2 text-sm" value={p.status} onChange={(e:any)=>p.setStatus(e.target.value)}><option>Planned</option><option>Active</option><option>Done</option><option>Blocked</option></select><Button className="mt-2 w-full" onClick={p.add}><Plus className="mr-1.5 h-4 w-4"/>Add row</Button></div><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Rows</h2><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="pb-2">Name</th><th className="pb-2">Status</th><th className="pb-2">Due</th><th/></tr></thead><tbody>{p.rows.map((r:any)=><tr key={r.id} className="border-t"><td className="py-2">{r.name}</td><td className="py-2">{r.status}</td><td className="py-2 text-xs text-muted-foreground">{r.due}</td><td className="py-2 text-right"><button onClick={()=>p.remove(r.id)}><Trash2 className="h-4 w-4 text-muted-foreground"/></button></td></tr>)}</tbody></table></div></div></section>}
function Progress({total,completed,percent}:any){return <section className="grid gap-4 sm:grid-cols-3"><Stat title="Tasks" value={total} detail="active"/><Stat title="Completed" value={completed} detail="finished"/><Stat title="Completion" value={`${percent}%`} detail="across planner"/></section>}
function Stat({title,value,detail}:{title:string,value:string|number,detail:string}){return <div className="rounded-xl border bg-card p-4"><p className="text-xs uppercase tracking-wider text-muted-foreground">{title}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>}
function Settings({reset}:any){return <section className="max-w-xl rounded-xl border bg-card p-5"><h2 className="font-semibold">Planner settings</h2><p className="mt-1 text-sm text-muted-foreground">Everything is stored locally in this browser. Clearing resets Planner data on this device.</p><Button variant="destructive" className="mt-5" onClick={()=>{if(confirm('Reset all Planner data on this device?'))reset()}}>Reset local Planner</Button></section>}
