'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Database, FileText, ListTodo, MessageSquareText, Plus, Repeat2, Search, Settings2, Sparkles, StickyNote, Target, Trash2, Undo2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { UnifiedSidebar } from '@/components/unified-sidebar';

type Task = { id:string; title:string; date:string; done:boolean; priority:'low'|'medium'|'high'; recurring?:boolean; deleted?:boolean };
type Note = { id:string; title:string; text:string; date:string; kind:'note'|'meeting'|'page' };
type Sticky = { id:string; text:string; color:string; created:string };
type Recurring = { id:string; title:string; cadence:'daily'|'weekdays'|'weekly'; active:boolean };
type DbRow = { id:string; name:string; status:string; due:string };
type Store = { tasks:Task[]; notes:Note[]; sticky:Sticky[]; recurring:Recurring[]; db:DbRow[]; lastPlanDate:string };

const KEY='streamearn-xara-planner-v2';
const iso=(d:Date)=>d.toISOString().slice(0,10);
const today=()=>iso(new Date());
const parse=(s:string)=>new Date(`${s}T12:00:00`);
const add=(s:string,n:number)=>{const d=parse(s);d.setDate(d.getDate()+n);return iso(d)};
const empty=():Store=>({tasks:[],notes:[],sticky:[],recurring:[],db:[],lastPlanDate:today()});
function load():Store{if(typeof window==='undefined')return empty();try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?{...empty(),...x}:empty()}catch{return empty()}}
function carry(s:Store):Store{const t=today();if(s.lastPlanDate===t)return s;const pending=s.tasks.filter(x=>x.date===s.lastPlanDate&&!x.done&&!x.deleted);const existing=new Set(s.tasks.filter(x=>x.date===t&&!x.deleted).map(x=>x.title.trim().toLowerCase()));const moved=pending.filter(x=>!existing.has(x.title.trim().toLowerCase())).map(x=>({...x,id:crypto.randomUUID(),date:t}));return {...s,tasks:[...s.tasks,...moved],lastPlanDate:t}}

const tabs=[
 ['today','Today',ClipboardList],['week','Week',ListTodo],['calendar','Calendar',CalendarDays],['tasks','To-Do',CheckCircle2],['sticky','Sticky Wall',StickyNote],['pages','Pages',FileText],['recurring','Recurring',Repeat2],['database','Database',Database],['progress','Progress',Target],['ai','Xara AI',Sparkles],['settings','Settings',Settings2],
] as const;

type Tab=typeof tabs[number][0];

export default function PlannerPage(){
 const [store,setStore]=useState<Store>(()=>carry(load()));
 const [tab,setTab]=useState<Tab>('today'); const [date,setDate]=useState(today()); const [q,setQ]=useState('');
 const [task,setTask]=useState(''); const [note,setNote]=useState(''); const [noteTitle,setNoteTitle]=useState(''); const [sticky,setSticky]=useState(''); const [chat,setChat]=useState(''); const [chatLog,setChatLog]=useState<{role:'user'|'assistant';text:string}[]>([]); const [busy,setBusy]=useState(false);
 const [rec,setRec]=useState(''); const [dbName,setDbName]=useState(''); const [dbStatus,setDbStatus]=useState('Planned');
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(store))},[store]);
 const tasks=useMemo(()=>store.tasks.filter(x=>x.date===date&&!x.deleted),[store.tasks,date]);
 const allTasks=store.tasks.filter(x=>!x.deleted); const done=allTasks.filter(x=>x.done).length; const progress=allTasks.length?Math.round(done/allTasks.length*100):0;
 const filtered=tasks.filter(x=>x.title.toLowerCase().includes(q.toLowerCase()));
 function addTask(){const v=task.trim();if(!v)return;setStore(s=>({...s,tasks:[...s.tasks,{id:crypto.randomUUID(),title:v,date,done:false,priority:'medium'}]}));setTask('')}
 function toggle(id:string){setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===id?{...x,done:!x.done}:x)}))}
 function remove(id:string){setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===id?{...x,deleted:true}:x)}))}
 function restore(id:string){setStore(s=>({...s,tasks:s.tasks.map(x=>x.id===id?{...x,deleted:false}:x)}))}
 function addNote(kind:'note'|'meeting'|'page'='note'){const t=note.trim();if(!t)return;setStore(s=>({...s,notes:[{id:crypto.randomUUID(),title:noteTitle.trim()||kind==='meeting'?'Meeting notes':kind==='page'?'Untitled page':'Quick note',text:t,date,kind},...s.notes]}));setNote('');setNoteTitle('')}
 function addSticky(){const t=sticky.trim();if(!t)return;setStore(s=>({...s,sticky:[{id:crypto.randomUUID(),text:t,color:['#fef3c7','#dbeafe','#dcfce7','#fce7f3'][s.sticky.length%4],created:today()},...s.sticky]}));setSticky('')}
 function addRecurring(){const t=rec.trim();if(!t)return;setStore(s=>({...s,recurring:[...s.recurring,{id:crypto.randomUUID(),title:t,cadence:'daily',active:true}]}));setRec('')}
 function addDb(){const n=dbName.trim();if(!n)return;setStore(s=>({...s,db:[...s.db,{id:crypto.randomUUID(),name:n,status:dbStatus,due:date}]}));setDbName('')}
 async function askXara(){const v=chat.trim();if(!v)return;setChat('');setChatLog(x=>[...x,{role:'user',text:v}]);setBusy(true);try{const r=await fetch('/api/planner-chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:v,context:{date,tasks:store.tasks.filter(x=>!x.deleted).slice(-30),notes:store.notes.slice(0,10)}})});const data=await r.json();setChatLog(x=>[...x,{role:'assistant',text:data.reply||data.error||'AI service is not configured.'}])}catch{setChatLog(x=>[...x,{role:'assistant',text:'AI service is not configured on this deployment. Planner data still works locally.'}])}finally{setBusy(false)}}
 const days=useMemo(()=>Array.from({length:7},(_,i)=>add(date,i)),[date]);
 const deleted=store.tasks.filter(x=>x.deleted);
 return <SidebarProvider><UnifiedSidebar/><SidebarInset><main className="min-h-screen bg-background overflow-x-hidden"><div className="mx-auto max-w-[1280px] px-4 py-5 md:px-7 md:py-7">
  <header className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><div className="mb-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">Personal command centre</div><h1 className="text-3xl font-semibold tracking-tight">Xara Planner</h1><p className="mt-1 text-sm text-muted-foreground">Tasks, calendar, notes, sticky ideas, recurring work, pages, database and Xara AI in one workspace.</p></div><div className="flex items-center gap-1 rounded-lg border bg-card p-1"><Button size="sm" variant="ghost" onClick={()=>setDate(add(date,-1))}><ChevronLeft className="h-4 w-4"/></Button><Button size="sm" variant="ghost" onClick={()=>setDate(today())}>Today</Button><Button size="sm" variant="ghost" onClick={()=>setDate(add(date,1))}><ChevronRight className="h-4 w-4"/></Button></div></header>
  <div className="mb-5 overflow-x-auto border-b pb-2"><div className="flex min-w-max gap-1">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-xs font-medium ${tab===id?'bg-foreground text-background':'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div></div>
  {tab==='today'&&<section className="grid gap-5 lg:grid-cols-[1fr_300px]"><div className="rounded-xl border bg-card p-4 md:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">{date===today()?'Today':parse(date).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</h2><p className="text-xs text-muted-foreground">Pending work automatically carries into the next day.</p></div><Badge variant="secondary">{tasks.filter(x=>!x.done).length} pending</Badge></div><form onSubmit={e=>{e.preventDefault();addTask()}} className="mb-4 flex gap-2"><Input value={task} onChange={e=>setTask(e.target.value)} placeholder="Add a task…"/><Button type="submit" size="sm"><Plus className="mr-1.5 h-4 w-4"/>Add</Button></form><div className="mb-3 flex items-center gap-2"><Search className="h-3.5 w-3.5 text-muted-foreground"/><Input className="h-8" value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter today's tasks…"/></div><div className="divide-y">{filtered.length===0?<div className="py-12 text-center text-sm text-muted-foreground">No tasks yet.</div>:filtered.map(t=><TaskRow key={t.id} t={t} toggle={toggle} remove={remove}/>)}</div></div><aside className="space-y-3"><Stat title="Progress" value={`${progress}%`} detail={`${done} completed of ${allTasks.length}`}/><Stat title="Today" value={`${tasks.length}`} detail={`${tasks.filter(x=>!x.done).length} pending`}/><div className="rounded-xl border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Xara actions</p><div className="mt-2 grid gap-2"><Button size="sm" variant="outline" onClick={()=>setTab('ai')}>Ask Xara</Button><Button size="sm" variant="outline" onClick={()=>setTab('sticky')}>Open Sticky Wall</Button><Button size="sm" variant="outline" onClick={()=>setTab('pages')}>Open Pages</Button></div></div></aside></section>}
  {tab==='week'&&<section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{days.map(d=><button key={d} onClick={()=>{setDate(d);setTab('today')}} className="min-h-36 rounded-xl border bg-card p-3 text-left hover:border-primary/50 hover:bg-muted/30"><p className="text-xs font-semibold">{parse(d).toLocaleDateString(undefined,{weekday:'short'})}</p><p className="text-[11px] text-muted-foreground">{parse(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</p><div className="mt-3 space-y-1.5">{store.tasks.filter(x=>x.date===d&&!x.deleted).slice(0,5).map(x=><div key={x.id} className={`truncate text-xs ${x.done?'line-through text-muted-foreground':''}`}>• {x.title}</div>)}</div></button>)}</section>}
  {tab==='calendar'&&<section className="rounded-xl border bg-card p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Calendar</h2><span className="text-xs text-muted-foreground">{parse(date).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</span></div><div className="grid grid-cols-7 gap-1">{Array.from({length:35},(_,i)=>{const first=new Date(parse(date).getFullYear(),parse(date).getMonth(),1);const d=new Date(first);d.setDate(i-first.getDay()+1);const ds=iso(d);const count=store.tasks.filter(x=>x.date===ds&&!x.deleted).length;return <button key={`${ds}-${i}`} onClick={()=>{setDate(ds);setTab('today')}} className={`min-h-16 rounded-md border p-2 text-left hover:bg-muted ${ds===today()?'border-primary':''}`}><span className="text-xs font-medium">{d.getDate()}</span>{count>0&&<span className="mt-1 block text-[10px] text-muted-foreground">{count} task{count>1?'s':''}</span>}</button>})}</div></section>}
  {tab==='tasks'&&<section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">All To-Do</h2><p className="mb-4 text-xs text-muted-foreground">Persistent tasks across every day.</p><div className="divide-y">{allTasks.length===0?<p className="py-10 text-sm text-muted-foreground">No tasks.</p>:allTasks.map(t=><div key={t.id} className="flex items-center gap-3 py-3"><button onClick={()=>toggle(t.id)}>{t.done?<CheckCircle2 className="h-5 w-5 text-primary"/>:<span className="block h-5 w-5 rounded-full border-2"/>}</button><div className="min-w-0 flex-1"><p className={`text-sm ${t.done?'line-through text-muted-foreground':''}`}>{t.title}</p><p className="text-[10px] text-muted-foreground">{t.date}</p></div><button onClick={()=>remove(t.id)}><Trash2 className="h-4 w-4 text-muted-foreground"/></button></div>)}</div></div><div className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Trash</h3><div className="mt-3 space-y-2">{deleted.length===0?<p className="text-xs text-muted-foreground">Trash is empty.</p>:deleted.map(t=><div key={t.id} className="flex items-center gap-2 text-xs"><span className="flex-1 line-through">{t.title}</span><button onClick={()=>restore(t.id)} title="Restore"><Undo2 className="h-3.5 w-3.5"/></button></div>)}</div></div></section>}
  {tab==='sticky'&&<section className="grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Sticky Wall</h2><Input className="mt-3" value={sticky} onChange={e=>setSticky(e.target.value)} placeholder="Pin an idea…"/><Button className="mt-2" size="sm" onClick={addSticky}>Pin note</Button></div>{store.sticky.map(n=><article key={n.id} className="min-h-36 rounded-xl border p-4" style={{background:n.color}}><div className="flex justify-between"><StickyNote className="h-4 w-4"/><button onClick={()=>setStore(s=>({...s,sticky:s.sticky.filter(x=>x.id!==n.id)}))}><Trash2 className="h-3.5 w-3.5"/></button></div><p className="mt-5 text-sm whitespace-pre-wrap">{n.text}</p></article>)}</section>}
  {tab==='pages'&&<section className="grid gap-4 lg:grid-cols-[320px_1fr]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Pages & Notes</h2><Input className="mt-3" value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Page title"/><textarea className="mt-2 min-h-44 w-full rounded-lg border bg-background p-3 text-sm outline-none" value={note} onChange={e=>setNote(e.target.value)} placeholder="Write blocks, meeting notes, project ideas…"/><div className="mt-2 flex gap-2"><Button size="sm" onClick={()=>addNote('page')}>Create page</Button><Button size="sm" variant="outline" onClick={()=>addNote('meeting')}>Meeting notes</Button></div></div><div className="space-y-2">{store.notes.length===0?<div className="rounded-xl border bg-card p-8 text-center text-sm text-muted-foreground">No pages yet.</div>:store.notes.map(n=><article key={n.id} className="rounded-xl border bg-card p-4"><div className="flex items-center gap-2"><FileText className="h-4 w-4"/><h3 className="font-medium">{n.title}</h3><Badge variant="secondary" className="ml-auto">{n.kind}</Badge></div><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{n.text}</p><p className="mt-3 text-[10px] text-muted-foreground">{n.date}</p></article>)}</div></section>}
  {tab==='recurring'&&<section className="grid gap-5 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Recurring Tasks</h2><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();addRecurring()}}><Input value={rec} onChange={e=>setRec(e.target.value)} placeholder="Daily review, weekly report…"/><Button type="submit" size="sm"><Plus className="h-4 w-4"/></Button></form><div className="mt-4 divide-y">{store.recurring.map(r=><div key={r.id} className="flex items-center gap-3 py-3"><Repeat2 className="h-4 w-4"/><span className="flex-1 text-sm">{r.title}</span><Badge variant="outline">{r.cadence}</Badge><button onClick={()=>setStore(s=>({...s,recurring:s.recurring.filter(x=>x.id!==r.id)}))}><Trash2 className="h-4 w-4"/></button></div>)}</div></section>}
  {tab==='database'&&<section className="rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center gap-2"><div><h2 className="font-semibold">Personal Database</h2><p className="text-xs text-muted-foreground">A compact table for projects, applications, ideas or anything you track.</p></div><div className="ml-auto flex gap-2"><Input className="w-44" value={dbName} onChange={e=>setDbName(e.target.value)} placeholder="New row…"/><select className="h-9 rounded-md border bg-background px-2 text-sm" value={dbStatus} onChange={e=>setDbStatus(e.target.value)}><option>Planned</option><option>Active</option><option>Done</option><option>Waiting</option></select><Button size="sm" onClick={addDb}>Add</Button></div></div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-2">Name</th><th className="p-2">Status</th><th className="p-2">Date</th><th className="p-2"/></tr></thead><tbody>{store.db.map(r=><tr key={r.id} className="border-b"><td className="p-2">{r.name}</td><td className="p-2">{r.status}</td><td className="p-2">{r.due}</td><td className="p-2 text-right"><button onClick={()=>setStore(s=>({...s,db:s.db.filter(x=>x.id!==r.id)}))}><Trash2 className="h-4 w-4 text-muted-foreground"/></button></td></tr>)}</tbody></table></div></section>}
  {tab==='progress'&&<section className="grid gap-3 sm:grid-cols-3"><Stat title="All tasks" value={`${allTasks.length}`} detail="Across all dates"/><Stat title="Completed" value={`${done}`} detail="Finished tasks"/><Stat title="Completion" value={`${progress}%`} detail="Overall completion"/></section>}
  {tab==='ai'&&<section className="mx-auto max-w-3xl rounded-xl border bg-card"><div className="border-b p-4"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Xara AI</h2><p className="text-xs text-muted-foreground">The planner assistant from the Xara project: ask it to plan, search, create tasks, summarize or prepare meeting notes.</p></div></div></div><div className="min-h-[360px] space-y-3 p-4">{chatLog.length===0&&<div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Try: “Plan my day”, “Create tasks for my cybersecurity project”, “Summarize my notes”, or “Prepare meeting action items”.</div>}{chatLog.map((m,i)=><div key={i} className={m.role==='user'?'ml-auto max-w-[80%] rounded-xl bg-muted p-3 text-sm':'max-w-[90%] whitespace-pre-wrap p-2 text-sm'}>{m.text}</div>)}{busy&&<div className="text-xs text-muted-foreground">Xara is working…</div>}</div><form className="flex gap-2 border-t p-3" onSubmit={e=>{e.preventDefault();askXara()}}><Input value={chat} onChange={e=>setChat(e.target.value)} placeholder="Ask Xara to act on your planner…"/><Button type="submit" disabled={busy}>Send</Button></form></section>}
  {tab==='settings'&&<section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Planner storage</h2><p className="mt-1 text-sm text-muted-foreground">All planner data is stored locally in this browser. No external database is required for these local planner features.</p><Button className="mt-4" variant="destructive" onClick={()=>{localStorage.removeItem(KEY);setStore(empty())}}>Reset local planner</Button></div><div className="rounded-xl border bg-card p-4"><h2 className="font-semibold">Daily carry</h2><p className="mt-1 text-sm text-muted-foreground">Incomplete tasks silently roll into the next day. Completed tasks remain on their original date.</p></div></section>}
 </div></main></SidebarInset></SidebarProvider>
}

function TaskRow({t,toggle,remove}:{t:Task;toggle:(id:string)=>void;remove:(id:string)=>void}){return <div className="group flex items-center gap-3 py-3"><button onClick={()=>toggle(t.id)}>{t.done?<CheckCircle2 className="h-5 w-5 text-primary"/>:<span className="block h-5 w-5 rounded-full border-2"/>}</button><span className={`min-w-0 flex-1 text-sm ${t.done?'line-through text-muted-foreground':''}`}>{t.title}</span><Badge variant="outline" className="hidden sm:inline-flex text-[10px]">{t.priority}</Badge><button onClick={()=>remove(t.id)} className="opacity-0 group-hover:opacity-100"><Trash2 className="h-4 w-4 text-muted-foreground"/></button></div>}
function Stat({title,value,detail}:{title:string;value:string;detail:string}){return <div className="rounded-xl border bg-card p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{title}</p><p className="mt-1 text-3xl font-semibold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>}
